"ID","NAME","ENTITY_ID__C","FIELD_LABEL__C","FIELD_APINAME__C","DATA_TYPE__C","SOURCE_TYPE__C","VALUES__C","GROUP_NAME__C","EXTERNAL_UID__C","ENTITY_CODE__C"
"a0K28000000V5cjEAC","PaymentType","a0J28000002aEkBEAU","","PaymentType","","","","","a0J28000002aEkBEAU-PaymentType","Sage100PaymentType"
"a0K28000000V5ckEAC","PaymentDesc","a0J28000002aEkBEAU","","PaymentDesc","","","","","a0J28000002aEkBEAU-PaymentDesc","Sage100PaymentType"
"a0K28000000V5clEAC","PaymentMethod","a0J28000002aEkBEAU","","PaymentMethod","","","","","a0J28000002aEkBEAU-PaymentMethod","Sage100PaymentType"
"a0K28000000V5cmEAC","AssetAcctKey","a0J28000002aEkBEAU","","AssetAcctKey","","","","","a0J28000002aEkBEAU-AssetAcctKey","Sage100PaymentType"
"a0K28000000V5cnEAC","CreditCardAccrualAcctKey","a0J28000002aEkBEAU","","CreditCardAccrualAcctKey","","","","","a0J28000002aEkBEAU-CreditCardAccrualAcctKey","Sage100PaymentType"
"a0K28000000V5coEAC","DefaultTransaction","a0J28000002aEkBEAU","","DefaultTransaction","","","","","a0J28000002aEkBEAU-DefaultTransaction","Sage100PaymentType"
"a0K28000000V5cpEAC","EBMInternetEnabled","a0J28000002aEkBEAU","","EBMInternetEnabled","","","","","a0J28000002aEkBEAU-EBMInternetEnabled","Sage100PaymentType"
"a0K28000000V5cqEAC","CreditCardSetupTested","a0J28000002aEkBEAU","","CreditCardSetupTested","","","","","a0J28000002aEkBEAU-CreditCardSetupTested","Sage100PaymentType"
"a0K28000000V5crEAC","MerchantID","a0J28000002aEkBEAU","","MerchantID","","","","","a0J28000002aEkBEAU-MerchantID","Sage100PaymentType"
"a0K28000000V5csEAC","DisplayAVSCVVResponse","a0J28000002aEkBEAU","","DisplayAVSCVVResponse","","","","","a0J28000002aEkBEAU-DisplayAVSCVVResponse","Sage100PaymentType"
"a0K28000000V5ctEAC","AllowCorporateCards","a0J28000002aEkBEAU","","AllowCorporateCards","","","","","a0J28000002aEkBEAU-AllowCorporateCards","Sage100PaymentType"
"a0K28000000V5cuEAC","VirtualTerminalID","a0J28000002aEkBEAU","","VirtualTerminalID","","","","","a0J28000002aEkBEAU-VirtualTerminalID","Sage100PaymentType"
"a0K28000000V5cvEAC","MerchantKey","a0J28000002aEkBEAU","","MerchantKey","","","","","a0J28000002aEkBEAU-MerchantKey","Sage100PaymentType"
"a0K28000000V5cwEAC","DiscountPercentage","a0J28000002aEkBEAU","","DiscountPercentage","","","","","a0J28000002aEkBEAU-DiscountPercentage","Sage100PaymentType"
"a0K28000000V5cxEAC","PerTransactionFee","a0J28000002aEkBEAU","","PerTransactionFee","","","","","a0J28000002aEkBEAU-PerTransactionFee","Sage100PaymentType"
"a0K28000000V5cyEAC","PreAuthorizationTerm","a0J28000002aEkBEAU","","PreAuthorizationTerm","","","","","a0J28000002aEkBEAU-PreAuthorizationTerm","Sage100PaymentType"
"a0K28000000V5czEAC","DateCreated","a0J28000002aEkBEAU","","DateCreated","","","","","a0J28000002aEkBEAU-DateCreated","Sage100PaymentType"
"a0K28000000V5d0EAC","TimeCreated","a0J28000002aEkBEAU","","TimeCreated","","","","","a0J28000002aEkBEAU-TimeCreated","Sage100PaymentType"
"a0K28000000V5d1EAC","UserCreatedKey","a0J28000002aEkBEAU","","UserCreatedKey","","","","","a0J28000002aEkBEAU-UserCreatedKey","Sage100PaymentType"
"a0K28000000V5d2EAC","DateUpdated","a0J28000002aEkBEAU","","DateUpdated","","","","","a0J28000002aEkBEAU-DateUpdated","Sage100PaymentType"
"a0K28000000V5d3EAC","TimeUpdated","a0J28000002aEkBEAU","","TimeUpdated","","","","","a0J28000002aEkBEAU-TimeUpdated","Sage100PaymentType"
"a0K28000000V5d4EAC","UserUpdatedKey","a0J28000002aEkBEAU","","UserUpdatedKey","","","","","a0J28000002aEkBEAU-UserUpdatedKey","Sage100PaymentType"
"a0K28000000V5dAEAS","SalespersonDivisionNo","a0J28000002aEHxEAM","","SalespersonDivisionNo","","","","","a0J28000002aEHxEAM-SalespersonDivisionNo","Sage100SalePerson"
"a0K28000000V5dBEAS","SalespersonNo","a0J28000002aEHxEAM","","SalespersonNo","","","","","a0J28000002aEHxEAM-SalespersonNo","Sage100SalePerson"
"a0K28000000V5dCEAS","SalespersonName","a0J28000002aEHxEAM","","SalespersonName","","","","","a0J28000002aEHxEAM-SalespersonName","Sage100SalePerson"
"a0K28000000V5dDEAS","AddressLine1","a0J28000002aEHxEAM","","AddressLine1","","","","","a0J28000002aEHxEAM-AddressLine1","Sage100SalePerson"
"a0K28000000V5dEEAS","AddressLine2","a0J28000002aEHxEAM","","AddressLine2","","","","","a0J28000002aEHxEAM-AddressLine2","Sage100SalePerson"
"a0K28000000V5dFEAS","AddressLine3","a0J28000002aEHxEAM","","AddressLine3","","","","","a0J28000002aEHxEAM-AddressLine3","Sage100SalePerson"
"a0K28000000V5dGEAS","City","a0J28000002aEHxEAM","","City","","","","","a0J28000002aEHxEAM-City","Sage100SalePerson"
"a0K28000000V5dHEAS","State","a0J28000002aEHxEAM","","State","","","","","a0J28000002aEHxEAM-State","Sage100SalePerson"
"a0K28000000V5dIEAS","ZipCode","a0J28000002aEHxEAM","","ZipCode","","","","","a0J28000002aEHxEAM-ZipCode","Sage100SalePerson"
"a0K28000000V5dJEAS","CountryCode","a0J28000002aEHxEAM","","CountryCode","","","","","a0J28000002aEHxEAM-CountryCode","Sage100SalePerson"
"a0K28000000V5dKEAS","TelephoneNo","a0J28000002aEHxEAM","","TelephoneNo","","","","","a0J28000002aEHxEAM-TelephoneNo","Sage100SalePerson"
"a0K28000000V5dLEAS","TelephoneExt","a0J28000002aEHxEAM","","TelephoneExt","","","","","a0J28000002aEHxEAM-TelephoneExt","Sage100SalePerson"
"a0K28000000V5dMEAS","EmailAddress","a0J28000002aEHxEAM","","EmailAddress","","","","","a0J28000002aEHxEAM-EmailAddress","Sage100SalePerson"
"a0K28000000V5dNEAS","SalesManagerDivisionNo","a0J28000002aEHxEAM","","SalesManagerDivisionNo","","","","","a0J28000002aEHxEAM-SalesManagerDivisionNo","Sage100SalePerson"
"a0K28000000V5dOEAS","SalesManagerNo","a0J28000002aEHxEAM","","SalesManagerNo","","","","","a0J28000002aEHxEAM-SalesManagerNo","Sage100SalePerson"
"a0K28000000V5dPEAS","CRMUserID","a0J28000002aEHxEAM","","CRMUserID","","","","","a0J28000002aEHxEAM-CRMUserID","Sage100SalePerson"
"a0K28000000V5dQEAS","UserKey","a0J28000002aEHxEAM","","UserKey","","","","","a0J28000002aEHxEAM-UserKey","Sage100SalePerson"
"a0K28000000V5dREAS","CommissionRate","a0J28000002aEHxEAM","","CommissionRate","","","","","a0J28000002aEHxEAM-CommissionRate","Sage100SalePerson"
"a0K28000000V5dSEAS","SalesManagerCommRate","a0J28000002aEHxEAM","","SalesManagerCommRate","","","","","a0J28000002aEHxEAM-SalesManagerCommRate","Sage100SalePerson"
"a0K28000000V5dTEAS","DateCreated","a0J28000002aEHxEAM","","DateCreated","","","","","a0J28000002aEHxEAM-DateCreated","Sage100SalePerson"
"a0K28000000V5dUEAS","TimeCreated","a0J28000002aEHxEAM","","TimeCreated","","","","","a0J28000002aEHxEAM-TimeCreated","Sage100SalePerson"
"a0K28000000V5dVEAS","UserCreatedKey","a0J28000002aEHxEAM","","UserCreatedKey","","","","","a0J28000002aEHxEAM-UserCreatedKey","Sage100SalePerson"
"a0K28000000V5dWEAS","DateUpdated","a0J28000002aEHxEAM","","DateUpdated","","","","","a0J28000002aEHxEAM-DateUpdated","Sage100SalePerson"
"a0K28000000V5dXEAS","TimeUpdated","a0J28000002aEHxEAM","","TimeUpdated","","","","","a0J28000002aEHxEAM-TimeUpdated","Sage100SalePerson"
"a0K28000000V5dYEAS","UserUpdatedKey","a0J28000002aEHxEAM","","UserUpdatedKey","","","","","a0J28000002aEHxEAM-UserUpdatedKey","Sage100SalePerson"
"a0K28000000V5joEAC","Parameter","a0J28000000UFLlEAO","","AXPARCOD","Char","","","","a0J28000000UFLlEAO-AXPARCOD","SageX3Address"
"a0K28000000V5jpEAC","Parameter value","a0J28000000UFLlEAO","","AXPARVAL","Char","","","","a0J28000000UFLlEAO-AXPARVAL","SageX3Address"
"a0K28000000V5jqEAC","A voir","a0J28000000UFLlEAO","","AXWHRLFTBRK","Integer","","","","a0J28000000UFLlEAO-AXWHRLFTBRK","SageX3Address"
"a0K28000000V5jrEAC","Selection: Field code","a0J28000000UFLlEAO","","AXWHRCOD","Char","","","","a0J28000000UFLlEAO-AXWHRCOD","SageX3Address"
"a0K28000000V5jsEAC","Selection: Operator","a0J28000000UFLlEAO","","AXWHROPE","Integer","","","","a0J28000000UFLlEAO-AXWHROPE","SageX3Address"
"a0K28000000V5jtEAC","Selection: Value","a0J28000000UFLlEAO","","AXWHRCODVAL","Char","","","","a0J28000000UFLlEAO-AXWHRCODVAL","SageX3Address"
"a0K28000000V5juEAC","Avoir","a0J28000000UFLlEAO","","AXWHRRGTBRK","Integer","","","","a0J28000000UFLlEAO-AXWHRRGTBRK","SageX3Address"
"a0K28000000V5jvEAC","Selection: Operator and/or","a0J28000000UFLlEAO","","AXWHRANDOR","Integer","","","","a0J28000000UFLlEAO-AXWHRANDOR","SageX3Address"
"a0K28000000V5jwEAC","Sort: Field code","a0J28000000UFLlEAO","","AXORDCOD","Char","","","","a0J28000000UFLlEAO-AXORDCOD","SageX3Address"
"a0K28000000V5jxEAC","Sort: Order","a0J28000000UFLlEAO","","AXORDTYP","Integer","","","","a0J28000000UFLlEAO-AXORDTYP","SageX3Address"
"a0K28000000V5jyEAC","Address","a0J28000000UFLlEAO","","BPAADD","Char","","","","a0J28000000UFLlEAO-BPAADD","SageX3Address"
"a0K28000000V5jzEAC","By default","a0J28000000UFLlEAO","","BPAADDFLG","Integer","","","","a0J28000000UFLlEAO-BPAADDFLG","SageX3Address"
"a0K28000000V5k0EAC","Address line","a0J28000000UFLlEAO","","BPAADDLIG0","Char","","","","a0J28000000UFLlEAO-BPAADDLIG0","SageX3Address"
"a0K28000000V5k1EAC","Address line","a0J28000000UFLlEAO","","BPAADDLIG1","Char","","","","a0J28000000UFLlEAO-BPAADDLIG1","SageX3Address"
"a0K28000000V5k2EAC","Address line","a0J28000000UFLlEAO","","BPAADDLIG2","Char","","","","a0J28000000UFLlEAO-BPAADDLIG2","SageX3Address"
"a0K28000000V5k3EAC","Entity","a0J28000000UFLlEAO","","BPANUM","Char","","","","a0J28000000UFLlEAO-BPANUM","SageX3Address"
"a0K28000000V5k4EAC","Country","a0J28000000UFLlEAO","","CRY","Char","","","","a0J28000000UFLlEAO-CRY","SageX3Address"
"a0K28000000V5k5EAC","City","a0J28000000UFLlEAO","","CTY","Char","","","","a0J28000000UFLlEAO-CTY","SageX3Address"
"a0K28000000V5k6EAC","County","a0J28000000UFLlEAO","","SAT","Char","","","","a0J28000000UFLlEAO-SAT","SageX3Address"
"a0K28000000V5k7EAC","Telephone","a0J28000000UFLlEAO","","TEL1","Char","","","","a0J28000000UFLlEAO-TEL1","SageX3Address"
"a0K28000000V5k8EAC","Internet address","a0J28000000UFLlEAO","","WEB0","Char","","","","a0J28000000UFLlEAO-WEB0","SageX3Address"
"a0K28000000V5l3EAC","Parameter","a0J28000000V9MxEAK","","AXPARCOD","Char","","","","a0J28000000V9MxEAK-AXPARCOD","SageX3Currency"
"a0K28000000V5l4EAC","Parameter value","a0J28000000V9MxEAK","","AXPARVAL","Char","","","","a0J28000000V9MxEAK-AXPARVAL","SageX3Currency"
"a0K28000000V5l5EAC","A voir","a0J28000000V9MxEAK","","AXWHRLFTBRK","Integer","","","","a0J28000000V9MxEAK-AXWHRLFTBRK","SageX3Currency"
"a0K28000000V5l6EAC","Selection: Field code","a0J28000000V9MxEAK","","AXWHRCOD","Char","","","","a0J28000000V9MxEAK-AXWHRCOD","SageX3Currency"
"a0K28000000V5l7EAC","Selection: Operator","a0J28000000V9MxEAK","","AXWHROPE","Integer","","","","a0J28000000V9MxEAK-AXWHROPE","SageX3Currency"
"a0K28000000V5l8EAC","Selection: Value","a0J28000000V9MxEAK","","AXWHRCODVAL","Char","","","","a0J28000000V9MxEAK-AXWHRCODVAL","SageX3Currency"
"a0K28000000V5l9EAC","Avoir","a0J28000000V9MxEAK","","AXWHRRGTBRK","Integer","","","","a0J28000000V9MxEAK-AXWHRRGTBRK","SageX3Currency"
"a0K28000000V5lAEAS","Selection: Operator and/or","a0J28000000V9MxEAK","","AXWHRANDOR","Integer","","","","a0J28000000V9MxEAK-AXWHRANDOR","SageX3Currency"
"a0K28000000V5lBEAS","Sort: Field code","a0J28000000V9MxEAK","","AXORDCOD","Char","","","","a0J28000000V9MxEAK-AXORDCOD","SageX3Currency"
"a0K28000000V5lCEAS","Sort: Order","a0J28000000V9MxEAK","","AXORDTYP","Integer","","","","a0J28000000V9MxEAK-AXORDTYP","SageX3Currency"
"a0K28000000V5lDEAS","Currency","a0J28000000V9MxEAK","","CUR","Char","","","","a0J28000000V9MxEAK-CUR","SageX3Currency"
"a0K28000000V5lEEAS","Title","a0J28000000V9MxEAK","","INTDES","Char","","","","a0J28000000V9MxEAK-INTDES","SageX3Currency"
"a0K28000000V5qAEAS","Parameter","a0J28000000V9MOEA0","","AXPARCOD","Char","","","","a0J28000000V9MOEA0-AXPARCOD","SageX3Language"
"a0K28000000V5qBEAS","Parameter value","a0J28000000V9MOEA0","","AXPARVAL","Char","","","","a0J28000000V9MOEA0-AXPARVAL","SageX3Language"
"a0K28000000V5qCEAS","A voir","a0J28000000V9MOEA0","","AXWHRLFTBRK","Integer","","","","a0J28000000V9MOEA0-AXWHRLFTBRK","SageX3Language"
"a0K28000000V5qDEAS","Selection: Field code","a0J28000000V9MOEA0","","AXWHRCOD","Char","","","","a0J28000000V9MOEA0-AXWHRCOD","SageX3Language"
"a0K28000000V5qEEAS","Selection: Operator","a0J28000000V9MOEA0","","AXWHROPE","Integer","","","","a0J28000000V9MOEA0-AXWHROPE","SageX3Language"
"a0K28000000V5qFEAS","Selection: Value","a0J28000000V9MOEA0","","AXWHRCODVAL","Char","","","","a0J28000000V9MOEA0-AXWHRCODVAL","SageX3Language"
"a0K28000000V5qGEAS","Avoir","a0J28000000V9MOEA0","","AXWHRRGTBRK","Integer","","","","a0J28000000V9MOEA0-AXWHRRGTBRK","SageX3Language"
"a0K28000000V5qHEAS","Selection: Operator and/or","a0J28000000V9MOEA0","","AXWHRANDOR","Integer","","","","a0J28000000V9MOEA0-AXWHRANDOR","SageX3Language"
"a0K28000000V5qIEAS","Sort: Field code","a0J28000000V9MOEA0","","AXORDCOD","Char","","","","a0J28000000V9MOEA0-AXORDCOD","SageX3Language"
"a0K28000000V5qJEAS","Sort: Order","a0J28000000V9MOEA0","","AXORDTYP","Integer","","","","a0J28000000V9MOEA0-AXORDTYP","SageX3Language"
"a0K28000000V5qKEAS","Title","a0J28000000V9MOEA0","","INTDES","Char","","","","a0J28000000V9MOEA0-INTDES","SageX3Language"
"a0K28000000V5qLEAS","Short title","a0J28000000V9MOEA0","","INTSHO","Char","","","","a0J28000000V9MOEA0-INTSHO","SageX3Language"
"a0K28000000V5qMEAS","Language","a0J28000000V9MOEA0","","LAN","Char","","","","a0J28000000V9MOEA0-LAN","SageX3Language"
"a0K28000000V5siEAC","Sales site","a0J28000000UmSUEA0","","SALFCY","Char","","","","a0J28000000UmSUEA0-SALFCY","SageX3OrderHeader"
"a0K28000000V5sjEAC","Type","a0J28000000UmSUEA0","","SOHTYP","Char","","","","a0J28000000UmSUEA0-SOHTYP","SageX3OrderHeader"
"a0K28000000V5skEAC","Number","a0J28000000UmSUEA0","","SOHNUM","Char","","","","a0J28000000UmSUEA0-SOHNUM","SageX3OrderHeader"
"a0K28000000V5slEAC","Revision","a0J28000000UmSUEA0","","REVNUM","Integer","","","","a0J28000000UmSUEA0-REVNUM","SageX3OrderHeader"
"a0K28000000V5smEAC","Reference","a0J28000000UmSUEA0","","CUSORDREF","Char","","","","a0J28000000UmSUEA0-CUSORDREF","SageX3OrderHeader"
"a0K28000000V5snEAC","Date","a0J28000000UmSUEA0","","ORDDAT","Date","","","","a0J28000000UmSUEA0-ORDDAT","SageX3OrderHeader"
"a0K28000000V5soEAC","Currency","a0J28000000UmSUEA0","","CUR","Char","","","","a0J28000000UmSUEA0-CUR","SageX3OrderHeader"
"a0K28000000V5spEAC","Sold to","a0J28000000UmSUEA0","","BPCORD","Char","","","","a0J28000000UmSUEA0-BPCORD","SageX3OrderHeader"
"a0K28000000V5sqEAC","Tracking #","a0J28000000UmSUEA0","","ZTRACKNUM","Char","","","","a0J28000000UmSUEA0-ZTRACKNUM","SageX3OrderHeader"
"a0K28000000V5srEAC","Bill-to customer","a0J28000000UmSUEA0","","BPCINV","Char","","","","a0J28000000UmSUEA0-BPCINV","SageX3OrderHeader"
"a0K28000000V5ssEAC","Pay by","a0J28000000UmSUEA0","","BPCPYR","Char","","","","a0J28000000UmSUEA0-BPCPYR","SageX3OrderHeader"
"a0K28000000V5stEAC","Group customer","a0J28000000UmSUEA0","","BPCGRU","Char","","","","a0J28000000UmSUEA0-BPCGRU","SageX3OrderHeader"
"a0K28000000V5suEAC","Delivery address","a0J28000000UmSUEA0","","BPAADD","Char","","","","a0J28000000UmSUEA0-BPAADD","SageX3OrderHeader"
"a0K28000000V5svEAC","Memo","a0J28000000UmSUEA0","","MEMO","Char","","","","a0J28000000UmSUEA0-MEMO","SageX3OrderHeader"
"a0K28000000V5swEAC","Project","a0J28000000UmSUEA0","","PJT","Char","","","","a0J28000000UmSUEA0-PJT","SageX3OrderHeader"
"a0K28000000V5sxEAC","Sales rep","a0J28000000UmSUEA0","","REP","Char","","","","a0J28000000UmSUEA0-REP","SageX3OrderHeader"
"a0K28000000V5syEAC","Loan return date","a0J28000000UmSUEA0","","LNDRTNDAT","Date","","","","a0J28000000UmSUEA0-LNDRTNDAT","SageX3OrderHeader"
"a0K28000000V5szEAC","Closing reason","a0J28000000UmSUEA0","","CCLREN","Char","","","","a0J28000000UmSUEA0-CCLREN","SageX3OrderHeader"
"a0K28000000V5t0EAC","Tax rule","a0J28000000UmSUEA0","","VACBPR","Char","","","","a0J28000000UmSUEA0-VACBPR","SageX3OrderHeader"
"a0K28000000V5t1EAC","Entity/Use","a0J28000000UmSUEA0","","SSTENTCOD","Char","","","","a0J28000000UmSUEA0-SSTENTCOD","SageX3OrderHeader"
"a0K28000000V5t2EAC","Price - / +tax","a0J28000000UmSUEA0","","PRITYP","Integer","","1-Exclude tax
2-Include tax","","a0J28000000UmSUEA0-PRITYP","SageX3OrderHeader"
"a0K28000000V5t3EAC","Signed","a0J28000000UmSUEA0","","APPFLG","Integer","","1-No
2-Partly
3-Completely
4-Not Managed
5-Yes Automatic","","a0J28000000UmSUEA0-APPFLG","SageX3OrderHeader"
"a0K28000000V5t4EAC","Order state","a0J28000000UmSUEA0","","ORDSTA","Integer","","1-Open
2-Closed","","a0J28000000UmSUEA0-ORDSTA","SageX3OrderHeader"
"a0K28000000V5t5EAC","Allocation","a0J28000000UmSUEA0","","ALLSTA","Integer","","1-Not Allocated
2-Partially Allocated
3-Allocated","","a0J28000000UmSUEA0-ALLSTA","SageX3OrderHeader"
"a0K28000000V5t6EAC","Delivery","a0J28000000UmSUEA0","","DLVSTA","Integer","","1-Not delivered
2-Partially delivered
3-Delivered","","a0J28000000UmSUEA0-DLVSTA","SageX3OrderHeader"
"a0K28000000V5t7EAC","Invoice","a0J28000000UmSUEA0","","INVSTA","Integer","","1-Not Invoiced
2-Partially Invoiced
3-Invoiced","","a0J28000000UmSUEA0-INVSTA","SageX3OrderHeader"
"a0K28000000V5t8EAC","Credit","a0J28000000UmSUEA0","","CDTSTA","Integer","","1-OK
2-On Hold
3-Limit Exceeded
4-Prepayment not Deposited
5-Sage Exchange","","a0J28000000UmSUEA0-CDTSTA","SageX3OrderHeader"
"a0K28000000V5t9EAC","Hold","a0J28000000UmSUEA0","","HLDSTA","Integer","","1-OK
2-On hold","","a0J28000000UmSUEA0-HLDSTA","SageX3OrderHeader"
"a0K28000000V5tAEAS","Intersites","a0J28000000UmSUEA0","","BETFCY","Integer","","1-No
2-Yes","","a0J28000000UmSUEA0-BETFCY","SageX3OrderHeader"
"a0K28000000V5tBEAS","Intercompany","a0J28000000UmSUEA0","","BETCPY","Integer","","1-No
2-Yes","","a0J28000000UmSUEA0-BETCPY","SageX3OrderHeader"
"a0K28000000V5tCEAS","Shipment site","a0J28000000UmSUEA0","","STOFCY","Char","","","","a0J28000000UmSUEA0-STOFCY","SageX3OrderHeader"
"a0K28000000V5tDEAS","Delivery priority","a0J28000000UmSUEA0","","DLVPIO","Integer","","1-Normal
2-Urgent
3-Critical","","a0J28000000UmSUEA0-DLVPIO","SageX3OrderHeader"
"a0K28000000V5tEEAS","Req. delivery date","a0J28000000UmSUEA0","","DEMDLVDAT","Date","","","","a0J28000000UmSUEA0-DEMDLVDAT","SageX3OrderHeader"
"a0K28000000V5tFEAS","Delivery LT in days","a0J28000000UmSUEA0","","DAYLTI","Integer","","","","a0J28000000UmSUEA0-DAYLTI","SageX3OrderHeader"
"a0K28000000V5tGEAS","Shipment date","a0J28000000UmSUEA0","","SHIDAT","Date","","","","a0J28000000UmSUEA0-SHIDAT","SageX3OrderHeader"
"a0K28000000V5tHEAS","Route no.","a0J28000000UmSUEA0","","DRN","Integer","","1-Route Code 1
2-Route Code 2
3-Route Code 3","","a0J28000000UmSUEA0-DRN","SageX3OrderHeader"
"a0K28000000V5tIEAS","Delivery mode","a0J28000000UmSUEA0","","MDL","Char","","","","a0J28000000UmSUEA0-MDL","SageX3OrderHeader"
"a0K28000000V5tJEAS","Carrier","a0J28000000UmSUEA0","","BPTNUM","Char","","","","a0J28000000UmSUEA0-BPTNUM","SageX3OrderHeader"
"a0K28000000V5tKEAS","Incoterm","a0J28000000UmSUEA0","","EECICT","Char","","","","a0J28000000UmSUEA0-EECICT","SageX3OrderHeader"
"a0K28000000V5tLEAS","Incoterm town","a0J28000000UmSUEA0","","ICTCTY","Char","","","","a0J28000000UmSUEA0-ICTCTY","SageX3OrderHeader"
"a0K28000000V5tMEAS","Last delivery no.","a0J28000000UmSUEA0","","LASDLVNUM","Char","","","","a0J28000000UmSUEA0-LASDLVNUM","SageX3OrderHeader"
"a0K28000000V5tNEAS","Acknowledgment printed","a0J28000000UmSUEA0","","OCNPRN","Integer","","1-No
2-Yes","","a0J28000000UmSUEA0-OCNPRN","SageX3OrderHeader"
"a0K28000000V5tOEAS","Last delivery date","a0J28000000UmSUEA0","","LASDLVDAT","Date","","","","a0J28000000UmSUEA0-LASDLVDAT","SageX3OrderHeader"
"a0K28000000V5tPEAS","Delivery type","a0J28000000UmSUEA0","","SDHTYP","Char","","","","a0J28000000UmSUEA0-SDHTYP","SageX3OrderHeader"
"a0K28000000V5tQEAS","Close unfilled lines","a0J28000000UmSUEA0","","ORDCLE","Integer","","1-No
2-Yes","","a0J28000000UmSUEA0-ORDCLE","SageX3OrderHeader"
"a0K28000000V5tREAS","One order per deliv","a0J28000000UmSUEA0","","ODL","Integer","","1-No
2-Yes","","a0J28000000UmSUEA0-ODL","SageX3OrderHeader"
"a0K28000000V5tSEAS","Partial delivery","a0J28000000UmSUEA0","","DME","Integer","","1-Allowed
2-Ship line complete
3-Ship order complete","","a0J28000000UmSUEA0-DME","SageX3OrderHeader"
"a0K28000000V5tTEAS","Allocation type","a0J28000000UmSUEA0","","ALLTYP","Integer","","1-Global
2-Detailed","","a0J28000000UmSUEA0-ALLTYP","SageX3OrderHeader"
"a0K28000000V5tUEAS","Invoicing mode","a0J28000000UmSUEA0","","IME","Integer","","1-One/Shipment
2-One/Closed order
3-One/Order
4-One/Ship to
5-One/Period
6-Manual","","a0J28000000UmSUEA0-IME","SageX3OrderHeader"
"a0K28000000V5tVEAS","Settlement discount","a0J28000000UmSUEA0","","DEP","Char","","","","a0J28000000UmSUEA0-DEP","SageX3OrderHeader"
"a0K28000000V5tWEAS","Quote no.","a0J28000000UmSUEA0","","SQHNUM","Char","","","","a0J28000000UmSUEA0-SQHNUM","SageX3OrderHeader"
"a0K28000000V5tXEAS","Proforma no.","a0J28000000UmSUEA0","","PRFNUM","Char","","","","a0J28000000UmSUEA0-PRFNUM","SageX3OrderHeader"
"a0K28000000V5tYEAS","Last invoice no.","a0J28000000UmSUEA0","","LASINVNUM","Char","","","","a0J28000000UmSUEA0-LASINVNUM","SageX3OrderHeader"
"a0K28000000V5tZEAS","Last invoice date","a0J28000000UmSUEA0","","LASINVDAT","Date","","","","a0J28000000UmSUEA0-LASINVDAT","SageX3OrderHeader"
"a0K28000000V5taEAC","Dimension type","a0J28000000UmSUEA0","","DIE","Char","","","","a0J28000000UmSUEA0-DIE","SageX3OrderHeader"
"a0K28000000V5tbEAC","Description","a0J28000000UmSUEA0","","NAMDIE","Char","","","","a0J28000000UmSUEA0-NAMDIE","SageX3OrderHeader"
"a0K28000000V5tcEAC","Analytical dimension","a0J28000000UmSUEA0","","CCE","Char","","","","a0J28000000UmSUEA0-CCE","SageX3OrderHeader"
"a0K28000000V5tdEAC","Short description","a0J28000000UmSUEA0","","SHO","Char","","","","a0J28000000UmSUEA0-SHO","SageX3OrderHeader"
"a0K28000000V5teEAC","% or amount","a0J28000000UmSUEA0","","INVDTAAMT","Decimal","","","","a0J28000000UmSUEA0-INVDTAAMT","SageX3OrderHeader"
"a0K28000000V5tfEAC","Ex tax to deliver","a0J28000000UmSUEA0","","DLRNOT","Decimal","","","","a0J28000000UmSUEA0-DLRNOT","SageX3OrderHeader"
"a0K28000000V5tgEAC","Margin","a0J28000000UmSUEA0","","PFMTOT","Decimal","","","","a0J28000000UmSUEA0-PFMTOT","SageX3OrderHeader"
"a0K28000000V5thEAC","Excl tax lines","a0J28000000UmSUEA0","","ORDNOT","Decimal","","","","a0J28000000UmSUEA0-ORDNOT","SageX3OrderHeader"
"a0K28000000V5tiEAC","Payment terms","a0J28000000UmSUEA0","","PTE","Char","","","","a0J28000000UmSUEA0-PTE","SageX3OrderHeader"
"a0K28000000V5tjEAC","- tax","a0J28000000UmSUEA0","","ORDINVNOT","Decimal","","","","a0J28000000UmSUEA0-ORDINVNOT","SageX3OrderHeader"
"a0K28000000V5tkEAC","Tax included","a0J28000000UmSUEA0","","ORDINVATI","Decimal","","","","a0J28000000UmSUEA0-ORDINVATI","SageX3OrderHeader"
"a0K28000000V5tlEAC","No.","a0J28000000UmSUEA0","","NUMLIG","Integer","","","","a0J28000000UmSUEA0-NUMLIG","SageX3OrderHeader"
"a0K28000000V5tmEAC","Product","a0J28000000UmSUEA0","","ITMREF","Char","","","","a0J28000000UmSUEA0-ITMREF","SageX3OrderHeader"
"a0K28000000V5tnEAC","Description","a0J28000000UmSUEA0","","ITMDES","Char","","","","a0J28000000UmSUEA0-ITMDES","SageX3OrderHeader"
"a0K28000000V5toEAC","Std description","a0J28000000UmSUEA0","","ITMDES1","Char","","","","a0J28000000UmSUEA0-ITMDES1","SageX3OrderHeader"
"a0K28000000V5tpEAC","Ship site","a0J28000000UmSUEA0","","DSTOFCY","Char","","","","a0J28000000UmSUEA0-DSTOFCY","SageX3OrderHeader"
"a0K28000000V5tqEAC","SAL","a0J28000000UmSUEA0","","SAU","Char","","","","a0J28000000UmSUEA0-SAU","SageX3OrderHeader"
"a0K28000000V5trEAC","Ordered qty","a0J28000000UmSUEA0","","QTY","Decimal","","","","a0J28000000UmSUEA0-QTY","SageX3OrderHeader"
"a0K28000000V5tsEAC","SAL-STK conv","a0J28000000UmSUEA0","","SAUSTUCOE","Decimal","","","","a0J28000000UmSUEA0-SAUSTUCOE","SageX3OrderHeader"
"a0K28000000V5ttEAC","Qty allocated","a0J28000000UmSUEA0","","ALLQTY","Decimal","","","","a0J28000000UmSUEA0-ALLQTY","SageX3OrderHeader"
"a0K28000000V5tuEAC","Shortage","a0J28000000UmSUEA0","","SHTQTY","Decimal","","","","a0J28000000UmSUEA0-SHTQTY","SageX3OrderHeader"
"a0K28000000V5tvEAC","Qty to allocate","a0J28000000UmSUEA0","","WALLQTY","Decimal","","","","a0J28000000UmSUEA0-WALLQTY","SageX3OrderHeader"
"a0K28000000V5twEAC","Allocation type","a0J28000000UmSUEA0","","DALLTYP","Integer","","1-Global
2-Detailed","","a0J28000000UmSUEA0-DALLTYP","SageX3OrderHeader"
"a0K28000000V5txEAC","Qty to deliver","a0J28000000UmSUEA0","","TDLQTY","Decimal","","","","a0J28000000UmSUEA0-TDLQTY","SageX3OrderHeader"
"a0K28000000V5tyEAC","Margin","a0J28000000UmSUEA0","","PFM","Decimal","","","","a0J28000000UmSUEA0-PFM","SageX3OrderHeader"
"a0K28000000V5tzEAC","Gross price","a0J28000000UmSUEA0","","GROPRI","Decimal","","","","a0J28000000UmSUEA0-GROPRI","SageX3OrderHeader"
"a0K28000000V5u0EAC","Net price","a0J28000000UmSUEA0","","NETPRI","Decimal","","","","a0J28000000UmSUEA0-NETPRI","SageX3OrderHeader"
"a0K28000000V5u1EAC","Cost price","a0J28000000UmSUEA0","","CPRPRI","Decimal","","","","a0J28000000UmSUEA0-CPRPRI","SageX3OrderHeader"
"a0K28000000V5u2EAC","Tax level 1","a0J28000000UmSUEA0","","VACITM1","Char","","","","a0J28000000UmSUEA0-VACITM1","SageX3OrderHeader"
"a0K28000000V5u3EAC","Tax level 2","a0J28000000UmSUEA0","","VACITM2","Char","","","","a0J28000000UmSUEA0-VACITM2","SageX3OrderHeader"
"a0K28000000V5u4EAC","Tax level 3","a0J28000000UmSUEA0","","VACITM3","Char","","","","a0J28000000UmSUEA0-VACITM3","SageX3OrderHeader"
"a0K28000000V5u5EAC","STK","a0J28000000UmSUEA0","","STU","Char","","","","a0J28000000UmSUEA0-STU","SageX3OrderHeader"
"a0K28000000V5u6EAC","Sales rep 1","a0J28000000UmSUEA0","","REP1","Char","","","","a0J28000000UmSUEA0-REP1","SageX3OrderHeader"
"a0K28000000V5u7EAC","Commission rate 1","a0J28000000UmSUEA0","","REPRAT1","Decimal","","","","a0J28000000UmSUEA0-REPRAT1","SageX3OrderHeader"
"a0K28000000V5u8EAC","Sales rep 2","a0J28000000UmSUEA0","","REP2","Char","","","","a0J28000000UmSUEA0-REP2","SageX3OrderHeader"
"a0K28000000V5u9EAC","Commission rate 2","a0J28000000UmSUEA0","","REPRAT2","Decimal","","","","a0J28000000UmSUEA0-REPRAT2","SageX3OrderHeader"
"a0K28000000V5uAEAS","Comm. factor","a0J28000000UmSUEA0","","REPCOE","Decimal","","","","a0J28000000UmSUEA0-REPCOE","SageX3OrderHeader"
"a0K28000000V5uBEAS","Last del date","a0J28000000UmSUEA0","","DDEMDLVDAT","Date","","","","a0J28000000UmSUEA0-DDEMDLVDAT","SageX3OrderHeader"
"a0K28000000V5uCEAS","Lead time","a0J28000000UmSUEA0","","DDAYLTI","Integer","","","","a0J28000000UmSUEA0-DDAYLTI","SageX3OrderHeader"
"a0K28000000V5uDEAS","Ship date","a0J28000000UmSUEA0","","DSHIDAT","Date","","","","a0J28000000UmSUEA0-DSHIDAT","SageX3OrderHeader"
"a0K28000000V5uEEAS","Exp delivery date","a0J28000000UmSUEA0","","EXTDLVDAT","Date","","","","a0J28000000UmSUEA0-EXTDLVDAT","SageX3OrderHeader"
"a0K28000000V5uFEAS","Addr","a0J28000000UmSUEA0","","DBPAADD","Char","","","","a0J28000000UmSUEA0-DBPAADD","SageX3OrderHeader"
"a0K28000000V5uGEAS","Delivery contact","a0J28000000UmSUEA0","","CNDNAM","Char","","","","a0J28000000UmSUEA0-CNDNAM","SageX3OrderHeader"
"a0K28000000V5uHEAS","Location reference","a0J28000000UmSUEA0","","USEPLC","Char","","","","a0J28000000UmSUEA0-USEPLC","SageX3OrderHeader"
"a0K28000000V5uIEAS","Deliv priority","a0J28000000UmSUEA0","","DDLVPIO","Integer","","1-Normal
2-Urgent
3-Critical","","a0J28000000UmSUEA0-DDLVPIO","SageX3OrderHeader"
"a0K28000000V5uJEAS","Route no.","a0J28000000UmSUEA0","","DDRN","Integer","","1-Route Code 1
2-Route Code 2
3-Route Code 3","","a0J28000000UmSUEA0-DDRN","SageX3OrderHeader"
"a0K28000000V5uKEAS","Deliv mode","a0J28000000UmSUEA0","","DMDL","Char","","","","a0J28000000UmSUEA0-DMDL","SageX3OrderHeader"
"a0K28000000V5uLEAS","Carrier","a0J28000000UmSUEA0","","DBPTNUM","Char","","","","a0J28000000UmSUEA0-DBPTNUM","SageX3OrderHeader"
"a0K28000000V5uMEAS","Preparation code","a0J28000000UmSUEA0","","PRECOD","Char","","","","a0J28000000UmSUEA0-PRECOD","SageX3OrderHeader"
"a0K28000000V5uNEAS","Package","a0J28000000UmSUEA0","","PCK","Char","","","","a0J28000000UmSUEA0-PCK","SageX3OrderHeader"
"a0K28000000V5uOEAS","Packing capacity","a0J28000000UmSUEA0","","PCKCAP","Decimal","","","","a0J28000000UmSUEA0-PCKCAP","SageX3OrderHeader"
"a0K28000000V5uPEAS","Order status","a0J28000000UmSUEA0","","DEMSTA","Integer","","1-Firm
2-Planned
3-Suggested
4-Closed","","a0J28000000UmSUEA0-DEMSTA","SageX3OrderHeader"
"a0K28000000V5uQEAS","Source for delivery","a0J28000000UmSUEA0","","FMI","Integer","","1-Stock
2-PO - Direct to Customer
3-PO - Recv and Ship
4-Transfer
5-Work Order","","a0J28000000UmSUEA0-FMI","SageX3OrderHeader"
"a0K28000000V5uREAS","Back-to-back order no.","a0J28000000UmSUEA0","","FMINUM","Char","","","","a0J28000000UmSUEA0-FMINUM","SageX3OrderHeader"
"a0K28000000V5uSEAS","Line amt -tax","a0J28000000UmSUEA0","","LINORDNOT","Decimal","","","","a0J28000000UmSUEA0-LINORDNOT","SageX3OrderHeader"
"a0K28000000V5uTEAS","Line amt +tax","a0J28000000UmSUEA0","","LINORDATI","Decimal","","","","a0J28000000UmSUEA0-LINORDATI","SageX3OrderHeader"
"a0K28000000V5uUEAS","Quote no.","a0J28000000UmSUEA0","","DETSQHNUM","Char","","","","a0J28000000UmSUEA0-DETSQHNUM","SageX3OrderHeader"
"a0K28000000V5uVEAS","Line type","a0J28000000UmSUEA0","","LINTYP","Integer","","1-Normal
2-Fixed kit
3-Kit Component
4-Kit Option
5-Kit Variant
6-Flex kit
7-BOM component
8-BOM Option
9-BOM Variant
10-Subcontracted
11-Service
12-Supplied material
13-Fixed-amount service","","a0J28000000UmSUEA0-LINTYP","SageX3OrderHeader"
"a0K28000000V5uWEAS","Free","a0J28000000UmSUEA0","","FOCFLG","Integer","","1-No
2-Source
3-Yes","","a0J28000000UmSUEA0-FOCFLG","SageX3OrderHeader"
"a0K28000000V5uXEAS","Closed","a0J28000000UmSUEA0","","SOQSTA","Integer","","1-Pending
2-Late
3-Closed","","a0J28000000UmSUEA0-SOQSTA","SageX3OrderHeader"
"a0K28000000V5uYEAS","Closing reason","a0J28000000UmSUEA0","","DCCLREN","Char","","","","a0J28000000UmSUEA0-DCCLREN","SageX3OrderHeader"
"a0K28000000V5uZEAS","Date closed","a0J28000000UmSUEA0","","DCCLDAT","Date","","","","a0J28000000UmSUEA0-DCCLDAT","SageX3OrderHeader"
"a0K28000000V5uaEAC","Company name","a0J28000000UmSUEA0","","BPRNAM","Char","","","","a0J28000000UmSUEA0-BPRNAM","SageX3OrderHeader"
"a0K28000000V5ubEAC","Country","a0J28000000UmSUEA0","","CRY","Char","","","","a0J28000000UmSUEA0-CRY","SageX3OrderHeader"
"a0K28000000V5ucEAC","Postal code","a0J28000000UmSUEA0","","POSCOD","Char","","","","a0J28000000UmSUEA0-POSCOD","SageX3OrderHeader"
"a0K28000000V5udEAC","City","a0J28000000UmSUEA0","","CTY","Char","","","","a0J28000000UmSUEA0-CTY","SageX3OrderHeader"
"a0K28000000V5ueEAC","Person to contact","a0J28000000UmSUEA0","","CNTNAM","Char","","","","a0J28000000UmSUEA0-CNTNAM","SageX3OrderHeader"
"a0K28000000V5ufEAC","EU VAT no.","a0J28000000UmSUEA0","","EECNUMX","Char","","","","a0J28000000UmSUEA0-EECNUMX","SageX3OrderHeader"
"a0K28000000V5ugEAC","Line margin","a0J28000000UmSUEA0","","LINPFM","Decimal","","","","a0J28000000UmSUEA0-LINPFM","SageX3OrderHeader"
"a0K28000000V5uhEAC","Address validation","a0J28000000UmSUEA0","","VALADR","Char","","","","a0J28000000UmSUEA0-VALADR","SageX3OrderHeader"
"a0K28000000V5uiEAC","Validated","a0J28000000UmSUEA0","","ADRVAL","Integer","","1-No
2-Yes","","a0J28000000UmSUEA0-ADRVAL","SageX3OrderHeader"
"a0K28000000V5wkEAC","Sales site","a0J28000000UuCREA0","","SALFCY","Char","","","","a0J28000000UuCREA0-SALFCY","SageX3OrderLine"
"a0K28000000V5wlEAC","Type","a0J28000000UuCREA0","","SOHTYP","Char","","","","a0J28000000UuCREA0-SOHTYP","SageX3OrderLine"
"a0K28000000V5wmEAC","Number","a0J28000000UuCREA0","","SOHNUM","Char","","","","a0J28000000UuCREA0-SOHNUM","SageX3OrderLine"
"a0K28000000V5wnEAC","Revision","a0J28000000UuCREA0","","REVNUM","Integer","","","","a0J28000000UuCREA0-REVNUM","SageX3OrderLine"
"a0K28000000V5woEAC","Reference","a0J28000000UuCREA0","","CUSORDREF","Char","","","","a0J28000000UuCREA0-CUSORDREF","SageX3OrderLine"
"a0K28000000V5wpEAC","Date","a0J28000000UuCREA0","","ORDDAT","Date","","","","a0J28000000UuCREA0-ORDDAT","SageX3OrderLine"
"a0K28000000V5wqEAC","Currency","a0J28000000UuCREA0","","CUR","Char","","","","a0J28000000UuCREA0-CUR","SageX3OrderLine"
"a0K28000000V5wrEAC","Sold to","a0J28000000UuCREA0","","BPCORD","Char","","","","a0J28000000UuCREA0-BPCORD","SageX3OrderLine"
"a0K28000000V5wsEAC","Tracking #","a0J28000000UuCREA0","","ZTRACKNUM","Char","","","","a0J28000000UuCREA0-ZTRACKNUM","SageX3OrderLine"
"a0K28000000V5wtEAC","Bill-to customer","a0J28000000UuCREA0","","BPCINV","Char","","","","a0J28000000UuCREA0-BPCINV","SageX3OrderLine"
"a0K28000000V5wuEAC","Pay by","a0J28000000UuCREA0","","BPCPYR","Char","","","","a0J28000000UuCREA0-BPCPYR","SageX3OrderLine"
"a0K28000000V5wvEAC","Group customer","a0J28000000UuCREA0","","BPCGRU","Char","","","","a0J28000000UuCREA0-BPCGRU","SageX3OrderLine"
"a0K28000000V5wwEAC","Delivery address","a0J28000000UuCREA0","","BPAADD","Char","","","","a0J28000000UuCREA0-BPAADD","SageX3OrderLine"
"a0K28000000V5wxEAC","Memo","a0J28000000UuCREA0","","MEMO","Char","","","","a0J28000000UuCREA0-MEMO","SageX3OrderLine"
"a0K28000000V5wyEAC","Project","a0J28000000UuCREA0","","PJT","Char","","","","a0J28000000UuCREA0-PJT","SageX3OrderLine"
"a0K28000000V5wzEAC","Sales rep","a0J28000000UuCREA0","","REP","Char","","","","a0J28000000UuCREA0-REP","SageX3OrderLine"
"a0K28000000V5x0EAC","Loan return date","a0J28000000UuCREA0","","LNDRTNDAT","Date","","","","a0J28000000UuCREA0-LNDRTNDAT","SageX3OrderLine"
"a0K28000000V5x1EAC","Closing reason","a0J28000000UuCREA0","","CCLREN","Char","","","","a0J28000000UuCREA0-CCLREN","SageX3OrderLine"
"a0K28000000V5x2EAC","Tax rule","a0J28000000UuCREA0","","VACBPR","Char","","","","a0J28000000UuCREA0-VACBPR","SageX3OrderLine"
"a0K28000000V5x3EAC","Entity/Use","a0J28000000UuCREA0","","SSTENTCOD","Char","","","","a0J28000000UuCREA0-SSTENTCOD","SageX3OrderLine"
"a0K28000000V5x4EAC","Price - / +tax","a0J28000000UuCREA0","","PRITYP","Integer","","1-Exclude tax
2-Include tax","","a0J28000000UuCREA0-PRITYP","SageX3OrderLine"
"a0K28000000V5x5EAC","Signed","a0J28000000UuCREA0","","APPFLG","Integer","","1-No
2-Partly
3-Completely
4-Not Managed
5-Yes Automatic","","a0J28000000UuCREA0-APPFLG","SageX3OrderLine"
"a0K28000000V5x6EAC","Order state","a0J28000000UuCREA0","","ORDSTA","Integer","","1-Open
2-Closed","","a0J28000000UuCREA0-ORDSTA","SageX3OrderLine"
"a0K28000000V5x7EAC","Allocation","a0J28000000UuCREA0","","ALLSTA","Integer","","1-Not Allocated
2-Partially Allocated
3-Allocated","","a0J28000000UuCREA0-ALLSTA","SageX3OrderLine"
"a0K28000000V5x8EAC","Delivery","a0J28000000UuCREA0","","DLVSTA","Integer","","1-Not delivered
2-Partially delivered
3-Delivered","","a0J28000000UuCREA0-DLVSTA","SageX3OrderLine"
"a0K28000000V5x9EAC","Invoice","a0J28000000UuCREA0","","INVSTA","Integer","","1-Not Invoiced
2-Partially Invoiced
3-Invoiced","","a0J28000000UuCREA0-INVSTA","SageX3OrderLine"
"a0K28000000V5xAEAS","Credit","a0J28000000UuCREA0","","CDTSTA","Integer","","1-OK
2-On Hold
3-Limit Exceeded
4-Prepayment not Deposited
5-Sage Exchange","","a0J28000000UuCREA0-CDTSTA","SageX3OrderLine"
"a0K28000000V5xBEAS","Hold","a0J28000000UuCREA0","","HLDSTA","Integer","","1-OK
2-On hold","","a0J28000000UuCREA0-HLDSTA","SageX3OrderLine"
"a0K28000000V5xCEAS","Acknowledgment printed","a0J28000000UuCREA0","","OCNPRN","Integer","","1-No
2-Yes","","a0J28000000UuCREA0-OCNPRN","SageX3OrderLine"
"a0K28000000V5xDEAS","Intersites","a0J28000000UuCREA0","","BETFCY","Integer","","1-No
2-Yes","","a0J28000000UuCREA0-BETFCY","SageX3OrderLine"
"a0K28000000V5xEEAS","Intercompany","a0J28000000UuCREA0","","BETCPY","Integer","","1-No
2-Yes","","a0J28000000UuCREA0-BETCPY","SageX3OrderLine"
"a0K28000000V5xFEAS","Shipment site","a0J28000000UuCREA0","","STOFCY","Char","","","","a0J28000000UuCREA0-STOFCY","SageX3OrderLine"
"a0K28000000V5xGEAS","Delivery priority","a0J28000000UuCREA0","","DLVPIO","Integer","","1-Normal
2-Urgent
3-Critical","","a0J28000000UuCREA0-DLVPIO","SageX3OrderLine"
"a0K28000000V5xHEAS","Req. delivery date","a0J28000000UuCREA0","","DEMDLVDAT","Date","","","","a0J28000000UuCREA0-DEMDLVDAT","SageX3OrderLine"
"a0K28000000V5xIEAS","Delivery LT in days","a0J28000000UuCREA0","","DAYLTI","Integer","","","","a0J28000000UuCREA0-DAYLTI","SageX3OrderLine"
"a0K28000000V5xJEAS","Shipment date","a0J28000000UuCREA0","","SHIDAT","Date","","","","a0J28000000UuCREA0-SHIDAT","SageX3OrderLine"
"a0K28000000V5xKEAS","Route no.","a0J28000000UuCREA0","","DRN","Integer","","1-Route Code 1
2-Route Code 2
3-Route Code 3","","a0J28000000UuCREA0-DRN","SageX3OrderLine"
"a0K28000000V5xLEAS","Delivery mode","a0J28000000UuCREA0","","MDL","Char","","","","a0J28000000UuCREA0-MDL","SageX3OrderLine"
"a0K28000000V5xMEAS","Carrier","a0J28000000UuCREA0","","BPTNUM","Char","","","","a0J28000000UuCREA0-BPTNUM","SageX3OrderLine"
"a0K28000000V5xNEAS","Incoterm","a0J28000000UuCREA0","","EECICT","Char","","","","a0J28000000UuCREA0-EECICT","SageX3OrderLine"
"a0K28000000V5xOEAS","Incoterm town","a0J28000000UuCREA0","","ICTCTY","Char","","","","a0J28000000UuCREA0-ICTCTY","SageX3OrderLine"
"a0K28000000V5xPEAS","Last delivery no.","a0J28000000UuCREA0","","LASDLVNUM","Char","","","","a0J28000000UuCREA0-LASDLVNUM","SageX3OrderLine"
"a0K28000000V5xQEAS","Last delivery date","a0J28000000UuCREA0","","LASDLVDAT","Date","","","","a0J28000000UuCREA0-LASDLVDAT","SageX3OrderLine"
"a0K28000000V5xREAS","Delivery type","a0J28000000UuCREA0","","SDHTYP","Char","","","","a0J28000000UuCREA0-SDHTYP","SageX3OrderLine"
"a0K28000000V5xSEAS","Close unfilled lines","a0J28000000UuCREA0","","ORDCLE","Integer","","1-No
2-Yes","","a0J28000000UuCREA0-ORDCLE","SageX3OrderLine"
"a0K28000000V5xTEAS","One order per deliv","a0J28000000UuCREA0","","ODL","Integer","","1-No
2-Yes","","a0J28000000UuCREA0-ODL","SageX3OrderLine"
"a0K28000000V5xUEAS","Partial delivery","a0J28000000UuCREA0","","DME","Integer","","1-Allowed
2-Ship line complete
3-Ship order complete","","a0J28000000UuCREA0-DME","SageX3OrderLine"
"a0K28000000V5xVEAS","Allocation type","a0J28000000UuCREA0","","ALLTYP","Integer","","1-Global
2-Detailed","","a0J28000000UuCREA0-ALLTYP","SageX3OrderLine"
"a0K28000000V5xWEAS","Invoicing mode","a0J28000000UuCREA0","","IME","Integer","","1-One/Shipment
2-One/Closed order
3-One/Order
4-One/Ship to
5-One/Period
6-Manual","","a0J28000000UuCREA0-IME","SageX3OrderLine"
"a0K28000000V5xXEAS","Payment terms","a0J28000000UuCREA0","","PTE","Char","","","","a0J28000000UuCREA0-PTE","SageX3OrderLine"
"a0K28000000V5xYEAS","Settlement discount","a0J28000000UuCREA0","","DEP","Char","","","","a0J28000000UuCREA0-DEP","SageX3OrderLine"
"a0K28000000V5xZEAS","Quote no.","a0J28000000UuCREA0","","SQHNUM","Char","","","","a0J28000000UuCREA0-SQHNUM","SageX3OrderLine"
"a0K28000000V5xaEAC","Proforma no.","a0J28000000UuCREA0","","PRFNUM","Char","","","","a0J28000000UuCREA0-PRFNUM","SageX3OrderLine"
"a0K28000000V5xbEAC","Last invoice no.","a0J28000000UuCREA0","","LASINVNUM","Char","","","","a0J28000000UuCREA0-LASINVNUM","SageX3OrderLine"
"a0K28000000V5xcEAC","Last invoice date","a0J28000000UuCREA0","","LASINVDAT","Date","","","","a0J28000000UuCREA0-LASINVDAT","SageX3OrderLine"
"a0K28000000V5xdEAC","Dimension type","a0J28000000UuCREA0","","DIE","Char","","","","a0J28000000UuCREA0-DIE","SageX3OrderLine"
"a0K28000000V5xeEAC","Description","a0J28000000UuCREA0","","NAMDIE","Char","","","","a0J28000000UuCREA0-NAMDIE","SageX3OrderLine"
"a0K28000000V5xfEAC","Analytical dimension","a0J28000000UuCREA0","","CCE","Char","","","","a0J28000000UuCREA0-CCE","SageX3OrderLine"
"a0K28000000V5xgEAC","Short description","a0J28000000UuCREA0","","SHO","Char","","","","a0J28000000UuCREA0-SHO","SageX3OrderLine"
"a0K28000000V5xhEAC","% or amount","a0J28000000UuCREA0","","INVDTAAMT","Decimal","","","","a0J28000000UuCREA0-INVDTAAMT","SageX3OrderLine"
"a0K28000000V5xiEAC","Ex tax to deliver","a0J28000000UuCREA0","","DLRNOT","Decimal","","","","a0J28000000UuCREA0-DLRNOT","SageX3OrderLine"
"a0K28000000V5xjEAC","Margin","a0J28000000UuCREA0","","PFMTOT","Decimal","","","","a0J28000000UuCREA0-PFMTOT","SageX3OrderLine"
"a0K28000000V5xkEAC","Excl tax lines","a0J28000000UuCREA0","","ORDNOT","Decimal","","","","a0J28000000UuCREA0-ORDNOT","SageX3OrderLine"
"a0K28000000V5xlEAC","- tax","a0J28000000UuCREA0","","ORDINVNOT","Decimal","","","","a0J28000000UuCREA0-ORDINVNOT","SageX3OrderLine"
"a0K28000000V5xmEAC","Tax included","a0J28000000UuCREA0","","ORDINVATI","Decimal","","","","a0J28000000UuCREA0-ORDINVATI","SageX3OrderLine"
"a0K28000000V5xnEAC","No.","a0J28000000UuCREA0","","NUMLIG","Integer","","","","a0J28000000UuCREA0-NUMLIG","SageX3OrderLine"
"a0K28000000V5xoEAC","Product","a0J28000000UuCREA0","","ITMREF","Char","","","","a0J28000000UuCREA0-ITMREF","SageX3OrderLine"
"a0K28000000V5xpEAC","Description","a0J28000000UuCREA0","","ITMDES","Char","","","","a0J28000000UuCREA0-ITMDES","SageX3OrderLine"
"a0K28000000V5xqEAC","Std description","a0J28000000UuCREA0","","ITMDES1","Char","","","","a0J28000000UuCREA0-ITMDES1","SageX3OrderLine"
"a0K28000000V5xrEAC","Ship site","a0J28000000UuCREA0","","DSTOFCY","Char","","","","a0J28000000UuCREA0-DSTOFCY","SageX3OrderLine"
"a0K28000000V5xsEAC","SAL","a0J28000000UuCREA0","","SAU","Char","","","","a0J28000000UuCREA0-SAU","SageX3OrderLine"
"a0K28000000V5xtEAC","Ordered qty","a0J28000000UuCREA0","","QTY","Decimal","","","","a0J28000000UuCREA0-QTY","SageX3OrderLine"
"a0K28000000V5xuEAC","SAL-STK conv","a0J28000000UuCREA0","","SAUSTUCOE","Decimal","","","","a0J28000000UuCREA0-SAUSTUCOE","SageX3OrderLine"
"a0K28000000V5xvEAC","STK","a0J28000000UuCREA0","","STU","Char","","","","a0J28000000UuCREA0-STU","SageX3OrderLine"
"a0K28000000V5xwEAC","Qty allocated","a0J28000000UuCREA0","","ALLQTY","Decimal","","","","a0J28000000UuCREA0-ALLQTY","SageX3OrderLine"
"a0K28000000V5xxEAC","Shortage","a0J28000000UuCREA0","","SHTQTY","Decimal","","","","a0J28000000UuCREA0-SHTQTY","SageX3OrderLine"
"a0K28000000V5xyEAC","Qty to allocate","a0J28000000UuCREA0","","WALLQTY","Decimal","","","","a0J28000000UuCREA0-WALLQTY","SageX3OrderLine"
"a0K28000000V5xzEAC","Allocation type","a0J28000000UuCREA0","","DALLTYP","Integer","","1-Global
2-Detailed","","a0J28000000UuCREA0-DALLTYP","SageX3OrderLine"
"a0K28000000V5y0EAC","Qty to deliver","a0J28000000UuCREA0","","TDLQTY","Decimal","","","","a0J28000000UuCREA0-TDLQTY","SageX3OrderLine"
"a0K28000000V5y1EAC","Gross price","a0J28000000UuCREA0","","GROPRI","Decimal","","","","a0J28000000UuCREA0-GROPRI","SageX3OrderLine"
"a0K28000000V5y2EAC","Net price","a0J28000000UuCREA0","","NETPRI","Decimal","","","","a0J28000000UuCREA0-NETPRI","SageX3OrderLine"
"a0K28000000V5y3EAC","Cost price","a0J28000000UuCREA0","","CPRPRI","Decimal","","","","a0J28000000UuCREA0-CPRPRI","SageX3OrderLine"
"a0K28000000V5y4EAC","Margin","a0J28000000UuCREA0","","PFM","Decimal","","","","a0J28000000UuCREA0-PFM","SageX3OrderLine"
"a0K28000000V5y5EAC","Tax level 1","a0J28000000UuCREA0","","VACITM1","Char","","","","a0J28000000UuCREA0-VACITM1","SageX3OrderLine"
"a0K28000000V5y6EAC","Tax level 2","a0J28000000UuCREA0","","VACITM2","Char","","","","a0J28000000UuCREA0-VACITM2","SageX3OrderLine"
"a0K28000000V5y7EAC","Tax level 3","a0J28000000UuCREA0","","VACITM3","Char","","","","a0J28000000UuCREA0-VACITM3","SageX3OrderLine"
"a0K28000000V5y8EAC","Sales rep 1","a0J28000000UuCREA0","","REP1","Char","","","","a0J28000000UuCREA0-REP1","SageX3OrderLine"
"a0K28000000V5y9EAC","Commission rate 1","a0J28000000UuCREA0","","REPRAT1","Decimal","","","","a0J28000000UuCREA0-REPRAT1","SageX3OrderLine"
"a0K28000000V5yAEAS","Sales rep 2","a0J28000000UuCREA0","","REP2","Char","","","","a0J28000000UuCREA0-REP2","SageX3OrderLine"
"a0K28000000V5yBEAS","Commission rate 2","a0J28000000UuCREA0","","REPRAT2","Decimal","","","","a0J28000000UuCREA0-REPRAT2","SageX3OrderLine"
"a0K28000000V5yCEAS","Comm. factor","a0J28000000UuCREA0","","REPCOE","Decimal","","","","a0J28000000UuCREA0-REPCOE","SageX3OrderLine"
"a0K28000000V5yDEAS","Last del date","a0J28000000UuCREA0","","DDEMDLVDAT","Date","","","","a0J28000000UuCREA0-DDEMDLVDAT","SageX3OrderLine"
"a0K28000000V5yEEAS","Lead time","a0J28000000UuCREA0","","DDAYLTI","Integer","","","","a0J28000000UuCREA0-DDAYLTI","SageX3OrderLine"
"a0K28000000V5yFEAS","Ship date","a0J28000000UuCREA0","","DSHIDAT","Date","","","","a0J28000000UuCREA0-DSHIDAT","SageX3OrderLine"
"a0K28000000V5yGEAS","Exp delivery date","a0J28000000UuCREA0","","EXTDLVDAT","Date","","","","a0J28000000UuCREA0-EXTDLVDAT","SageX3OrderLine"
"a0K28000000V5yHEAS","Addr","a0J28000000UuCREA0","","DBPAADD","Char","","","","a0J28000000UuCREA0-DBPAADD","SageX3OrderLine"
"a0K28000000V5yIEAS","Delivery contact","a0J28000000UuCREA0","","CNDNAM","Char","","","","a0J28000000UuCREA0-CNDNAM","SageX3OrderLine"
"a0K28000000V5yJEAS","Location reference","a0J28000000UuCREA0","","USEPLC","Char","","","","a0J28000000UuCREA0-USEPLC","SageX3OrderLine"
"a0K28000000V5yKEAS","Deliv priority","a0J28000000UuCREA0","","DDLVPIO","Integer","","1-Normal
2-Urgent
3-Critical","","a0J28000000UuCREA0-DDLVPIO","SageX3OrderLine"
"a0K28000000V5yLEAS","Route no.","a0J28000000UuCREA0","","DDRN","Integer","","1-Route Code 1
2-Route Code 2
3-Route Code 3","","a0J28000000UuCREA0-DDRN","SageX3OrderLine"
"a0K28000000V5yMEAS","Deliv mode","a0J28000000UuCREA0","","DMDL","Char","","","","a0J28000000UuCREA0-DMDL","SageX3OrderLine"
"a0K28000000V5yNEAS","Carrier","a0J28000000UuCREA0","","DBPTNUM","Char","","","","a0J28000000UuCREA0-DBPTNUM","SageX3OrderLine"
"a0K28000000V5yOEAS","Preparation code","a0J28000000UuCREA0","","PRECOD","Char","","","","a0J28000000UuCREA0-PRECOD","SageX3OrderLine"
"a0K28000000V5yPEAS","Package","a0J28000000UuCREA0","","PCK","Char","","","","a0J28000000UuCREA0-PCK","SageX3OrderLine"
"a0K28000000V5yQEAS","Packing capacity","a0J28000000UuCREA0","","PCKCAP","Decimal","","","","a0J28000000UuCREA0-PCKCAP","SageX3OrderLine"
"a0K28000000V5yREAS","Order status","a0J28000000UuCREA0","","DEMSTA","Integer","","1-Firm
2-Planned
3-Suggested
4-Closed","","a0J28000000UuCREA0-DEMSTA","SageX3OrderLine"
"a0K28000000V5ySEAS","Source for delivery","a0J28000000UuCREA0","","FMI","Integer","","1-Stock
2-PO - Direct to Customer
3-PO - Recv and Ship
4-Transfer
5-Work Order","","a0J28000000UuCREA0-FMI","SageX3OrderLine"
"a0K28000000V5yTEAS","Back-to-back order no.","a0J28000000UuCREA0","","FMINUM","Char","","","","a0J28000000UuCREA0-FMINUM","SageX3OrderLine"
"a0K28000000V5yUEAS","Line amt -tax","a0J28000000UuCREA0","","LINORDNOT","Decimal","","","","a0J28000000UuCREA0-LINORDNOT","SageX3OrderLine"
"a0K28000000V5yVEAS","Line amt +tax","a0J28000000UuCREA0","","LINORDATI","Decimal","","","","a0J28000000UuCREA0-LINORDATI","SageX3OrderLine"
"a0K28000000V5yWEAS","Line margin","a0J28000000UuCREA0","","LINPFM","Decimal","","","","a0J28000000UuCREA0-LINPFM","SageX3OrderLine"
"a0K28000000V5yXEAS","Quote no.","a0J28000000UuCREA0","","DETSQHNUM","Char","","","","a0J28000000UuCREA0-DETSQHNUM","SageX3OrderLine"
"a0K28000000V5yYEAS","Line type","a0J28000000UuCREA0","","LINTYP","Integer","","1-Normal
2-Fixed kit
3-Kit Component
4-Kit Option
5-Kit Variant
6-Flex kit
7-BOM component
8-BOM Option
9-BOM Variant
10-Subcontracted
11-Service
12-Supplied material
13-Fixed-amount service","","a0J28000000UuCREA0-LINTYP","SageX3OrderLine"
"a0K28000000V5yZEAS","Free","a0J28000000UuCREA0","","FOCFLG","Integer","","1-No
2-Source
3-Yes","","a0J28000000UuCREA0-FOCFLG","SageX3OrderLine"
"a0K28000000V5yaEAC","Closed","a0J28000000UuCREA0","","SOQSTA","Integer","","1-Pending
2-Late
3-Closed","","a0J28000000UuCREA0-SOQSTA","SageX3OrderLine"
"a0K28000000V5ybEAC","Closing reason","a0J28000000UuCREA0","","DCCLREN","Char","","","","a0J28000000UuCREA0-DCCLREN","SageX3OrderLine"
"a0K28000000V5ycEAC","Date closed","a0J28000000UuCREA0","","DCCLDAT","Date","","","","a0J28000000UuCREA0-DCCLDAT","SageX3OrderLine"
"a0K28000000V5ydEAC","Company name","a0J28000000UuCREA0","","BPRNAM","Char","","","","a0J28000000UuCREA0-BPRNAM","SageX3OrderLine"
"a0K28000000V5yeEAC","Country","a0J28000000UuCREA0","","CRY","Char","","","","a0J28000000UuCREA0-CRY","SageX3OrderLine"
"a0K28000000V5yfEAC","Postal code","a0J28000000UuCREA0","","POSCOD","Char","","","","a0J28000000UuCREA0-POSCOD","SageX3OrderLine"
"a0K28000000V5ygEAC","City","a0J28000000UuCREA0","","CTY","Char","","","","a0J28000000UuCREA0-CTY","SageX3OrderLine"
"a0K28000000V5yhEAC","Person to contact","a0J28000000UuCREA0","","CNTNAM","Char","","","","a0J28000000UuCREA0-CNTNAM","SageX3OrderLine"
"a0K28000000V5yiEAC","EU VAT no.","a0J28000000UuCREA0","","EECNUMX","Char","","","","a0J28000000UuCREA0-EECNUMX","SageX3OrderLine"
"a0K28000000V5yjEAC","Address validation","a0J28000000UuCREA0","","VALADR","Char","","","","a0J28000000UuCREA0-VALADR","SageX3OrderLine"
"a0K28000000V5ykEAC","Validated","a0J28000000UuCREA0","","ADRVAL","Integer","","1-No
2-Yes","","a0J28000000UuCREA0-ADRVAL","SageX3OrderLine"
"a0K28000000V60JEAS","Site","a0J28000000V9LuEAK","","FCY","Char","","","","a0J28000000V9LuEAK-FCY","SageX3SalesPerson"
"a0K28000000V60KEAS","SalesPerson Name","a0J28000000V9LuEAK","","REPNAM","Char","","","","a0J28000000V9LuEAK-REPNAM","SageX3SalesPerson"
"a0K28000000V60LEAS","SalesPerson Number","a0J28000000V9LuEAK","","REPNUM","Char","","","","a0J28000000V9LuEAK-REPNUM","SageX3SalesPerson"
"a0K28000000V60OEAS","Parameter","a0J28000000VR8KEAW","","AXPARCOD","Char","","","","a0J28000000VR8KEAW-AXPARCOD","SageX3ShipWithView"
"a0K28000000V60PEAS","Parameter value","a0J28000000VR8KEAW","","AXPARVAL","Char","","","","a0J28000000VR8KEAW-AXPARVAL","SageX3ShipWithView"
"a0K28000000V60QEAS","A voir","a0J28000000VR8KEAW","","AXWHRLFTBRK","Integer","","","","a0J28000000VR8KEAW-AXWHRLFTBRK","SageX3ShipWithView"
"a0K28000000V60REAS","Selection: Field code","a0J28000000VR8KEAW","","AXWHRCOD","Char","","","","a0J28000000VR8KEAW-AXWHRCOD","SageX3ShipWithView"
"a0K28000000V60SEAS","Selection: Operator","a0J28000000VR8KEAW","","AXWHROPE","Integer","","","","a0J28000000VR8KEAW-AXWHROPE","SageX3ShipWithView"
"a0K28000000V60TEAS","Selection: Value","a0J28000000VR8KEAW","","AXWHRCODVAL","Char","","","","a0J28000000VR8KEAW-AXWHRCODVAL","SageX3ShipWithView"
"a0K28000000V60UEAS","Avoir","a0J28000000VR8KEAW","","AXWHRRGTBRK","Integer","","","","a0J28000000VR8KEAW-AXWHRRGTBRK","SageX3ShipWithView"
"a0K28000000V60VEAS","Selection: Operator and/or","a0J28000000VR8KEAW","","AXWHRANDOR","Integer","","","","a0J28000000VR8KEAW-AXWHRANDOR","SageX3ShipWithView"
"a0K28000000V60WEAS","Sort: Field code","a0J28000000VR8KEAW","","AXORDCOD","Char","","","","a0J28000000VR8KEAW-AXORDCOD","SageX3ShipWithView"
"a0K28000000V60XEAS","Sort: Order","a0J28000000VR8KEAW","","AXORDTYP","Integer","","","","a0J28000000VR8KEAW-AXORDTYP","SageX3ShipWithView"
"a0K28000000V60YEAS","Address line","a0J28000000VR8KEAW","","ADDLIG0","Char","","","","a0J28000000VR8KEAW-ADDLIG0","SageX3ShipWithView"
"a0K28000000V60ZEAS","Address line","a0J28000000VR8KEAW","","ADDLIG1","Char","","","","a0J28000000VR8KEAW-ADDLIG1","SageX3ShipWithView"
"a0K28000000V60aEAC","Address line","a0J28000000VR8KEAW","","ADDLIG2","Char","","","","a0J28000000VR8KEAW-ADDLIG2","SageX3ShipWithView"
"a0K28000000V60bEAC","Address code","a0J28000000VR8KEAW","","BPAADD","Char","","","","a0J28000000VR8KEAW-BPAADD","SageX3ShipWithView"
"a0K28000000V60cEAC","Local menu","a0J28000000VR8KEAW","","BPAADDFLG","Integer","","1-No
2-Yes","","a0J28000000VR8KEAW-BPAADDFLG","SageX3ShipWithView"
"a0K28000000V60dEAC","Description","a0J28000000VR8KEAW","","BPADES","Char","","","","a0J28000000VR8KEAW-BPADES","SageX3ShipWithView"
"a0K28000000V60eEAC","Name","a0J28000000VR8KEAW","","BPCNAM","Char","","","","a0J28000000VR8KEAW-BPCNAM","SageX3ShipWithView"
"a0K28000000V60fEAC","BP number","a0J28000000VR8KEAW","","BPCNUM","Char","","","","a0J28000000VR8KEAW-BPCNUM","SageX3ShipWithView"
"a0K28000000V60gEAC","Type","a0J28000000VR8KEAW","","BPCTYP","Integer","","1-Normal
2-Miscellaneous
3-Intra-company
4-Prospect","","a0J28000000VR8KEAW-BPCTYP","SageX3ShipWithView"
"a0K28000000V60hEAC","Address code","a0J28000000VR8KEAW","","BPDADD","Char","","","","a0J28000000VR8KEAW-BPDADD","SageX3ShipWithView"
"a0K28000000V60iEAC","Local menu","a0J28000000VR8KEAW","","BPDADDFLG","Integer","","1-No
2-Yes","","a0J28000000VR8KEAW-BPDADDFLG","SageX3ShipWithView"
"a0K28000000V60jEAC","Country code","a0J28000000VR8KEAW","","CRY","Char","","","","a0J28000000VR8KEAW-CRY","SageX3ShipWithView"
"a0K28000000V60kEAC","City","a0J28000000VR8KEAW","","CTY","Char","","","","a0J28000000VR8KEAW-CTY","SageX3ShipWithView"
"a0K28000000V60lEAC","Currency","a0J28000000VR8KEAW","","CUR","Char","","","","a0J28000000VR8KEAW-CUR","SageX3ShipWithView"
"a0K28000000V60mEAC","Telephone","a0J28000000VR8KEAW","","FAX","Char","","","","a0J28000000VR8KEAW-FAX","SageX3ShipWithView"
"a0K28000000V60nEAC","Email","a0J28000000VR8KEAW","","FCYWEB","Char","","","","a0J28000000VR8KEAW-FCYWEB","SageX3ShipWithView"
"a0K28000000V60oEAC","Postal code","a0J28000000VR8KEAW","","POSCOD","Char","","","","a0J28000000VR8KEAW-POSCOD","SageX3ShipWithView"
"a0K28000000V60pEAC","Region (county, state, ..)","a0J28000000VR8KEAW","","SAT","Char","","","","a0J28000000VR8KEAW-SAT","SageX3ShipWithView"
"a0K28000000V60qEAC","SHIPTO","a0J28000000VR8KEAW","","SHIPTO","Integer","","1-No
2-Yes","","a0J28000000VR8KEAW-SHIPTO","SageX3ShipWithView"
"a0K28000000V60rEAC","Telephone","a0J28000000VR8KEAW","","TEL","Char","","","","a0J28000000VR8KEAW-TEL","SageX3ShipWithView"
"a0K28000000V60sEAC","Website","a0J28000000VR8KEAW","","WEB","Char","","","","a0J28000000VR8KEAW-WEB","SageX3ShipWithView"
"a0K28000000V616EAC","Parameter","a0J28000000V9LfEAK","","AXPARCOD","Char","","","","a0J28000000V9LfEAK-AXPARCOD","SageX3TermsCode"
"a0K28000000V617EAC","Parameter value","a0J28000000V9LfEAK","","AXPARVAL","Char","","","","a0J28000000V9LfEAK-AXPARVAL","SageX3TermsCode"
"a0K28000000V618EAC","A voir","a0J28000000V9LfEAK","","AXWHRLFTBRK","Integer","","","","a0J28000000V9LfEAK-AXWHRLFTBRK","SageX3TermsCode"
"a0K28000000V619EAC","Selection: Field code","a0J28000000V9LfEAK","","AXWHRCOD","Char","","","","a0J28000000V9LfEAK-AXWHRCOD","SageX3TermsCode"
"a0K28000000V61AEAS","Selection: Operator","a0J28000000V9LfEAK","","AXWHROPE","Integer","","","","a0J28000000V9LfEAK-AXWHROPE","SageX3TermsCode"
"a0K28000000V61BEAS","Selection: Value","a0J28000000V9LfEAK","","AXWHRCODVAL","Char","","","","a0J28000000V9LfEAK-AXWHRCODVAL","SageX3TermsCode"
"a0K28000000V61CEAS","Avoir","a0J28000000V9LfEAK","","AXWHRRGTBRK","Integer","","","","a0J28000000V9LfEAK-AXWHRRGTBRK","SageX3TermsCode"
"a0K28000000V61DEAS","Selection: Operator and/or","a0J28000000V9LfEAK","","AXWHRANDOR","Integer","","","","a0J28000000V9LfEAK-AXWHRANDOR","SageX3TermsCode"
"a0K28000000V61EEAS","Sort: Field code","a0J28000000V9LfEAK","","AXORDCOD","Char","","","","a0J28000000V9LfEAK-AXORDCOD","SageX3TermsCode"
"a0K28000000V61FEAS","Sort: Order","a0J28000000V9LfEAK","","AXORDTYP","Integer","","","","a0J28000000V9LfEAK-AXORDTYP","SageX3TermsCode"
"a0K28000000V61GEAS","Title","a0J28000000V9LfEAK","","DESAXX","Char","","","","a0J28000000V9LfEAK-DESAXX","SageX3TermsCode"
"a0K28000000V61HEAS","Legislation","a0J28000000V9LfEAK","","LEG","Char","","","","a0J28000000V9LfEAK-LEG","SageX3TermsCode"
"a0K28000000V61IEAS","Payment method","a0J28000000V9LfEAK","","PAM","Char","","","","a0J28000000V9LfEAK-PAM","SageX3TermsCode"
"a0K28000000V61JEAS","Payment type","a0J28000000V9LfEAK","","PAMTYP","Integer","","","","a0J28000000V9LfEAK-PAMTYP","SageX3TermsCode"
"a0K28000000V61KEAS","Payment terms","a0J28000000V9LfEAK","","PTE","Char","","","","a0J28000000V9LfEAK-PTE","SageX3TermsCode"
"a0K28000000V61LEAS","Condition Line","a0J28000000V9LfEAK","","PTELIN","Integer","","","","a0J28000000V9LfEAK-PTELIN","SageX3TermsCode"
"a0K28000000V623EAC","Title","a0J28000000V9MiEAK","","DES","Char","","","","a0J28000000V9MiEAK-DES","SageX3UOM"
"a0K28000000V624EAC","Unit","a0J28000000V9MiEAK","","UOM","Char","","","","a0J28000000V9MiEAK-UOM","SageX3UOM"
"a0K28000000VezKEAS","Parameter","a0J28000000V9LQEA0","","AXPARCOD","Char","","","","a0J28000000V9LQEA0-AXPARCOD","SageX3TaxRule"
"a0K28000000VezLEAS","Parameter value","a0J28000000V9LQEA0","","AXPARVAL","Char","","","","a0J28000000V9LQEA0-AXPARVAL","SageX3TaxRule"
"a0K28000000VezMEAS","A voir","a0J28000000V9LQEA0","","AXWHRLFTBRK","Integer","","","","a0J28000000V9LQEA0-AXWHRLFTBRK","SageX3TaxRule"
"a0K28000000VezNEAS","Selection: Field code","a0J28000000V9LQEA0","","AXWHRCOD","Char","","","","a0J28000000V9LQEA0-AXWHRCOD","SageX3TaxRule"
"a0K28000000VezOEAS","Selection: Operator","a0J28000000V9LQEA0","","AXWHROPE","Integer","","","","a0J28000000V9LQEA0-AXWHROPE","SageX3TaxRule"
"a0K28000000VezPEAS","Selection: Value","a0J28000000V9LQEA0","","AXWHRCODVAL","Char","","","","a0J28000000V9LQEA0-AXWHRCODVAL","SageX3TaxRule"
"a0K28000000VezQEAS","Avoir","a0J28000000V9LQEA0","","AXWHRRGTBRK","Integer","","","","a0J28000000V9LQEA0-AXWHRRGTBRK","SageX3TaxRule"
"a0K28000000VezREAS","Selection: Operator and/or","a0J28000000V9LQEA0","","AXWHRANDOR","Integer","","","","a0J28000000V9LQEA0-AXWHRANDOR","SageX3TaxRule"
"a0K28000000VezSEAS","Sort: Field code","a0J28000000V9LQEA0","","AXORDCOD","Char","","","","a0J28000000V9LQEA0-AXORDCOD","SageX3TaxRule"
"a0K28000000VezTEAS","Sort: Order","a0J28000000V9LQEA0","","AXORDTYP","Integer","","","","a0J28000000V9LQEA0-AXORDTYP","SageX3TaxRule"
"a0K28000000VezUEAS","Descriptions","a0J28000000V9LQEA0","","LANDESSHO","Char","","","","a0J28000000V9LQEA0-LANDESSHO","SageX3TaxRule"
"a0K28000000VezVEAS","Legislation","a0J28000000V9LQEA0","","LEG","Char","","","","a0J28000000V9LQEA0-LEG","SageX3TaxRule"
"a0K28000000VezWEAS","Tax rule","a0J28000000V9LQEA0","","VACBPR","Char","","","","a0J28000000V9LQEA0-VACBPR","SageX3TaxRule"
"a0K28000000VezcEAC","Company name","a0J28000000V96JEAS","","BPCNAM","Char","","","","a0J28000000V96JEAS-BPCNAM","SageX3CutomerList"
"a0K28000000VezdEAC","Customer","a0J28000000V96JEAS","","BPCNUM","Char","","","","a0J28000000V96JEAS-BPCNUM","SageX3CutomerList"
"a0K28000000VezeEAC","Active customer","a0J28000000V96JEAS","","BPCSTA","Integer","","","","a0J28000000V96JEAS-BPCSTA","SageX3CutomerList"
"a0K28000000VezfEAC","Type","a0J28000000V96JEAS","","BPCTYP","Integer","","","","a0J28000000V96JEAS-BPCTYP","SageX3CutomerList"
"a0K28000000VezgEAC","Ship-to customer address","a0J28000000V96JEAS","","BPDADD","Char","","","","a0J28000000V96JEAS-BPDADD","SageX3CutomerList"
"a0K28000000VezhEAC","Prospect","a0J28000000V96JEAS","","PPTFLG","Integer","","","","a0J28000000V96JEAS-PPTFLG","SageX3CutomerList"
"a0K28000000VeziEAC","Change date","a0J28000000V96JEAS","","UPDDAT","Date","","","","a0J28000000V96JEAS-UPDDAT","SageX3CutomerList"
"a0K28000000VfRyEAK","Default address","a0J28000000V9OAEA0","","BPAADD","Char","","","","a0J28000000V9OAEA0-BPAADD","SageX3Site"
"a0K28000000VfRzEAK","Country","a0J28000000V9OAEA0","","CRY","Char","","","","a0J28000000V9OAEA0-CRY","SageX3Site"
"a0K28000000VfS0EAK","Site","a0J28000000V9OAEA0","","FCY","Char","","","","a0J28000000V9OAEA0-FCY","SageX3Site"
"a0K28000000VfS1EAK","Name","a0J28000000V9OAEA0","","FCYNAM","Char","","","","a0J28000000V9OAEA0-FCYNAM","SageX3Site"
"a0K28000000VfS2EAK","Legal company","a0J28000000V9OAEA0","","LEGCPY","Char","","","","a0J28000000V9OAEA0-LEGCPY","SageX3Site"
"a0K28000000VfSxEAK","Sold to","a0J28000000WHQ1EAO","","BPCORD","Char","","","","a0J28000000WHQ1EAO-BPCORD","SageX3Customer"
"a0K28000000VfSyEAK","Order state","a0J28000000WHQ1EAO","","BPCSAT","Char","","","","a0J28000000WHQ1EAO-BPCSAT","SageX3Customer"
"a0K28000000VfSzEAK","Req. delivery date","a0J28000000WHQ1EAO","","DEMDLVDAT","Date","","","","a0J28000000WHQ1EAO-DEMDLVDAT","SageX3Customer"
"a0K28000000VfT0EAK","Line amt incl tax","a0J28000000WHQ1EAO","","ORDATI","Decimal","","","","a0J28000000WHQ1EAO-ORDATI","SageX3Customer"
"a0K28000000VfT1EAK","Line amt tax incl. (cy)","a0J28000000WHQ1EAO","","ORDATIL","Decimal","","","","a0J28000000WHQ1EAO-ORDATIL","SageX3Customer"
"a0K28000000VfT2EAK","Order date","a0J28000000WHQ1EAO","","ORDDAT","Date","","","","a0J28000000WHQ1EAO-ORDDAT","SageX3Customer"
"a0K28000000VfT3EAK","Valuation tax incl.","a0J28000000WHQ1EAO","","ORDINVATI","Decimal","","","","a0J28000000WHQ1EAO-ORDINVATI","SageX3Customer"
"a0K28000000VfT4EAK","Order state","a0J28000000WHQ1EAO","","ORDSTA","Integer","","","","a0J28000000WHQ1EAO-ORDSTA","SageX3Customer"
"a0K28000000VfT5EAK","Sales rep","a0J28000000WHQ1EAO","","REP0","Char","","","","a0J28000000WHQ1EAO-REP0","SageX3Customer"
"a0K28000000VfT6EAK","Sales site","a0J28000000WHQ1EAO","","SALFCY","Char","","","","a0J28000000WHQ1EAO-SALFCY","SageX3Customer"
"a0K28000000VfT7EAK","Order no.","a0J28000000WHQ1EAO","","SOHNUM","Char","","","","a0J28000000WHQ1EAO-SOHNUM","SageX3Customer"
"a0K28000000VfT8EAK","Order type","a0J28000000WHQ1EAO","","SOHTYP","Char","","","","a0J28000000WHQ1EAO-SOHTYP","SageX3Customer"
"a0K28000000VfczEAC","ProductLine","a0J28000002aaqAEAQ","","ProductLine","","","","","a0J28000002aaqAEAQ-ProductLine","Sage100ProductFamily"
"a0K28000000Vfd0EAC","ProductLineDesc","a0J28000002aaqAEAQ","","ProductLineDesc","","","","","a0J28000002aaqAEAQ-ProductLineDesc","Sage100ProductFamily"
"a0K28000000Vfd1EAC","ProductType","a0J28000002aaqAEAQ","","ProductType","","","","","a0J28000002aaqAEAQ-ProductType","Sage100ProductFamily"
"a0K28000000Vfd2EAC","Valuation","a0J28000002aaqAEAQ","","Valuation","","","","","a0J28000002aaqAEAQ-Valuation","Sage100ProductFamily"
"a0K28000000Vfd3EAC","PriceCode","a0J28000002aaqAEAQ","","PriceCode","","","","","a0J28000002aaqAEAQ-PriceCode","Sage100ProductFamily"
"a0K28000000Vfd4EAC","AllowBackOrders","a0J28000002aaqAEAQ","","AllowBackOrders","","","","","a0J28000002aaqAEAQ-AllowBackOrders","Sage100ProductFamily"
"a0K28000000Vfd5EAC","ExplodeKitItems","a0J28000002aaqAEAQ","","ExplodeKitItems","","","","","a0J28000002aaqAEAQ-ExplodeKitItems","Sage100ProductFamily"
"a0K28000000Vfd6EAC","CalculateCommission","a0J28000002aaqAEAQ","","CalculateCommission","","","","","a0J28000002aaqAEAQ-CalculateCommission","Sage100ProductFamily"
"a0K28000000Vfd7EAC","StandardUnitOfMeasure","a0J28000002aaqAEAQ","","StandardUnitOfMeasure","","","","","a0J28000002aaqAEAQ-StandardUnitOfMeasure","Sage100ProductFamily"
"a0K28000000Vfd8EAC","PurchaseUnitOfMeasure","a0J28000002aaqAEAQ","","PurchaseUnitOfMeasure","","","","","a0J28000002aaqAEAQ-PurchaseUnitOfMeasure","Sage100ProductFamily"
"a0K28000000Vfd9EAC","SalesUnitOfMeasure","a0J28000002aaqAEAQ","","SalesUnitOfMeasure","","","","","a0J28000002aaqAEAQ-SalesUnitOfMeasure","Sage100ProductFamily"
"a0K28000000VfdAEAS","ProcurementType","a0J28000002aaqAEAQ","","ProcurementType","","","","","a0J28000002aaqAEAQ-ProcurementType","Sage100ProductFamily"
"a0K28000000VfdBEAS","InventoryCycle","a0J28000002aaqAEAQ","","InventoryCycle","","","","","a0J28000002aaqAEAQ-InventoryCycle","Sage100ProductFamily"
"a0K28000000VfdCEAS","AllowTradeDiscount","a0J28000002aaqAEAQ","","AllowTradeDiscount","","","","","a0J28000002aaqAEAQ-AllowTradeDiscount","Sage100ProductFamily"
"a0K28000000VfdDEAS","InactiveItem","a0J28000002aaqAEAQ","","InactiveItem","","","","","a0J28000002aaqAEAQ-InactiveItem","Sage100ProductFamily"
"a0K28000000VfdEEAS","AllocateLandedCost","a0J28000002aaqAEAQ","","AllocateLandedCost","","","","","a0J28000002aaqAEAQ-AllocateLandedCost","Sage100ProductFamily"
"a0K28000000VfdFEAS","TaxClass","a0J28000002aaqAEAQ","","TaxClass","","","","","a0J28000002aaqAEAQ-TaxClass","Sage100ProductFamily"
"a0K28000000VfdGEAS","PurchasesTaxClass","a0J28000002aaqAEAQ","","PurchasesTaxClass","","","","","a0J28000002aaqAEAQ-PurchasesTaxClass","Sage100ProductFamily"
"a0K28000000VfdHEAS","PrintReceiptLabels","a0J28000002aaqAEAQ","","PrintReceiptLabels","","","","","a0J28000002aaqAEAQ-PrintReceiptLabels","Sage100ProductFamily"
"a0K28000000VfdIEAS","ConfirmCostIncrInRcptOfGoods","a0J28000002aaqAEAQ","","ConfirmCostIncrInRcptOfGoods","","","","","a0J28000002aaqAEAQ-ConfirmCostIncrInRcptOfGoods","Sage100ProductFamily"
"a0K28000000VfdJEAS","PostInventoryByWhse","a0J28000002aaqAEAQ","","PostInventoryByWhse","","","","","a0J28000002aaqAEAQ-PostInventoryByWhse","Sage100ProductFamily"
"a0K28000000VfdKEAS","PostCostOfGoodsSoldByWhse","a0J28000002aaqAEAQ","","PostCostOfGoodsSoldByWhse","","","","","a0J28000002aaqAEAQ-PostCostOfGoodsSoldByWhse","Sage100ProductFamily"
"a0K28000000VfdLEAS","PostSalesIncomeByWhse","a0J28000002aaqAEAQ","","PostSalesIncomeByWhse","","","","","a0J28000002aaqAEAQ-PostSalesIncomeByWhse","Sage100ProductFamily"
"a0K28000000VfdMEAS","PostReturnsByWhse","a0J28000002aaqAEAQ","","PostReturnsByWhse","","","","","a0J28000002aaqAEAQ-PostReturnsByWhse","Sage100ProductFamily"
"a0K28000000VfdNEAS","PostAdjustmentByWhse","a0J28000002aaqAEAQ","","PostAdjustmentByWhse","","","","","a0J28000002aaqAEAQ-PostAdjustmentByWhse","Sage100ProductFamily"
"a0K28000000VfdOEAS","PostPurchaseByWhse","a0J28000002aaqAEAQ","","PostPurchaseByWhse","","","","","a0J28000002aaqAEAQ-PostPurchaseByWhse","Sage100ProductFamily"
"a0K28000000VfdPEAS","PostPOVarianceByWhse","a0J28000002aaqAEAQ","","PostPOVarianceByWhse","","","","","a0J28000002aaqAEAQ-PostPOVarianceByWhse","Sage100ProductFamily"
"a0K28000000VfdQEAS","PostMFGVarianceByWhse","a0J28000002aaqAEAQ","","PostMFGVarianceByWhse","","","","","a0J28000002aaqAEAQ-PostMFGVarianceByWhse","Sage100ProductFamily"
"a0K28000000VfdREAS","InventoryAcctKey","a0J28000002aaqAEAQ","","InventoryAcctKey","","","","","a0J28000002aaqAEAQ-InventoryAcctKey","Sage100ProductFamily"
"a0K28000000VfdSEAS","CostOfGoodsSoldAcctKey","a0J28000002aaqAEAQ","","CostOfGoodsSoldAcctKey","","","","","a0J28000002aaqAEAQ-CostOfGoodsSoldAcctKey","Sage100ProductFamily"
"a0K28000000VfdTEAS","SalesIncomeAcctKey","a0J28000002aaqAEAQ","","SalesIncomeAcctKey","","","","","a0J28000002aaqAEAQ-SalesIncomeAcctKey","Sage100ProductFamily"
"a0K28000000VfdUEAS","ReturnsAcctKey","a0J28000002aaqAEAQ","","ReturnsAcctKey","","","","","a0J28000002aaqAEAQ-ReturnsAcctKey","Sage100ProductFamily"
"a0K28000000VfdVEAS","AdjustmentAcctKey","a0J28000002aaqAEAQ","","AdjustmentAcctKey","","","","","a0J28000002aaqAEAQ-AdjustmentAcctKey","Sage100ProductFamily"
"a0K28000000VfdWEAS","PurchaseAcctKey","a0J28000002aaqAEAQ","","PurchaseAcctKey","","","","","a0J28000002aaqAEAQ-PurchaseAcctKey","Sage100ProductFamily"
"a0K28000000VfdXEAS","PurchaseOrderVarianceAcctKey","a0J28000002aaqAEAQ","","PurchaseOrderVarianceAcctKey","","","","","a0J28000002aaqAEAQ-PurchaseOrderVarianceAcctKey","Sage100ProductFamily"
"a0K28000000VfdYEAS","ManufacturingVarianceAcctKey","a0J28000002aaqAEAQ","","ManufacturingVarianceAcctKey","","","","","a0J28000002aaqAEAQ-ManufacturingVarianceAcctKey","Sage100ProductFamily"
"a0K28000000VfdZEAS","WarrantyCode","a0J28000002aaqAEAQ","","WarrantyCode","","","","","a0J28000002aaqAEAQ-WarrantyCode","Sage100ProductFamily"
"a0K28000000VfdaEAC","AllowReturns","a0J28000002aaqAEAQ","","AllowReturns","","","","","a0J28000002aaqAEAQ-AllowReturns","Sage100ProductFamily"
"a0K28000000VfdbEAC","RestockingMethod","a0J28000002aaqAEAQ","","RestockingMethod","","","","","a0J28000002aaqAEAQ-RestockingMethod","Sage100ProductFamily"
"a0K28000000VfdcEAC","ScrapAcctKey","a0J28000002aaqAEAQ","","ScrapAcctKey","","","","","a0J28000002aaqAEAQ-ScrapAcctKey","Sage100ProductFamily"
"a0K28000000VfddEAC","RepairsInProcessAcctKey","a0J28000002aaqAEAQ","","RepairsInProcessAcctKey","","","","","a0J28000002aaqAEAQ-RepairsInProcessAcctKey","Sage100ProductFamily"
"a0K28000000VfdeEAC","RepairsClearingAcctKey","a0J28000002aaqAEAQ","","RepairsClearingAcctKey","","","","","a0J28000002aaqAEAQ-RepairsClearingAcctKey","Sage100ProductFamily"
"a0K28000000VfdfEAC","PostScrapByWhse","a0J28000002aaqAEAQ","","PostScrapByWhse","","","","","a0J28000002aaqAEAQ-PostScrapByWhse","Sage100ProductFamily"
"a0K28000000VfdgEAC","PostRepairsInProcessByWhse","a0J28000002aaqAEAQ","","PostRepairsInProcessByWhse","","","","","a0J28000002aaqAEAQ-PostRepairsInProcessByWhse","Sage100ProductFamily"
"a0K28000000VfdhEAC","PostRepairsClearingByWhse","a0J28000002aaqAEAQ","","PostRepairsClearingByWhse","","","","","a0J28000002aaqAEAQ-PostRepairsClearingByWhse","Sage100ProductFamily"
"a0K28000000VfdiEAC","CommissionRate","a0J28000002aaqAEAQ","","CommissionRate","","","","","a0J28000002aaqAEAQ-CommissionRate","Sage100ProductFamily"
"a0K28000000VfdjEAC","BaseCommAmt","a0J28000002aaqAEAQ","","BaseCommAmt","","","","","a0J28000002aaqAEAQ-BaseCommAmt","Sage100ProductFamily"
"a0K28000000VfdkEAC","PurchaseUMConvFctr","a0J28000002aaqAEAQ","","PurchaseUMConvFctr","","","","","a0J28000002aaqAEAQ-PurchaseUMConvFctr","Sage100ProductFamily"
"a0K28000000VfdlEAC","SalesUMConvFctr","a0J28000002aaqAEAQ","","SalesUMConvFctr","","","","","a0J28000002aaqAEAQ-SalesUMConvFctr","Sage100ProductFamily"
"a0K28000000VfdmEAC","RestockingCharge","a0J28000002aaqAEAQ","","RestockingCharge","","","","","a0J28000002aaqAEAQ-RestockingCharge","Sage100ProductFamily"
"a0K28000000VfdnEAC","DateCreated","a0J28000002aaqAEAQ","","DateCreated","","","","","a0J28000002aaqAEAQ-DateCreated","Sage100ProductFamily"
"a0K28000000VfdoEAC","TimeCreated","a0J28000002aaqAEAQ","","TimeCreated","","","","","a0J28000002aaqAEAQ-TimeCreated","Sage100ProductFamily"
"a0K28000000VfdpEAC","UserCreatedKey","a0J28000002aaqAEAQ","","UserCreatedKey","","","","","a0J28000002aaqAEAQ-UserCreatedKey","Sage100ProductFamily"
"a0K28000000VfdqEAC","DateUpdated","a0J28000002aaqAEAQ","","DateUpdated","","","","","a0J28000002aaqAEAQ-DateUpdated","Sage100ProductFamily"
"a0K28000000VfdrEAC","TimeUpdated","a0J28000002aaqAEAQ","","TimeUpdated","","","","","a0J28000002aaqAEAQ-TimeUpdated","Sage100ProductFamily"
"a0K28000000VfdsEAC","UserUpdatedKey","a0J28000002aaqAEAQ","","UserUpdatedKey","","","","","a0J28000002aaqAEAQ-UserUpdatedKey","Sage100ProductFamily"
"a0K28000000VfdtEAC","ARDivisionNo","a0J28000002anQiEAI","","ARDivisionNo","","","","","a0J28000002anQiEAI-ARDivisionNo","Sage100ShipTo"
"a0K28000000VfduEAC","CustomerNo","a0J28000002anQiEAI","","CustomerNo","","","","","a0J28000002anQiEAI-CustomerNo","Sage100ShipTo"
"a0K28000000VfdvEAC","ShipToCode","a0J28000002anQiEAI","","ShipToCode","","","","","a0J28000002anQiEAI-ShipToCode","Sage100ShipTo"
"a0K28000000VfdwEAC","ShipToName","a0J28000002anQiEAI","","ShipToName","","","","","a0J28000002anQiEAI-ShipToName","Sage100ShipTo"
"a0K28000000VfdxEAC","ShipToAddress1","a0J28000002anQiEAI","","ShipToAddress1","","","","","a0J28000002anQiEAI-ShipToAddress1","Sage100ShipTo"
"a0K28000000VfdyEAC","ShipToAddress2","a0J28000002anQiEAI","","ShipToAddress2","","","","","a0J28000002anQiEAI-ShipToAddress2","Sage100ShipTo"
"a0K28000000VfdzEAC","ShipToAddress3","a0J28000002anQiEAI","","ShipToAddress3","","","","","a0J28000002anQiEAI-ShipToAddress3","Sage100ShipTo"
"a0K28000000Vfe0EAC","ShipToCity","a0J28000002anQiEAI","","ShipToCity","","","","","a0J28000002anQiEAI-ShipToCity","Sage100ShipTo"
"a0K28000000Vfe1EAC","ShipToState","a0J28000002anQiEAI","","ShipToState","","","","","a0J28000002anQiEAI-ShipToState","Sage100ShipTo"
"a0K28000000Vfe2EAC","ShipToZipCode","a0J28000002anQiEAI","","ShipToZipCode","","","","","a0J28000002anQiEAI-ShipToZipCode","Sage100ShipTo"
"a0K28000000Vfe3EAC","ShipToCountryCode","a0J28000002anQiEAI","","ShipToCountryCode","","","","","a0J28000002anQiEAI-ShipToCountryCode","Sage100ShipTo"
