"ID","NAME","ENTITY_ID__C","FIELD_LABEL__C","FIELD_APINAME__C","DATA_TYPE__C","SOURCE_TYPE__C","VALUES__C","GROUP_NAME__C","EXTERNAL_UID__C","ENTITY_CODE__C"
"a0K28000000VsovEAC","ExpirationDate","a0J28000002c4zzEAA","","ExpirationDate","dateTime","","","","a0J28000002c4zzEAA-ExpirationDate","Sage100OrdersLine"
"a0K28000000VsowEAC","ExpirationOverridden","a0J28000002c4zzEAA","","ExpirationOverridden","string","","","","a0J28000002c4zzEAA-ExpirationOverridden","Sage100OrdersLine"
"a0K28000000VsoxEAC","CostOverridden","a0J28000002c4zzEAA","","CostOverridden","string","","","","a0J28000002c4zzEAA-CostOverridden","Sage100OrdersLine"
"a0K28000000VsoyEAC","CostCode","a0J28000002c4zzEAA","","CostCode","string","","","","a0J28000002c4zzEAA-CostCode","Sage100OrdersLine"
"a0K28000000VsozEAC","CostType","a0J28000002c4zzEAA","","CostType","string","","","","a0J28000002c4zzEAA-CostType","Sage100OrdersLine"
"a0K28000000Vsp0EAC","CommentText","a0J28000002c4zzEAA","","CommentText","string","","","","a0J28000002c4zzEAA-CommentText","Sage100OrdersLine"
"a0K28000000Vsp1EAC","APDivisionNo","a0J28000002c4zzEAA","","APDivisionNo","string","","","","a0J28000002c4zzEAA-APDivisionNo","Sage100OrdersLine"
"a0K28000000Vsp2EAC","VendorNo","a0J28000002c4zzEAA","","VendorNo","string","","","","a0J28000002c4zzEAA-VendorNo","Sage100OrdersLine"
"a0K28000000Vsp3EAC","PurchaseOrderNo","a0J28000002c4zzEAA","","PurchaseOrderNo","string","","","","a0J28000002c4zzEAA-PurchaseOrderNo","Sage100OrdersLine"
"a0K28000000Vsp4EAC","PurchaseOrderRequiredDate","a0J28000002c4zzEAA","","PurchaseOrderRequiredDate","dateTime","","","","a0J28000002c4zzEAA-PurchaseOrderRequiredDate","Sage100OrdersLine"
"a0K28000000Vsp5EAC","QuantityOrdered","a0J28000002c4zzEAA","","QuantityOrdered","decimal","","","","a0J28000002c4zzEAA-QuantityOrdered","Sage100OrdersLine"
"a0K28000000Vsp6EAC","QuantityShipped","a0J28000002c4zzEAA","","QuantityShipped","decimal","","","","a0J28000002c4zzEAA-QuantityShipped","Sage100OrdersLine"
"a0K28000000Vsp7EAC","QuantityBackordered","a0J28000002c4zzEAA","","QuantityBackordered","decimal","","","","a0J28000002c4zzEAA-QuantityBackordered","Sage100OrdersLine"
"a0K28000000Vsp8EAC","MasterOriginalQty","a0J28000002c4zzEAA","","MasterOriginalQty","decimal","","","","a0J28000002c4zzEAA-MasterOriginalQty","Sage100OrdersLine"
"a0K28000000Vsp9EAC","MasterQtyBalance","a0J28000002c4zzEAA","","MasterQtyBalance","decimal","","","","a0J28000002c4zzEAA-MasterQtyBalance","Sage100OrdersLine"
"a0K28000000VspAEAS","MasterQtyOrderedToDate","a0J28000002c4zzEAA","","MasterQtyOrderedToDate","decimal","","","","a0J28000002c4zzEAA-MasterQtyOrderedToDate","Sage100OrdersLine"
"a0K28000000VspBEAS","RepeatingQtyShippedToDate","a0J28000002c4zzEAA","","RepeatingQtyShippedToDate","decimal","","","","a0J28000002c4zzEAA-RepeatingQtyShippedToDate","Sage100OrdersLine"
"a0K28000000VspCEAS","UnitPrice","a0J28000002c4zzEAA","","UnitPrice","decimal","","","","a0J28000002c4zzEAA-UnitPrice","Sage100OrdersLine"
"a0K28000000VspDEAS","UnitCost","a0J28000002c4zzEAA","","UnitCost","decimal","","","","a0J28000002c4zzEAA-UnitCost","Sage100OrdersLine"
"a0K28000000VspEEAS","ExtensionAmt","a0J28000002c4zzEAA","","ExtensionAmt","decimal","","","","a0J28000002c4zzEAA-ExtensionAmt","Sage100OrdersLine"
"a0K28000000VspFEAS","UnitOfMeasureConvFactor","a0J28000002c4zzEAA","","UnitOfMeasureConvFactor","decimal","","","","a0J28000002c4zzEAA-UnitOfMeasureConvFactor","Sage100OrdersLine"
"a0K28000000VspGEAS","QuantityPerBill","a0J28000002c4zzEAA","","QuantityPerBill","decimal","","","","a0J28000002c4zzEAA-QuantityPerBill","Sage100OrdersLine"
"a0K28000000VspHEAS","LineDiscountPercent","a0J28000002c4zzEAA","","LineDiscountPercent","decimal","","","","a0J28000002c4zzEAA-LineDiscountPercent","Sage100OrdersLine"
"a0K28000000VspIEAS","LineWeight","a0J28000002c4zzEAA","","LineWeight","decimal","","","","a0J28000002c4zzEAA-LineWeight","Sage100OrdersLine"
"a0K28000000VspJEAS","LotSerialNo","a0J28000002c4zzEAA","","LotSerialNo","string","","","SO_SalesOrderTierDistribution--type","a0J28000002c4zzEAA-LotSerialNo","Sage100OrdersLine"
"a0K28000000VspKEAS","TierType","a0J28000002c4zzEAA","","TierType","string","","","SO_SalesOrderTierDistribution--type","a0J28000002c4zzEAA-TierType","Sage100OrdersLine"
"a0K28000000VuehEAC","TaxSchedule","a0J28000002cCwhEAE","","TaxSchedule","string","","","","a0J28000002cCwhEAE-TaxSchedule","Sage100TaxSchedule"
"a0K28000000VueiEAC","TaxScheduleDesc","a0J28000002cCwhEAE","","TaxScheduleDesc","string","","","","a0J28000002cCwhEAE-TaxScheduleDesc","Sage100TaxSchedule"
"a0K28000000VuejEAC","PrintTaxCodeOnForms","a0J28000002cCwhEAE","","PrintTaxCodeOnForms","string","","","","a0J28000002cCwhEAE-PrintTaxCodeOnForms","Sage100TaxSchedule"
"a0K28000000VwD0EAK","Price List Code","a0J28000002dE5IEAU","","PRICELIST","","","","","a0J28000002dE5IEAU-PRICELIST","Sage300PriceList"
"a0K28000000VwD1EAK","Description","a0J28000002dE5IEAU","","DESC","","","","","a0J28000002dE5IEAU-DESC","Sage300PriceList"
"a0K28000000VwD2EAK","Selling Price Based on","a0J28000002dE5IEAU","","PRICETYPE","","","1-Discount
2-Markup on Markup Cost
3-Markup on Standard Cost
4-Markup on Most Recent Cost
5-Markup on Average Cost
6-Markup on Last Cost
7-Markup on Landed","","a0J28000002dE5IEAU-PRICETYPE","Sage300PriceList"
"a0K28000000VwD3EAK","Discount/Markup on Price by","a0J28000002dE5IEAU","","PRICEFMT","","","1-Percentage
2-Amount","","a0J28000002dE5IEAU-PRICEFMT","Sage300PriceList"
"a0K28000000VwD4EAK","Discount/Markup Percentage 1","a0J28000002dE5IEAU","","PRCNTLVL1","","","","","a0J28000002dE5IEAU-PRCNTLVL1","Sage300PriceList"
"a0K28000000VwD5EAK","Discount/Markup Percentage 2","a0J28000002dE5IEAU","","PRCNTLVL2","","","","","a0J28000002dE5IEAU-PRCNTLVL2","Sage300PriceList"
"a0K28000000VwD6EAK","Discount/Markup Percentage 3","a0J28000002dE5IEAU","","PRCNTLVL3","","","","","a0J28000002dE5IEAU-PRCNTLVL3","Sage300PriceList"
"a0K28000000VwD7EAK","Discount/Markup Percentage 4","a0J28000002dE5IEAU","","PRCNTLVL4","","","","","a0J28000002dE5IEAU-PRCNTLVL4","Sage300PriceList"
"a0K28000000VwD8EAK","Discount/Markup Percentage 5","a0J28000002dE5IEAU","","PRCNTLVL5","","","","","a0J28000002dE5IEAU-PRCNTLVL5","Sage300PriceList"
"a0K28000000VwD9EAK","Price Determined by","a0J28000002dE5IEAU","","PRICEBASE","","","1-Customer Type
2-Volume Discounts","","a0J28000002dE5IEAU-PRICEBASE","Sage300PriceList"
"a0K28000000VwDAEA0","Quantity Level 1","a0J28000002dE5IEAU","","PRICEQTY1","","","","","a0J28000002dE5IEAU-PRICEQTY1","Sage300PriceList"
"a0K28000000VwDBEA0","Quantity Level 2","a0J28000002dE5IEAU","","PRICEQTY2","","","","","a0J28000002dE5IEAU-PRICEQTY2","Sage300PriceList"
"a0K28000000VwDCEA0","Quantity Level 3","a0J28000002dE5IEAU","","PRICEQTY3","","","","","a0J28000002dE5IEAU-PRICEQTY3","Sage300PriceList"
"a0K28000000VwDDEA0","Quantity Level 4","a0J28000002dE5IEAU","","PRICEQTY4","","","","","a0J28000002dE5IEAU-PRICEQTY4","Sage300PriceList"
"a0K28000000VwDEEA0","Quantity Level 5","a0J28000002dE5IEAU","","PRICEQTY5","","","","","a0J28000002dE5IEAU-PRICEQTY5","Sage300PriceList"
"a0K28000000VwDFEA0","Discount/Markup Amount 1","a0J28000002dE5IEAU","","AMOUNTLVL1","","","","","a0J28000002dE5IEAU-AMOUNTLVL1","Sage300PriceList"
"a0K28000000VwDGEA0","Discount/Markup Amount 2","a0J28000002dE5IEAU","","AMOUNTLVL2","","","","","a0J28000002dE5IEAU-AMOUNTLVL2","Sage300PriceList"
"a0K28000000VwDHEA0","Discount/Markup Amount 3","a0J28000002dE5IEAU","","AMOUNTLVL3","","","","","a0J28000002dE5IEAU-AMOUNTLVL3","Sage300PriceList"
"a0K28000000VwDIEA0","Discount/Markup Amount 4","a0J28000002dE5IEAU","","AMOUNTLVL4","","","","","a0J28000002dE5IEAU-AMOUNTLVL4","Sage300PriceList"
"a0K28000000VwDJEA0","Discount/Markup Amount 5","a0J28000002dE5IEAU","","AMOUNTLVL5","","","","","a0J28000002dE5IEAU-AMOUNTLVL5","Sage300PriceList"
"a0K28000000VwDKEA0","Price By","a0J28000002dE5IEAU","","PRICEBY","","","1-Quantity
2-Weight","","a0J28000002dE5IEAU-PRICEBY","Sage300PriceList"
"a0K28000000VwDLEA0","Price Check Type","a0J28000002dE5IEAU","","CPRICETYPE","","","0-None
1-Warning
2-Error
3-Approval","","a0J28000002dE5IEAU-CPRICETYPE","Sage300PriceList"
"a0K28000000VwDMEA0","Check Base","a0J28000002dE5IEAU","","CCHECKBASE","","","1-Cost Plus a Percentage
2-Cost Plus a Fixed Amount
3-Fixed Amount","","a0J28000002dE5IEAU-CCHECKBASE","Sage300PriceList"
"a0K28000000VwDNEA0","Cost/Margin Base","a0J28000002dE5IEAU","","CBASE","","","1-Markup Cost
2-Standard Cost
3-Most Recent Cost
4-Average Cost
5-Last Cost
6-Landed","","a0J28000002dE5IEAU-CBASE","Sage300PriceList"
"a0K28000000VzryEAC","ItemCode","a0J28000002aarmEAA","","ItemCode","","","","","a0J28000002aarmEAA-ItemCode","Sage100ProductCode"
"a0K28000000VzrzEAC","ItemType","a0J28000002aarmEAA","","ItemType","","","","","a0J28000002aarmEAA-ItemType","Sage100ProductCode"
"a0K28000000Vzs0EAC","ItemCodeDesc","a0J28000002aarmEAA","","ItemCodeDesc","","","","","a0J28000002aarmEAA-ItemCodeDesc","Sage100ProductCode"
"a0K28000000Vzs1EAC","ExtendedDescriptionKey","a0J28000002aarmEAA","","ExtendedDescriptionKey","","","","","a0J28000002aarmEAA-ExtendedDescriptionKey","Sage100ProductCode"
"a0K28000000Vzs2EAC","UseInAR","a0J28000002aarmEAA","","UseInAR","","","","","a0J28000002aarmEAA-UseInAR","Sage100ProductCode"
"a0K28000000Vzs3EAC","UseInSO","a0J28000002aarmEAA","","UseInSO","","","","","a0J28000002aarmEAA-UseInSO","Sage100ProductCode"
"a0K28000000Vzs4EAC","UseInPO","a0J28000002aarmEAA","","UseInPO","","","","","a0J28000002aarmEAA-UseInPO","Sage100ProductCode"
"a0K28000000Vzs5EAC","UseInBM","a0J28000002aarmEAA","","UseInBM","","","","","a0J28000002aarmEAA-UseInBM","Sage100ProductCode"
"a0K28000000Vzs6EAC","CalculateCommission","a0J28000002aarmEAA","","CalculateCommission","","","","","a0J28000002aarmEAA-CalculateCommission","Sage100ProductCode"
"a0K28000000Vzs7EAC","DropShip","a0J28000002aarmEAA","","DropShip","","","","","a0J28000002aarmEAA-DropShip","Sage100ProductCode"
"a0K28000000Vzs8EAC","EBMEnabled","a0J28000002aarmEAA","","EBMEnabled","","","","","a0J28000002aarmEAA-EBMEnabled","Sage100ProductCode"
"a0K28000000Vzs9EAC","AllowBackOrders","a0J28000002aarmEAA","","AllowBackOrders","","","","","a0J28000002aarmEAA-AllowBackOrders","Sage100ProductCode"
"a0K28000000VzsAEAS","AllowReturns","a0J28000002aarmEAA","","AllowReturns","","","","","a0J28000002aarmEAA-AllowReturns","Sage100ProductCode"
"a0K28000000VzsBEAS","PriceCode","a0J28000002aarmEAA","","PriceCode","","","","","a0J28000002aarmEAA-PriceCode","Sage100ProductCode"
"a0K28000000VzsCEAS","AllowTradeDiscount","a0J28000002aarmEAA","","AllowTradeDiscount","","","","","a0J28000002aarmEAA-AllowTradeDiscount","Sage100ProductCode"
"a0K28000000VzsDEAS","PrintReceiptLabels","a0J28000002aarmEAA","","PrintReceiptLabels","","","","","a0J28000002aarmEAA-PrintReceiptLabels","Sage100ProductCode"
"a0K28000000VzsEEAS","AllocateLandedCost","a0J28000002aarmEAA","","AllocateLandedCost","","","","","a0J28000002aarmEAA-AllocateLandedCost","Sage100ProductCode"
"a0K28000000VzsFEAS","InactiveItem","a0J28000002aarmEAA","","InactiveItem","","","","","a0J28000002aarmEAA-InactiveItem","Sage100ProductCode"
"a0K28000000VzsGEAS","ConfirmCostIncrInRcptOfGoods","a0J28000002aarmEAA","","ConfirmCostIncrInRcptOfGoods","","","","","a0J28000002aarmEAA-ConfirmCostIncrInRcptOfGoods","Sage100ProductCode"
"a0K28000000VzsHEAS","WarrantyCode","a0J28000002aarmEAA","","WarrantyCode","","","","","a0J28000002aarmEAA-WarrantyCode","Sage100ProductCode"
"a0K28000000VzsIEAS","SalesUnitOfMeasure","a0J28000002aarmEAA","","SalesUnitOfMeasure","","","","","a0J28000002aarmEAA-SalesUnitOfMeasure","Sage100ProductCode"
"a0K28000000VzsJEAS","PurchaseUnitOfMeasure","a0J28000002aarmEAA","","PurchaseUnitOfMeasure","","","","","a0J28000002aarmEAA-PurchaseUnitOfMeasure","Sage100ProductCode"
"a0K28000000VzsKEAS","StandardUnitOfMeasure","a0J28000002aarmEAA","","StandardUnitOfMeasure","","","","","a0J28000002aarmEAA-StandardUnitOfMeasure","Sage100ProductCode"
"a0K28000000VzsLEAS","PostToGLByDivision","a0J28000002aarmEAA","","PostToGLByDivision","","","","","a0J28000002aarmEAA-PostToGLByDivision","Sage100ProductCode"
"a0K28000000VzsMEAS","SalesAcctKey","a0J28000002aarmEAA","","SalesAcctKey","","","","","a0J28000002aarmEAA-SalesAcctKey","Sage100ProductCode"
"a0K28000000VzsNEAS","CostOfGoodsSoldAcctKey","a0J28000002aarmEAA","","CostOfGoodsSoldAcctKey","","","","","a0J28000002aarmEAA-CostOfGoodsSoldAcctKey","Sage100ProductCode"
"a0K28000000VzsOEAS","InventoryAcctKey","a0J28000002aarmEAA","","InventoryAcctKey","","","","","a0J28000002aarmEAA-InventoryAcctKey","Sage100ProductCode"
"a0K28000000VzsPEAS","PurchaseAcctKey","a0J28000002aarmEAA","","PurchaseAcctKey","","","","","a0J28000002aarmEAA-PurchaseAcctKey","Sage100ProductCode"
"a0K28000000VzsQEAS","ManufacturingCostAcctKey","a0J28000002aarmEAA","","ManufacturingCostAcctKey","","","","","a0J28000002aarmEAA-ManufacturingCostAcctKey","Sage100ProductCode"
"a0K28000000VzsREAS","TaxClass","a0J28000002aarmEAA","","TaxClass","","","","","a0J28000002aarmEAA-TaxClass","Sage100ProductCode"
"a0K28000000VzsSEAS","PurchasesTaxClass","a0J28000002aarmEAA","","PurchasesTaxClass","","","","","a0J28000002aarmEAA-PurchasesTaxClass","Sage100ProductCode"
"a0K28000000VzsTEAS","ProductLine","a0J28000002aarmEAA","","ProductLine","","","","","a0J28000002aarmEAA-ProductLine","Sage100ProductCode"
"a0K28000000VzsUEAS","ProductType","a0J28000002aarmEAA","","ProductType","","","","","a0J28000002aarmEAA-ProductType","Sage100ProductCode"
"a0K28000000VzsVEAS","Valuation","a0J28000002aarmEAA","","Valuation","","","","","a0J28000002aarmEAA-Valuation","Sage100ProductCode"
"a0K28000000VzsWEAS","DefaultWarehouseCode","a0J28000002aarmEAA","","DefaultWarehouseCode","","","","","a0J28000002aarmEAA-DefaultWarehouseCode","Sage100ProductCode"
"a0K28000000VzsXEAS","PrimaryAPDivisionNo","a0J28000002aarmEAA","","PrimaryAPDivisionNo","","","","","a0J28000002aarmEAA-PrimaryAPDivisionNo","Sage100ProductCode"
"a0K28000000VzsYEAS","PrimaryVendorNo","a0J28000002aarmEAA","","PrimaryVendorNo","","","","","a0J28000002aarmEAA-PrimaryVendorNo","Sage100ProductCode"
"a0K28000000VzsZEAS","ImageFile","a0J28000002aarmEAA","","ImageFile","","","","","a0J28000002aarmEAA-ImageFile","Sage100ProductCode"
"a0K28000000VzsaEAC","LastSoldDate","a0J28000002aarmEAA","","LastSoldDate","","","","","a0J28000002aarmEAA-LastSoldDate","Sage100ProductCode"
"a0K28000000VzsbEAC","LastReceiptDate","a0J28000002aarmEAA","","LastReceiptDate","","","","","a0J28000002aarmEAA-LastReceiptDate","Sage100ProductCode"
"a0K28000000VzscEAC","Category1","a0J28000002aarmEAA","","Category1","","","","","a0J28000002aarmEAA-Category1","Sage100ProductCode"
"a0K28000000VzsdEAC","Category2","a0J28000002aarmEAA","","Category2","","","","","a0J28000002aarmEAA-Category2","Sage100ProductCode"
"a0K28000000VzseEAC","Category3","a0J28000002aarmEAA","","Category3","","","","","a0J28000002aarmEAA-Category3","Sage100ProductCode"
"a0K28000000VzsfEAC","Category4","a0J28000002aarmEAA","","Category4","","","","","a0J28000002aarmEAA-Category4","Sage100ProductCode"
"a0K28000000VzsgEAC","SalesPromotionCode","a0J28000002aarmEAA","","SalesPromotionCode","","","","","a0J28000002aarmEAA-SalesPromotionCode","Sage100ProductCode"
"a0K28000000VzshEAC","SaleStartingDate","a0J28000002aarmEAA","","SaleStartingDate","","","","","a0J28000002aarmEAA-SaleStartingDate","Sage100ProductCode"
"a0K28000000VzsiEAC","SaleEndingDate","a0J28000002aarmEAA","","SaleEndingDate","","","","","a0J28000002aarmEAA-SaleEndingDate","Sage100ProductCode"
"a0K28000000VzsjEAC","SaleMethod","a0J28000002aarmEAA","","SaleMethod","","","","","a0J28000002aarmEAA-SaleMethod","Sage100ProductCode"
"a0K28000000VzskEAC","ExplodeKitItems","a0J28000002aarmEAA","","ExplodeKitItems","","","","","a0J28000002aarmEAA-ExplodeKitItems","Sage100ProductCode"
"a0K28000000VzslEAC","ShipWeight","a0J28000002aarmEAA","","ShipWeight","","","","","a0J28000002aarmEAA-ShipWeight","Sage100ProductCode"
"a0K28000000VzsmEAC","CommentText","a0J28000002aarmEAA","","CommentText","","","","","a0J28000002aarmEAA-CommentText","Sage100ProductCode"
"a0K28000000VzsnEAC","RestockingMethod","a0J28000002aarmEAA","","RestockingMethod","","","","","a0J28000002aarmEAA-RestockingMethod","Sage100ProductCode"
"a0K28000000VzsoEAC","NextLotSerialNo","a0J28000002aarmEAA","","NextLotSerialNo","","","","","a0J28000002aarmEAA-NextLotSerialNo","Sage100ProductCode"
"a0K28000000VzspEAC","InventoryCycle","a0J28000002aarmEAA","","InventoryCycle","","","","","a0J28000002aarmEAA-InventoryCycle","Sage100ProductCode"
"a0K28000000VzsqEAC","RoutingNo","a0J28000002aarmEAA","","RoutingNo","","","","","a0J28000002aarmEAA-RoutingNo","Sage100ProductCode"
"a0K28000000VzsrEAC","ProcurementType","a0J28000002aarmEAA","","ProcurementType","","","","","a0J28000002aarmEAA-ProcurementType","Sage100ProductCode"
"a0K28000000VzssEAC","PlannerCode","a0J28000002aarmEAA","","PlannerCode","","","","","a0J28000002aarmEAA-PlannerCode","Sage100ProductCode"
"a0K28000000VzstEAC","BuyerCode","a0J28000002aarmEAA","","BuyerCode","","","","","a0J28000002aarmEAA-BuyerCode","Sage100ProductCode"
"a0K28000000VzsuEAC","LowLevelCode","a0J28000002aarmEAA","","LowLevelCode","","","","","a0J28000002aarmEAA-LowLevelCode","Sage100ProductCode"
"a0K28000000VzsvEAC","PlannedByMRP","a0J28000002aarmEAA","","PlannedByMRP","","","","","a0J28000002aarmEAA-PlannedByMRP","Sage100ProductCode"
"a0K28000000VzswEAC","VendorItemCode","a0J28000002aarmEAA","","VendorItemCode","","","","","a0J28000002aarmEAA-VendorItemCode","Sage100ProductCode"
"a0K28000000VzsxEAC","SetupCharge","a0J28000002aarmEAA","","SetupCharge","","","","","a0J28000002aarmEAA-SetupCharge","Sage100ProductCode"
"a0K28000000VzsyEAC","AttachmentFileName","a0J28000002aarmEAA","","AttachmentFileName","","","","","a0J28000002aarmEAA-AttachmentFileName","Sage100ProductCode"
"a0K28000000VzszEAC","ItemImageWidthInPixels","a0J28000002aarmEAA","","ItemImageWidthInPixels","","","","","a0J28000002aarmEAA-ItemImageWidthInPixels","Sage100ProductCode"
"a0K28000000Vzt0EAC","ItemImageHeightInPixels","a0J28000002aarmEAA","","ItemImageHeightInPixels","","","","","a0J28000002aarmEAA-ItemImageHeightInPixels","Sage100ProductCode"
"a0K28000000Vzt1EAC","StandardUnitCost","a0J28000002aarmEAA","","StandardUnitCost","","","","","a0J28000002aarmEAA-StandardUnitCost","Sage100ProductCode"
"a0K28000000Vzt2EAC","StandardUnitPrice","a0J28000002aarmEAA","","StandardUnitPrice","","","","","a0J28000002aarmEAA-StandardUnitPrice","Sage100ProductCode"
"a0K28000000Vzt3EAC","LastTotalUnitCost","a0J28000002aarmEAA","","LastTotalUnitCost","","","","","a0J28000002aarmEAA-LastTotalUnitCost","Sage100ProductCode"
"a0K28000000Vzt4EAC","AverageUnitCost","a0J28000002aarmEAA","","AverageUnitCost","","","","","a0J28000002aarmEAA-AverageUnitCost","Sage100ProductCode"
"a0K28000000Vzt5EAC","SalesPromotionPrice","a0J28000002aarmEAA","","SalesPromotionPrice","","","","","a0J28000002aarmEAA-SalesPromotionPrice","Sage100ProductCode"
"a0K28000000Vzt6EAC","SuggestedRetailPrice","a0J28000002aarmEAA","","SuggestedRetailPrice","","","","","a0J28000002aarmEAA-SuggestedRetailPrice","Sage100ProductCode"
"a0K28000000Vzt7EAC","SalesPromotionDiscountPercent","a0J28000002aarmEAA","","SalesPromotionDiscountPercent","","","","","a0J28000002aarmEAA-SalesPromotionDiscountPercent","Sage100ProductCode"
"a0K28000000Vzt8EAC","TotalQuantityOnHand","a0J28000002aarmEAA","","TotalQuantityOnHand","","","","","a0J28000002aarmEAA-TotalQuantityOnHand","Sage100ProductCode"
"a0K28000000Vzt9EAC","AverageBackOrderFillDays","a0J28000002aarmEAA","","AverageBackOrderFillDays","","","","","a0J28000002aarmEAA-AverageBackOrderFillDays","Sage100ProductCode"
"a0K28000000VztAEAS","LastAllocatedUnitCost","a0J28000002aarmEAA","","LastAllocatedUnitCost","","","","","a0J28000002aarmEAA-LastAllocatedUnitCost","Sage100ProductCode"
"a0K28000000VztBEAS","CommissionRate","a0J28000002aarmEAA","","CommissionRate","","","","","a0J28000002aarmEAA-CommissionRate","Sage100ProductCode"
"a0K28000000VztCEAS","BaseCommAmt","a0J28000002aarmEAA","","BaseCommAmt","","","","","a0J28000002aarmEAA-BaseCommAmt","Sage100ProductCode"
"a0K28000000VztDEAS","PurchaseUMConvFctr","a0J28000002aarmEAA","","PurchaseUMConvFctr","","","","","a0J28000002aarmEAA-PurchaseUMConvFctr","Sage100ProductCode"
"a0K28000000VztEEAS","SalesUMConvFctr","a0J28000002aarmEAA","","SalesUMConvFctr","","","","","a0J28000002aarmEAA-SalesUMConvFctr","Sage100ProductCode"
"a0K28000000VztFEAS","Volume","a0J28000002aarmEAA","","Volume","","","","","a0J28000002aarmEAA-Volume","Sage100ProductCode"
"a0K28000000VztGEAS","RestockingCharge","a0J28000002aarmEAA","","RestockingCharge","","","","","a0J28000002aarmEAA-RestockingCharge","Sage100ProductCode"
"a0K28000000VztHEAS","TotalInventoryValue","a0J28000002aarmEAA","","TotalInventoryValue","","","","","a0J28000002aarmEAA-TotalInventoryValue","Sage100ProductCode"
"a0K28000000VztIEAS","DateCreated","a0J28000002aarmEAA","","DateCreated","","","","","a0J28000002aarmEAA-DateCreated","Sage100ProductCode"
"a0K28000000VztJEAS","TimeCreated","a0J28000002aarmEAA","","TimeCreated","","","","","a0J28000002aarmEAA-TimeCreated","Sage100ProductCode"
"a0K28000000VztKEAS","UserCreatedKey","a0J28000002aarmEAA","","UserCreatedKey","","","","","a0J28000002aarmEAA-UserCreatedKey","Sage100ProductCode"
"a0K28000000VztLEAS","DateUpdated","a0J28000002aarmEAA","","DateUpdated","","","","","a0J28000002aarmEAA-DateUpdated","Sage100ProductCode"
"a0K28000000VztMEAS","TimeUpdated","a0J28000002aarmEAA","","TimeUpdated","","","","","a0J28000002aarmEAA-TimeUpdated","Sage100ProductCode"
"a0K28000000VztNEAS","UserUpdatedKey","a0J28000002aarmEAA","","UserUpdatedKey","","","","","a0J28000002aarmEAA-UserUpdatedKey","Sage100ProductCode"
"a0K28000000VztOEAS","ARDivisionNo","a0J28000002c5JzEAI","","ARDivisionNo","string","","","","a0J28000002c5JzEAI-ARDivisionNo","Sage100ARDivision"
"a0K28000000VztPEAS","ARDivisionDesc","a0J28000002c5JzEAI","","ARDivisionDesc","string","","","","a0J28000002c5JzEAI-ARDivisionDesc","Sage100ARDivision"
"a0K28000000VztQEAS","AccountsReceivableAcctKey","a0J28000002c5JzEAI","","AccountsReceivableAcctKey","string","","","","a0J28000002c5JzEAI-AccountsReceivableAcctKey","Sage100ARDivision"
"a0K28000000VztREAS","CashAcctKey","a0J28000002c5JzEAI","","CashAcctKey","string","","","","a0J28000002c5JzEAI-CashAcctKey","Sage100ARDivision"
"a0K28000000VztSEAS","DiscountsAllowedAcctKey","a0J28000002c5JzEAI","","DiscountsAllowedAcctKey","string","","","","a0J28000002c5JzEAI-DiscountsAllowedAcctKey","Sage100ARDivision"
"a0K28000000VztTEAS","FreightAcctKey","a0J28000002c5JzEAI","","FreightAcctKey","string","","","","a0J28000002c5JzEAI-FreightAcctKey","Sage100ARDivision"
"a0K28000000VztUEAS","SalesTaxAcctKey","a0J28000002c5JzEAI","","SalesTaxAcctKey","string","","","","a0J28000002c5JzEAI-SalesTaxAcctKey","Sage100ARDivision"
"a0K28000000VztVEAS","FinanceChrgAcctKey","a0J28000002c5JzEAI","","FinanceChrgAcctKey","string","","","","a0J28000002c5JzEAI-FinanceChrgAcctKey","Sage100ARDivision"
"a0K28000000VztWEAS","RetentionReceivableAcctKey","a0J28000002c5JzEAI","","RetentionReceivableAcctKey","string","","","","a0J28000002c5JzEAI-RetentionReceivableAcctKey","Sage100ARDivision"
"a0K28000000VztXEAS","PostSalesToGLSubAcct","a0J28000002c5JzEAI","","PostSalesToGLSubAcct","string","","","","a0J28000002c5JzEAI-PostSalesToGLSubAcct","Sage100ARDivision"
"a0K28000000VztYEAS","DateCreated","a0J28000002c5JzEAI","","DateCreated","dateTime","","","","a0J28000002c5JzEAI-DateCreated","Sage100ARDivision"
"a0K28000000VztZEAS","TimeCreated","a0J28000002c5JzEAI","","TimeCreated","string","","","","a0J28000002c5JzEAI-TimeCreated","Sage100ARDivision"
"a0K28000000VztaEAC","UserCreatedKey","a0J28000002c5JzEAI","","UserCreatedKey","string","","","","a0J28000002c5JzEAI-UserCreatedKey","Sage100ARDivision"
"a0K28000000VztbEAC","DateUpdated","a0J28000002c5JzEAI","","DateUpdated","dateTime","","","","a0J28000002c5JzEAI-DateUpdated","Sage100ARDivision"
"a0K28000000VztcEAC","TimeUpdated","a0J28000002c5JzEAI","","TimeUpdated","string","","","","a0J28000002c5JzEAI-TimeUpdated","Sage100ARDivision"
"a0K28000000VztdEAC","UserUpdatedKey","a0J28000002c5JzEAI","","UserUpdatedKey","string","","","","a0J28000002c5JzEAI-UserUpdatedKey","Sage100ARDivision"
"a0K28000000VzteEAC","Category","a0J28000000V97CEAS","","BCGCOD","Char","","","","a0J28000000V97CEAS-BCGCOD","SageX3CustomerAddress"
"a0K28000000VztfEAC","Active","a0J28000000V97CEAS","","BPCSTA","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-BPCSTA","SageX3CustomerAddress"
"a0K28000000VztgEAC","Customer","a0J28000000V97CEAS","","BPCNUM","Char","","","","a0J28000000V97CEAS-BPCNUM","SageX3CustomerAddress"
"a0K28000000VzthEAC","Name","a0J28000000V97CEAS","","BPCNAM","Char","","","","a0J28000000V97CEAS-BPCNAM","SageX3CustomerAddress"
"a0K28000000VztiEAC","Short description","a0J28000000V97CEAS","","BPRSHO","Char","","","","a0J28000000V97CEAS-BPRSHO","SageX3CustomerAddress"
"a0K28000000VztjEAC","Acronym","a0J28000000V97CEAS","","BPRLOG","Char","","","","a0J28000000V97CEAS-BPRLOG","SageX3CustomerAddress"
"a0K28000000VztkEAC","Physical person","a0J28000000V97CEAS","","LEGETT","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-LEGETT","SageX3CustomerAddress"
"a0K28000000VztlEAC","Country","a0J28000000V97CEAS","","CRY","Char","","","","a0J28000000V97CEAS-CRY","SageX3CustomerAddress"
"a0K28000000VztmEAC","Language","a0J28000000V97CEAS","","LAN","Char","","","","a0J28000000V97CEAS-LAN","SageX3CustomerAddress"
"a0K28000000VztnEAC","Site tax ID no.","a0J28000000V97CEAS","","CRN","Char","","","","a0J28000000V97CEAS-CRN","SageX3CustomerAddress"
"a0K28000000VztoEAC","SIC code","a0J28000000V97CEAS","","NAF","Char","","","","a0J28000000V97CEAS-NAF","SageX3CustomerAddress"
"a0K28000000VztpEAC","EU VAT no.","a0J28000000V97CEAS","","EECNUM","Char","","","","a0J28000000V97CEAS-EECNUM","SageX3CustomerAddress"
"a0K28000000VztqEAC","Currency","a0J28000000V97CEAS","","CUR","Char","","","","a0J28000000V97CEAS-CUR","SageX3CustomerAddress"
"a0K28000000VztrEAC","Mailing prohibited","a0J28000000V97CEAS","","BPRFBDMAG","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-BPRFBDMAG","SageX3CustomerAddress"
"a0K28000000VztsEAC","Intersites","a0J28000000V97CEAS","","BETFCY","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-BETFCY","SageX3CustomerAddress"
"a0K28000000VzttEAC","Site","a0J28000000V97CEAS","","FCY","Char","","","","a0J28000000V97CEAS-FCY","SageX3CustomerAddress"
"a0K28000000VztuEAC","Customer","a0J28000000V97CEAS","","BPCFLG","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-BPCFLG","SageX3CustomerAddress"
"a0K28000000VztvEAC","Sales rep","a0J28000000V97CEAS","","REPFLG","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-REPFLG","SageX3CustomerAddress"
"a0K28000000VztwEAC","Prospect","a0J28000000V97CEAS","","PPTFLG","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-PPTFLG","SageX3CustomerAddress"
"a0K28000000VztxEAC","Supplier","a0J28000000V97CEAS","","BPSFLG","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-BPSFLG","SageX3CustomerAddress"
"a0K28000000VztyEAC","Miscellaneous BP","a0J28000000V97CEAS","","BPRACC","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-BPRACC","SageX3CustomerAddress"
"a0K28000000VztzEAC","Service supplier","a0J28000000V97CEAS","","PRVFLG","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-PRVFLG","SageX3CustomerAddress"
"a0K28000000Vzu0EAC","Carrier","a0J28000000V97CEAS","","BPTFLG","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-BPTFLG","SageX3CustomerAddress"
"a0K28000000Vzu1EAC","Service caller","a0J28000000V97CEAS","","DOOFLG","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-DOOFLG","SageX3CustomerAddress"
"a0K28000000Vzu2EAC","Identifier","a0J28000000V97CEAS","","IDENT","Char","","","","a0J28000000V97CEAS-IDENT","SageX3CustomerAddress"
"a0K28000000Vzu3EAC","Address","a0J28000000V97CEAS","","CODADR","Char","","","BPAC_1","a0J28000000V97CEAS-CODADR","SageX3CustomerAddress"
"a0K28000000Vzu4EAC","Description","a0J28000000V97CEAS","","BPADES","Char","","","BPAC_1","a0J28000000V97CEAS-BPADES","SageX3CustomerAddress"
"a0K28000000Vzu5EAC","Country","a0J28000000V97CEAS","","BPACRY","Char","","","BPAC_1","a0J28000000V97CEAS-BPACRY","SageX3CustomerAddress"
"a0K28000000Vzu6EAC","Country name","a0J28000000V97CEAS","","CRYNAM","Char","","","BPAC_1","a0J28000000V97CEAS-CRYNAM","SageX3CustomerAddress"
"a0K28000000Vzu7EAC","Address","a0J28000000V97CEAS","","ADDLIG1","Char","","","BPAC_1","a0J28000000V97CEAS-ADDLIG1","SageX3CustomerAddress"
"a0K28000000Vzu8EAC","Address","a0J28000000V97CEAS","","ADDLIG2","Char","","","BPAC_1","a0J28000000V97CEAS-ADDLIG2","SageX3CustomerAddress"
"a0K28000000Vzu9EAC","Address","a0J28000000V97CEAS","","ADDLIG3","Char","","","BPAC_1","a0J28000000V97CEAS-ADDLIG3","SageX3CustomerAddress"
"a0K28000000VzuAEAS","Postal code","a0J28000000V97CEAS","","POSCOD","Char","","","BPAC_1","a0J28000000V97CEAS-POSCOD","SageX3CustomerAddress"
"a0K28000000VzuBEAS","City","a0J28000000V97CEAS","","CTY","Char","","","BPAC_1","a0J28000000V97CEAS-CTY","SageX3CustomerAddress"
"a0K28000000VzuCEAS","Region (county, state, ..)","a0J28000000V97CEAS","","SAT","Char","","","BPAC_1","a0J28000000V97CEAS-SAT","SageX3CustomerAddress"
"a0K28000000VzuDEAS","Telephone","a0J28000000V97CEAS","","TEL1","Char","","","BPAC_1","a0J28000000V97CEAS-TEL1","SageX3CustomerAddress"
"a0K28000000VzuEEAS","Email","a0J28000000V97CEAS","","WEB1","Char","","","BPAC_1","a0J28000000V97CEAS-WEB1","SageX3CustomerAddress"
"a0K28000000VzuFEAS","Website","a0J28000000V97CEAS","","FCYWEB","Char","","","BPAC_1","a0J28000000V97CEAS-FCYWEB","SageX3CustomerAddress"
"a0K28000000VzuGEAS","External identifier","a0J28000000V97CEAS","","EXTNUM","Char","","","BPAC_1","a0J28000000V97CEAS-EXTNUM","SageX3CustomerAddress"
"a0K28000000VzuHEAS","Default","a0J28000000V97CEAS","","BPAADDFLG","Integer","","1-No
2-Yes","BPAC_1","a0J28000000V97CEAS-BPAADDFLG","SageX3CustomerAddress"
"a0K28000000VzuIEAS","Flag","a0J28000000V97CEAS","","FLMOD","Integer","","","BPAC_1","a0J28000000V97CEAS-FLMOD","SageX3CustomerAddress"
"a0K28000000VzuJEAS","Validated","a0J28000000V97CEAS","","ADRVAL","Integer","","1-No
2-Yes","BPAC_1","a0J28000000V97CEAS-ADRVAL","SageX3CustomerAddress"
"a0K28000000VzuKEAS","Flag","a0J28000000V97CEAS","","FLMODFONC","Integer","","","BPAC_1","a0J28000000V97CEAS-FLMODFONC","SageX3CustomerAddress"
"a0K28000000VzuLEAS","ABC class","a0J28000000V97CEAS","","ABCCLS","Integer","","1-Class A
2-Class B
3-Class C
4-Class D","","a0J28000000V97CEAS-ABCCLS","SageX3CustomerAddress"
"a0K28000000VzuMEAS","Minimum order","a0J28000000V97CEAS","","WORDMINAMT","Decimal","","","","a0J28000000V97CEAS-WORDMINAMT","SageX3CustomerAddress"
"a0K28000000VzuNEAS","Allow order close","a0J28000000V97CEAS","","ORDCLE","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-ORDCLE","SageX3CustomerAddress"
"a0K28000000VzuOEAS","Loan authorized","a0J28000000V97CEAS","","LNDAUZ","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-LNDAUZ","SageX3CustomerAddress"
"a0K28000000VzuPEAS","One order per deliv","a0J28000000V97CEAS","","ODL","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-ODL","SageX3CustomerAddress"
"a0K28000000VzuQEAS","Partial delivery","a0J28000000V97CEAS","","DME","Integer","","1-Allowed
2-Ship line complete
3-Ship order complete","","a0J28000000V97CEAS-DME","SageX3CustomerAddress"
"a0K28000000VzuREAS","Price / Amount type","a0J28000000V97CEAS","","PRITYP","Integer","","1-Exclude tax
2-Include tax","","a0J28000000V97CEAS-PRITYP","SageX3CustomerAddress"
"a0K28000000VzuSEAS","Freight invoicing","a0J28000000V97CEAS","","FREINV","Integer","","1-Invoiced
2-Not invoiced
3-Until threshold 1
4-Until threshold 2
5-Until threshold 3
6-Until threshold 4
7-Until threshold 5","","a0J28000000V97CEAS-FREINV","SageX3CustomerAddress"
"a0K28000000VzuTEAS","Invoicing mode","a0J28000000V97CEAS","","IME","Integer","","1-One/Shipment
2-One/Closed order
3-One/Order
4-One/Ship to
5-One/Period
6-Manual","","a0J28000000V97CEAS-IME","SageX3CustomerAddress"
"a0K28000000VzuUEAS","Invoice period","a0J28000000V97CEAS","","INVPER","Integer","","1-Per request
2-Daily
3-Weekly
4-10 day period
5-2 week period
6-Monthly","","a0J28000000V97CEAS-INVPER","SageX3CustomerAddress"
"a0K28000000VzuVEAS","Due date origin","a0J28000000V97CEAS","","DUDCLC","Integer","","1-Invoice date
2-Shipment date","","a0J28000000V97CEAS-DUDCLC","SageX3CustomerAddress"
"a0K28000000VzuWEAS","Commission category","a0J28000000V97CEAS","","COMCAT","Integer","","1-Category 1
2-Category 2
3-Category 3","","a0J28000000V97CEAS-COMCAT","SageX3CustomerAddress"
"a0K28000000VzuXEAS","Order","a0J28000000V97CEAS","","WORDTEX","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-WORDTEX","SageX3CustomerAddress"
"a0K28000000VzuYEAS","Invoice","a0J28000000V97CEAS","","WINVTEX","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-WINVTEX","SageX3CustomerAddress"
"a0K28000000VzuZEAS","Print ack.","a0J28000000V97CEAS","","OCNFLG","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-OCNFLG","SageX3CustomerAddress"
"a0K28000000VzuaEAC","Template code","a0J28000000V97CEAS","","TPMCOD","Char","","","","a0J28000000V97CEAS-TPMCOD","SageX3CustomerAddress"
"a0K28000000VzubEAC","No.","a0J28000000V97CEAS","","INVDTA","Integer","","","BPC1_6","a0J28000000V97CEAS-INVDTA","SageX3CustomerAddress"
"a0K28000000VzucEAC","Description","a0J28000000V97CEAS","","SHO","Char","","","BPC1_6","a0J28000000V97CEAS-SHO","SageX3CustomerAddress"
"a0K28000000VzudEAC","% or amount","a0J28000000V97CEAS","","INVDTAAMT","Decimal","","","BPC1_6","a0J28000000V97CEAS-INVDTAAMT","SageX3CustomerAddress"
"a0K28000000VzueEAC","Curr.","a0J28000000V97CEAS","","WWCUR","Char","","","BPC1_6","a0J28000000V97CEAS-WWCUR","SageX3CustomerAddress"
"a0K28000000VzufEAC","Customer type","a0J28000000V97CEAS","","BPCTYP","Integer","","1-Normal
2-Miscellaneous
3-Intra-company
4-Prospect","","a0J28000000V97CEAS-BPCTYP","SageX3CustomerAddress"
"a0K28000000VzugEAC","Our supplier no.","a0J28000000V97CEAS","","BPCBPSNUM","Char","","","","a0J28000000V97CEAS-BPCBPSNUM","SageX3CustomerAddress"
"a0K28000000VzuhEAC","Rate type","a0J28000000V97CEAS","","CHGTYP","Integer","","1-Daily Rate
2-Monthly Rate
3-Average Rate
4-Customs Doc File exchange","","a0J28000000V97CEAS-CHGTYP","SageX3CustomerAddress"
"a0K28000000VzuiEAC","Credit control","a0J28000000V97CEAS","","OSTCTL","Integer","","1-Check
2-No Check
3-Hold","","a0J28000000V97CEAS-OSTCTL","SageX3CustomerAddress"
"a0K28000000VzujEAC","Authorized credit","a0J28000000V97CEAS","","WOSTAUZ","Decimal","","","","a0J28000000V97CEAS-WOSTAUZ","SageX3CustomerAddress"
"a0K28000000VzukEAC","Credit level total","a0J28000000V97CEAS","","XOST","Decimal","","","","a0J28000000V97CEAS-XOST","SageX3CustomerAddress"
"a0K28000000VzulEAC","Credit insurance","a0J28000000V97CEAS","","WCDTISR","Decimal","","","","a0J28000000V97CEAS-WCDTISR","SageX3CustomerAddress"
"a0K28000000VzumEAC","Insurance date","a0J28000000V97CEAS","","CDTISRDAT","Date","","","","a0J28000000V97CEAS-CDTISRDAT","SageX3CustomerAddress"
"a0K28000000VzunEAC","Ins. company","a0J28000000V97CEAS","","BPCCDTISR","Char","","","","a0J28000000V97CEAS-BPCCDTISR","SageX3CustomerAddress"
"a0K28000000VzuoEAC","Customer notes","a0J28000000V97CEAS","","BPCNOTE","Char","","","","a0J28000000V97CEAS-BPCNOTE","SageX3CustomerAddress"
"a0K28000000VzupEAC","Business","a0J28000000V97CEAS","","BUS","Char","","","","a0J28000000V97CEAS-BUS","SageX3CustomerAddress"
"a0K28000000VzuqEAC","Source","a0J28000000V97CEAS","","ORIPPT","Char","","","","a0J28000000V97CEAS-ORIPPT","SageX3CustomerAddress"
"a0K28000000VzurEAC","Customer since","a0J28000000V97CEAS","","BPCSNCDAT","Date","","","","a0J28000000V97CEAS-BPCSNCDAT","SageX3CustomerAddress"
"a0K28000000VzusEAC","Token credits","a0J28000000V97CEAS","","PITCDT","Integer","","","","a0J28000000V97CEAS-PITCDT","SageX3CustomerAddress"
"a0K28000000VzutEAC","Manual supplement","a0J28000000V97CEAS","","PITCPT","Integer","","","","a0J28000000V97CEAS-PITCPT","SageX3CustomerAddress"
"a0K28000000VzuuEAC","Total token credit","a0J28000000V97CEAS","","TOTPIT","Integer","","","","a0J28000000V97CEAS-TOTPIT","SageX3CustomerAddress"
"a0K28000000VzuvEAC","Points debit","a0J28000000V97CEAS","","BPCPITDEB","Integer","","","","a0J28000000V97CEAS-BPCPITDEB","SageX3CustomerAddress"
"a0K28000000VzuwEAC","Value  0","a0J28000000V97CEAS","","NULPIO","Integer","","1-No
2-Yes","","a0J28000000V97CEAS-NULPIO","SageX3CustomerAddress"
"a0K28000000VzuxEAC","Chosen service","a0J28000000V97CEAS","","COTCHX","Char","","","","a0J28000000V97CEAS-COTCHX","SageX3CustomerAddress"
"a0K28000000VzuyEAC","Tokens necessary","a0J28000000V97CEAS","","COTPITRQD","Integer","","","","a0J28000000V97CEAS-COTPITRQD","SageX3CustomerAddress"
"a0K28000000VzuzEAC","Bill-to customer","a0J28000000V97CEAS","","BPCINV","Char","","","","a0J28000000V97CEAS-BPCINV","SageX3CustomerAddress"
"a0K28000000Vzv0EAC","Pay by","a0J28000000V97CEAS","","BPCPYR","Char","","","","a0J28000000V97CEAS-BPCPYR","SageX3CustomerAddress"
"a0K28000000Vzv1EAC","Factor","a0J28000000V97CEAS","","FCTNUM","Char","","","","a0J28000000V97CEAS-FCTNUM","SageX3CustomerAddress"
"a0K28000000Vzv2EAC","Group customer","a0J28000000V97CEAS","","BPCGRU","Char","","","","a0J28000000V97CEAS-BPCGRU","SageX3CustomerAddress"
"a0K28000000Vzv3EAC","Risk BP","a0J28000000V97CEAS","","BPCRSK","Char","","","","a0J28000000V97CEAS-BPCRSK","SageX3CustomerAddress"
"a0K28000000Vzv4EAC","Accounting code","a0J28000000V97CEAS","","ACCCOD","Char","","","","a0J28000000V97CEAS-ACCCOD","SageX3CustomerAddress"
"a0K28000000Vzv5EAC","Account structure","a0J28000000V97CEAS","","DIA","Char","","","","a0J28000000V97CEAS-DIA","SageX3CustomerAddress"
"a0K28000000Vzv6EAC","Tax rule","a0J28000000V97CEAS","","VACBPR","Char","","","","a0J28000000V97CEAS-VACBPR","SageX3CustomerAddress"
"a0K28000000Vzv7EAC","Exemption no.","a0J28000000V97CEAS","","VATEXN","Char","","","","a0J28000000V97CEAS-VATEXN","SageX3CustomerAddress"
"a0K28000000Vzv8EAC","Payment terms","a0J28000000V97CEAS","","PTE","Char","","","","a0J28000000V97CEAS-PTE","SageX3CustomerAddress"
"a0K28000000Vzv9EAC","Payment days","a0J28000000V97CEAS","","J1","Integer","","","","a0J28000000V97CEAS-J1","SageX3CustomerAddress"
"a0K28000000VzvAEAS","Reminder group","a0J28000000V97CEAS","","GRP","Char","","","","a0J28000000V97CEAS-GRP","SageX3CustomerAddress"
"a0K28000000VzvBEAS","Unavailable","a0J28000000V97CEAS","","UVYCOD2","Char","","","","a0J28000000V97CEAS-UVYCOD2","SageX3CustomerAddress"
"a0K28000000VzvCEAS","Settlement discount","a0J28000000V97CEAS","","DEP","Char","","","","a0J28000000V97CEAS-DEP","SageX3CustomerAddress"
"a0K28000000VzvDEAS","Bank","a0J28000000V97CEAS","","PAYBAN","Char","","","","a0J28000000V97CEAS-PAYBAN","SageX3CustomerAddress"
"a0K28000000VzvEEAS","Reminder type","a0J28000000V97CEAS","","FUPTYP","Integer","","1-No reminder
2-By invoice
3-Global
4-Global by level
5-Global by date","","a0J28000000V97CEAS-FUPTYP","SageX3CustomerAddress"
"a0K28000000VzvFEAS","Min reminder","a0J28000000V97CEAS","","FUPMINAMT","Decimal","","","","a0J28000000V97CEAS-FUPMINAMT","SageX3CustomerAddress"
"a0K28000000VzvGEAS","Note type","a0J28000000V97CEAS","","SOIPER","Integer","","1-Per Request
2-Weekly
3-10-day Period
4-2-week Period
5-Monthly","","a0J28000000V97CEAS-SOIPER","SageX3CustomerAddress"
"a0K28000000VzvHEAS","Sage Exchange","a0J28000000V97CEAS","","SEBPC","Char","","","","a0J28000000V97CEAS-SEBPC","SageX3CustomerAddress"
"a0K28000000VzvIEAS","Dimension type","a0J28000000V97CEAS","","DIE","Char","","","BPC3_4","a0J28000000V97CEAS-DIE","SageX3CustomerAddress"
"a0K28000000VzvJEAS","Analytical dimension","a0J28000000V97CEAS","","CCE","Char","","","BPC3_4","a0J28000000V97CEAS-CCE","SageX3CustomerAddress"
"a0K28000000VzvKEAS","Tax rule","a0J28000000V97CEAS","","CSHVATRGM","Integer","","1-No
2-Yes","BPC3_6","a0J28000000V97CEAS-CSHVATRGM","SageX3CustomerAddress"
"a0K28000000VzvLEAS","VAT start date","a0J28000000V97CEAS","","VATSTRDAT","Date","","","BPC3_6","a0J28000000V97CEAS-VATSTRDAT","SageX3CustomerAddress"
"a0K28000000VzvMEAS","VAT end date","a0J28000000V97CEAS","","VATENDDAT","Date","","","BPC3_6","a0J28000000V97CEAS-VATENDDAT","SageX3CustomerAddress"
"a0K28000000VzvNEAS","Addr","a0J28000000V97CEAS","","BPAADD","Char","","","BPC4_1","a0J28000000V97CEAS-BPAADD","SageX3CustomerAddress"
"a0K28000000VzvOEAS","Company name","a0J28000000V97CEAS","","BPDNAM0","Char","","","BPC4_1","a0J28000000V97CEAS-BPDNAM0","SageX3CustomerAddress"
"a0K28000000VzvPEAS","Company name","a0J28000000V97CEAS","","BPDNAM1","Char","","","BPC4_1","a0J28000000V97CEAS-BPDNAM1","SageX3CustomerAddress"
"a0K28000000VzvQEAS","Shipment site","a0J28000000V97CEAS","","STOFCY","Char","","","BPC4_1","a0J28000000V97CEAS-STOFCY","SageX3CustomerAddress"
"a0K28000000VzvREAS","Loan location","a0J28000000V97CEAS","","BPCLOC","Char","","","BPC4_1","a0J28000000V97CEAS-BPCLOC","SageX3CustomerAddress"
"a0K28000000VzvSEAS","Subcontract loc","a0J28000000V97CEAS","","SCOLOC","Char","","","BPC4_1","a0J28000000V97CEAS-SCOLOC","SageX3CustomerAddress"
"a0K28000000VzvTEAS","Receiving site","a0J28000000V97CEAS","","RCPFCY","Char","","","BPC4_1","a0J28000000V97CEAS-RCPFCY","SageX3CustomerAddress"
"a0K28000000VzvUEAS","Route no.","a0J28000000V97CEAS","","DRN","Integer","","1-Route Code 1
2-Route Code 2
3-Route Code 3","BPC4_1","a0J28000000V97CEAS-DRN","SageX3CustomerAddress"
"a0K28000000VzvVEAS","Delivery priority","a0J28000000V97CEAS","","DLVPIO","Integer","","1-Normal
2-Urgent
3-Critical","BPC4_1","a0J28000000V97CEAS-DLVPIO","SageX3CustomerAddress"
"a0K28000000VzvWEAS","Carrier","a0J28000000V97CEAS","","BPTNUM","Char","","","BPC4_1","a0J28000000V97CEAS-BPTNUM","SageX3CustomerAddress"
"a0K28000000VzvXEAS","Delivery mode","a0J28000000V97CEAS","","MDL","Char","","","BPC4_1","a0J28000000V97CEAS-MDL","SageX3CustomerAddress"
"a0K28000000VzvYEAS","Delivery LT in days","a0J28000000V97CEAS","","DAYLTI","Integer","","","BPC4_1","a0J28000000V97CEAS-DAYLTI","SageX3CustomerAddress"
"a0K28000000VzvZEAS","EU increase","a0J28000000V97CEAS","","EECINCRAT","Decimal","","","BPC4_1","a0J28000000V97CEAS-EECINCRAT","SageX3CustomerAddress"
"a0K28000000VzvaEAC","Picking ticket print","a0J28000000V97CEAS","","NPRFLG","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V97CEAS-NPRFLG","SageX3CustomerAddress"
"a0K28000000VzvbEAC","Print delivery note","a0J28000000V97CEAS","","NDEFLG","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V97CEAS-NDEFLG","SageX3CustomerAddress"
"a0K28000000VzvcEAC","Sales rep","a0J28000000V97CEAS","","REP0","Char","","","BPC4_1","a0J28000000V97CEAS-REP0","SageX3CustomerAddress"
"a0K28000000VzvdEAC","Previous representative","a0J28000000V97CEAS","","PREREP0","Char","","","BPC4_1","a0J28000000V97CEAS-PREREP0","SageX3CustomerAddress"
"a0K28000000VzveEAC","Sales rep","a0J28000000V97CEAS","","REP1","Char","","","BPC4_1","a0J28000000V97CEAS-REP1","SageX3CustomerAddress"
"a0K28000000VzvfEAC","Previous representative","a0J28000000V97CEAS","","PREREP1","Char","","","BPC4_1","a0J28000000V97CEAS-PREREP1","SageX3CustomerAddress"
"a0K28000000VzvgEAC","Picking header text","a0J28000000V97CEAS","","PRPTEX","Char","","","BPC4_1","a0J28000000V97CEAS-PRPTEX","SageX3CustomerAddress"
"a0K28000000VzvhEAC","Delivery header text","a0J28000000V97CEAS","","DLVTEX","Char","","","BPC4_1","a0J28000000V97CEAS-DLVTEX","SageX3CustomerAddress"
"a0K28000000VzviEAC","Monday","a0J28000000V97CEAS","","UVYDAY1","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V97CEAS-UVYDAY1","SageX3CustomerAddress"
"a0K28000000VzvjEAC","Tuesday","a0J28000000V97CEAS","","UVYDAY2","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V97CEAS-UVYDAY2","SageX3CustomerAddress"
"a0K28000000VzvkEAC","Wednesday","a0J28000000V97CEAS","","UVYDAY3","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V97CEAS-UVYDAY3","SageX3CustomerAddress"
"a0K28000000VzvlEAC","Thursday","a0J28000000V97CEAS","","UVYDAY4","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V97CEAS-UVYDAY4","SageX3CustomerAddress"
"a0K28000000VzvmEAC","Friday","a0J28000000V97CEAS","","UVYDAY5","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V97CEAS-UVYDAY5","SageX3CustomerAddress"
"a0K28000000VzvnEAC","Saturday","a0J28000000V97CEAS","","UVYDAY6","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V97CEAS-UVYDAY6","SageX3CustomerAddress"
"a0K28000000VzvoEAC","Sunday","a0J28000000V97CEAS","","UVYDAY7","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V97CEAS-UVYDAY7","SageX3CustomerAddress"
"a0K28000000VzvpEAC","Unavailable","a0J28000000V97CEAS","","UVYCOD","Char","","","BPC4_1","a0J28000000V97CEAS-UVYCOD","SageX3CustomerAddress"
"a0K28000000VzvqEAC","Incoterm","a0J28000000V97CEAS","","EECICT","Char","","","BPC4_1","a0J28000000V97CEAS-EECICT","SageX3CustomerAddress"
"a0K28000000VzvrEAC","Intrastat transport location","a0J28000000V97CEAS","","EECLOC","Integer","","1-Domestic
2-Other EU
3-Outside EU","BPC4_1","a0J28000000V97CEAS-EECLOC","SageX3CustomerAddress"
"a0K28000000VzvsEAC","Entity/Use","a0J28000000V97CEAS","","SSTENTCOD","Char","","","BPC4_1","a0J28000000V97CEAS-SSTENTCOD","SageX3CustomerAddress"
"a0K28000000VzvtEAC","Active","a0J28000000V97CEAS","","ENAFLG","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V97CEAS-ENAFLG","SageX3CustomerAddress"
"a0K28000000VzvuEAC","Tax rule","a0J28000000V97CEAS","","VACBPD","Char","","","BPC4_1","a0J28000000V97CEAS-VACBPD","SageX3CustomerAddress"
"a0K28000000VzvvEAC","Incoterm town","a0J28000000V97CEAS","","ICTCTY","Char","","","BPC4_1","a0J28000000V97CEAS-ICTCTY","SageX3CustomerAddress"
"a0K28000000VzvwEAC","Freight agent","a0J28000000V97CEAS","","FFWNUM","Char","","","BPC4_1","a0J28000000V97CEAS-FFWNUM","SageX3CustomerAddress"
"a0K28000000VzvxEAC","Forwarding agent address","a0J28000000V97CEAS","","FFWADD","Char","","","BPC4_1","a0J28000000V97CEAS-FFWADD","SageX3CustomerAddress"
"a0K28000000VzvyEAC","Default ship-to customer","a0J28000000V97CEAS","","BPDADDFLG","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V97CEAS-BPDADDFLG","SageX3CustomerAddress"
"a0K28000000VzvzEAC","Export number","a0J28000000V97CEAS","","EXPNUM","Integer","","","BPC4_1","a0J28000000V97CEAS-EXPNUM","SageX3CustomerAddress"
"a0K28000000Vzw0EAC","Creation user","a0J28000000V97CEAS","","CREUSR","Char","","","BPC4_1","a0J28000000V97CEAS-CREUSR","SageX3CustomerAddress"
"a0K28000000Vzw1EAC","Date created","a0J28000000V97CEAS","","CREDAT","Date","","","BPC4_1","a0J28000000V97CEAS-CREDAT","SageX3CustomerAddress"
"a0K28000000Vzw2EAC","Change user","a0J28000000V97CEAS","","UPDUSR","Char","","","BPC4_1","a0J28000000V97CEAS-UPDUSR","SageX3CustomerAddress"
"a0K28000000Vzw3EAC","Change date","a0J28000000V97CEAS","","UPDDAT","Date","","","BPC4_1","a0J28000000V97CEAS-UPDDAT","SageX3CustomerAddress"
"a0K28000000Vzw4EAC","Addr","a0J28000000V97CEAS","","BIDBPAADD","Char","","","BIDC_1","a0J28000000V97CEAS-BIDBPAADD","SageX3CustomerAddress"
"a0K28000000Vzw5EAC","Country","a0J28000000V97CEAS","","BIDCRY","Char","","","BIDC_1","a0J28000000V97CEAS-BIDCRY","SageX3CustomerAddress"
"a0K28000000Vzw6EAC","IBAN pref","a0J28000000V97CEAS","","IBAN","Char","","","BIDC_1","a0J28000000V97CEAS-IBAN","SageX3CustomerAddress"
"a0K28000000Vzw7EAC","Bank ID number","a0J28000000V97CEAS","","BIDNUM","Char","","","BIDC_1","a0J28000000V97CEAS-BIDNUM","SageX3CustomerAddress"
"a0K28000000Vzw8EAC","Default","a0J28000000V97CEAS","","BIDNUMFLG","Integer","","1-No
2-Yes","BIDC_1","a0J28000000V97CEAS-BIDNUMFLG","SageX3CustomerAddress"
"a0K28000000Vzw9EAC","Curr.","a0J28000000V97CEAS","","BIDCUR","Char","","","BIDC_1","a0J28000000V97CEAS-BIDCUR","SageX3CustomerAddress"
"a0K28000000VzwAEAS","Domicile","a0J28000000V97CEAS","","PAB1","Char","","","BIDC_1","a0J28000000V97CEAS-PAB1","SageX3CustomerAddress"
"a0K28000000VzwBEAS","Beneficiary","a0J28000000V97CEAS","","BNF","Char","","","BIDC_1","a0J28000000V97CEAS-BNF","SageX3CustomerAddress"
"a0K28000000VzwCEAS","Paying bank 2","a0J28000000V97CEAS","","PAB2","Char","","","BIDC_1","a0J28000000V97CEAS-PAB2","SageX3CustomerAddress"
"a0K28000000VzwDEAS","Address 3","a0J28000000V97CEAS","","PAB3","Char","","","BIDC_1","a0J28000000V97CEAS-PAB3","SageX3CustomerAddress"
"a0K28000000VzwEEAS","Address 4","a0J28000000V97CEAS","","PAB4","Char","","","BIDC_1","a0J28000000V97CEAS-PAB4","SageX3CustomerAddress"
"a0K28000000VzwFEAS","BIC code","a0J28000000V97CEAS","","BICCOD","Char","","","BIDC_1","a0J28000000V97CEAS-BICCOD","SageX3CustomerAddress"
"a0K28000000VzwGEAS","Intermediary bank","a0J28000000V97CEAS","","MIDPAB1","Char","","","BIDC_1","a0J28000000V97CEAS-MIDPAB1","SageX3CustomerAddress"
"a0K28000000VzwHEAS","Paying bank 1","a0J28000000V97CEAS","","MIDPAB2","Char","","","BIDC_1","a0J28000000V97CEAS-MIDPAB2","SageX3CustomerAddress"
"a0K28000000VzwIEAS","Paying bank 2","a0J28000000V97CEAS","","MIDPAB3","Char","","","BIDC_1","a0J28000000V97CEAS-MIDPAB3","SageX3CustomerAddress"
"a0K28000000VzwJEAS","Address 3","a0J28000000V97CEAS","","MIDPAB4","Char","","","BIDC_1","a0J28000000V97CEAS-MIDPAB4","SageX3CustomerAddress"
"a0K28000000VzwKEAS","BIC code","a0J28000000V97CEAS","","MIDBICCOD","Char","","","BIDC_1","a0J28000000V97CEAS-MIDBICCOD","SageX3CustomerAddress"
"a0K28000000VzwLEAS","Country","a0J28000000V97CEAS","","MIDCRY","Char","","","BIDC_1","a0J28000000V97CEAS-MIDCRY","SageX3CustomerAddress"
"a0K28000000VzwMEAS","Code","a0J28000000V97CEAS","","CCNCRM","Char","","","CNTC_1","a0J28000000V97CEAS-CCNCRM","SageX3CustomerAddress"
"a0K28000000VzwNEAS","Surname","a0J28000000V97CEAS","","CNTLNA","Char","","","CNTC_1","a0J28000000V97CEAS-CNTLNA","SageX3CustomerAddress"
"a0K28000000VzwOEAS","First name","a0J28000000V97CEAS","","CNTFNA","Char","","","CNTC_1","a0J28000000V97CEAS-CNTFNA","SageX3CustomerAddress"
"a0K28000000VzwPEAS","Country","a0J28000000V97CEAS","","CNTCRY","Char","","","CNTC_1","a0J28000000V97CEAS-CNTCRY","SageX3CustomerAddress"
"a0K28000000VzwQEAS","By default","a0J28000000V97CEAS","","CNTFLG","Integer","","1-No
2-Yes","CNTC_1","a0J28000000V97CEAS-CNTFLG","SageX3CustomerAddress"
"a0K28000000VzwREAS","Title","a0J28000000V97CEAS","","CNTTTL","Integer","","1-Mr
2-Mrs
3-Ms","CNTC_1","a0J28000000V97CEAS-CNTTTL","SageX3CustomerAddress"
"a0K28000000VzwSEAS","Function","a0J28000000V97CEAS","","CNTFNC","Integer","","1-CEO
2-Sales Director
3-Technical Director
4-Purchasing Director
5-Buyer
6-Inventory Director
7-Financial and Legal Director
8-Import/Export Director
9-Site Director
10-External Consultant
11-Other
12-REACH contact","CNTC_1","a0J28000000V97CEAS-CNTFNC","SageX3CustomerAddress"
"a0K28000000VzwTEAS","Department","a0J28000000V97CEAS","","CNTSRV","Char","","","CNTC_1","a0J28000000V97CEAS-CNTSRV","SageX3CustomerAddress"
"a0K28000000VzwUEAS","Address","a0J28000000V97CEAS","","CNTADD","Char","","","CNTC_1","a0J28000000V97CEAS-CNTADD","SageX3CustomerAddress"
"a0K28000000VzwVEAS","Telephone","a0J28000000V97CEAS","","CNTTEL","Char","","","CNTC_1","a0J28000000V97CEAS-CNTTEL","SageX3CustomerAddress"
"a0K28000000VzwWEAS","Fax","a0J28000000V97CEAS","","CNTFAX","Char","","","CNTC_1","a0J28000000V97CEAS-CNTFAX","SageX3CustomerAddress"
"a0K28000000VzwXEAS","Mobile phone","a0J28000000V97CEAS","","CNTMOB","Char","","","CNTC_1","a0J28000000V97CEAS-CNTMOB","SageX3CustomerAddress"
"a0K28000000VzwYEAS","Email","a0J28000000V97CEAS","","CNTWEB","Char","","","CNTC_1","a0J28000000V97CEAS-CNTWEB","SageX3CustomerAddress"
"a0K28000000VzwZEAS","Role","a0J28000000V97CEAS","","CNTMSS","Char","","","CNTC_1","a0J28000000V97CEAS-CNTMSS","SageX3CustomerAddress"
"a0K28000000VzwaEAC","Birth date","a0J28000000V97CEAS","","CNTBIR","Date","","","CNTC_1","a0J28000000V97CEAS-CNTBIR","SageX3CustomerAddress"
"a0K28000000VzwbEAC","Search key","a0J28000000V97CEAS","","CNTFULNAM","Char","","","CNTC_1","a0J28000000V97CEAS-CNTFULNAM","SageX3CustomerAddress"
"a0K28000000VzwcEAC","Mailing prohibited","a0J28000000V97CEAS","","CNTFBDMAG","Integer","","1-No
2-Yes","CNTC_1","a0J28000000V97CEAS-CNTFBDMAG","SageX3CustomerAddress"
"a0K28000000VzwdEAC","Language","a0J28000000V97CEAS","","CNTLAN","Char","","","CNTC_1","a0J28000000V97CEAS-CNTLAN","SageX3CustomerAddress"
"a0K28000000VzweEAC","Category","a0J28000000V97CEAS","","CNTCSP","Char","","","CNTC_1","a0J28000000V97CEAS-CNTCSP","SageX3CustomerAddress"
"a0K28000000VzwfEAC","Flag","a0J28000000V97CEAS","","FLNEW","Integer","","","CNTC_1","a0J28000000V97CEAS-FLNEW","SageX3CustomerAddress"
"a0K28000000VzziEAC","Monday","a0J28000000V96TEAS","","UVYDAY1","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V96TEAS-UVYDAY1","SageX3CutomerHeader"
"a0K28000000VzzjEAC","Tuesday","a0J28000000V96TEAS","","UVYDAY2","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V96TEAS-UVYDAY2","SageX3CutomerHeader"
"a0K28000000VzzkEAC","Wednesday","a0J28000000V96TEAS","","UVYDAY3","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V96TEAS-UVYDAY3","SageX3CutomerHeader"
"a0K28000000VzzlEAC","Thursday","a0J28000000V96TEAS","","UVYDAY4","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V96TEAS-UVYDAY4","SageX3CutomerHeader"
"a0K28000000VzzmEAC","Friday","a0J28000000V96TEAS","","UVYDAY5","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V96TEAS-UVYDAY5","SageX3CutomerHeader"
"a0K28000000VzznEAC","Saturday","a0J28000000V96TEAS","","UVYDAY6","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V96TEAS-UVYDAY6","SageX3CutomerHeader"
"a0K28000000VzzoEAC","Sunday","a0J28000000V96TEAS","","UVYDAY7","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V96TEAS-UVYDAY7","SageX3CutomerHeader"
"a0K28000000VzzpEAC","Unavailable","a0J28000000V96TEAS","","UVYCOD","Char","","","BPC4_1","a0J28000000V96TEAS-UVYCOD","SageX3CutomerHeader"
"a0K28000000VzzqEAC","Incoterm","a0J28000000V96TEAS","","EECICT","Char","","","BPC4_1","a0J28000000V96TEAS-EECICT","SageX3CutomerHeader"
"a0K28000000VzzrEAC","Intrastat transport location","a0J28000000V96TEAS","","EECLOC","Integer","","1-Domestic
2-Other EU
3-Outside EU","BPC4_1","a0J28000000V96TEAS-EECLOC","SageX3CutomerHeader"
"a0K28000000VzzsEAC","Active","a0J28000000V96TEAS","","ENAFLG","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V96TEAS-ENAFLG","SageX3CutomerHeader"
"a0K28000000VzztEAC","Tax rule","a0J28000000V96TEAS","","VACBPD","Char","","","BPC4_1","a0J28000000V96TEAS-VACBPD","SageX3CutomerHeader"
"a0K28000000VzzuEAC","Incoterm town","a0J28000000V96TEAS","","ICTCTY","Char","","","BPC4_1","a0J28000000V96TEAS-ICTCTY","SageX3CutomerHeader"
"a0K28000000VzzvEAC","Entity/Use","a0J28000000V96TEAS","","SSTENTCOD","Char","","","BPC4_1","a0J28000000V96TEAS-SSTENTCOD","SageX3CutomerHeader"
"a0K28000000VzzwEAC","Freight agent","a0J28000000V96TEAS","","FFWNUM","Char","","","BPC4_1","a0J28000000V96TEAS-FFWNUM","SageX3CutomerHeader"
"a0K28000000VzzxEAC","Forwarding agent address","a0J28000000V96TEAS","","FFWADD","Char","","","BPC4_1","a0J28000000V96TEAS-FFWADD","SageX3CutomerHeader"
"a0K28000000VzzyEAC","Default ship-to customer","a0J28000000V96TEAS","","BPDADDFLG","Integer","","1-No
2-Yes","BPC4_1","a0J28000000V96TEAS-BPDADDFLG","SageX3CutomerHeader"
"a0K28000000VzzzEAC","Export number","a0J28000000V96TEAS","","EXPNUM","Integer","","","BPC4_1","a0J28000000V96TEAS-EXPNUM","SageX3CutomerHeader"
"a0K28000000W000EAC","Creation user","a0J28000000V96TEAS","","CREUSR","Char","","","BPC4_1","a0J28000000V96TEAS-CREUSR","SageX3CutomerHeader"
"a0K28000000W001EAC","Date created","a0J28000000V96TEAS","","CREDAT","Date","","","BPC4_1","a0J28000000V96TEAS-CREDAT","SageX3CutomerHeader"
"a0K28000000W002EAC","Change user","a0J28000000V96TEAS","","UPDUSR","Char","","","BPC4_1","a0J28000000V96TEAS-UPDUSR","SageX3CutomerHeader"
"a0K28000000W003EAC","Change date","a0J28000000V96TEAS","","UPDDAT","Date","","","BPC4_1","a0J28000000V96TEAS-UPDDAT","SageX3CutomerHeader"
"a0K28000000W004EAC","Addr","a0J28000000V96TEAS","","BIDBPAADD","Char","","","BIDC_1","a0J28000000V96TEAS-BIDBPAADD","SageX3CutomerHeader"
"a0K28000000W005EAC","Country","a0J28000000V96TEAS","","BIDCRY","Char","","","BIDC_1","a0J28000000V96TEAS-BIDCRY","SageX3CutomerHeader"
"a0K28000000W006EAC","IBAN pref","a0J28000000V96TEAS","","IBAN","Char","","","BIDC_1","a0J28000000V96TEAS-IBAN","SageX3CutomerHeader"
"a0K28000000W007EAC","Bank ID number","a0J28000000V96TEAS","","BIDNUM","Char","","","BIDC_1","a0J28000000V96TEAS-BIDNUM","SageX3CutomerHeader"
"a0K28000000W008EAC","Default","a0J28000000V96TEAS","","BIDNUMFLG","Integer","","1-No
2-Yes","BIDC_1","a0J28000000V96TEAS-BIDNUMFLG","SageX3CutomerHeader"
"a0K28000000W009EAC","Curr.","a0J28000000V96TEAS","","BIDCUR","Char","","","BIDC_1","a0J28000000V96TEAS-BIDCUR","SageX3CutomerHeader"
"a0K28000000W00AEAS","Domicile","a0J28000000V96TEAS","","PAB1","Char","","","BIDC_1","a0J28000000V96TEAS-PAB1","SageX3CutomerHeader"
"a0K28000000W00BEAS","Beneficiary","a0J28000000V96TEAS","","BNF","Char","","","BIDC_1","a0J28000000V96TEAS-BNF","SageX3CutomerHeader"
"a0K28000000W00CEAS","Paying bank 2","a0J28000000V96TEAS","","PAB2","Char","","","BIDC_1","a0J28000000V96TEAS-PAB2","SageX3CutomerHeader"
"a0K28000000W00DEAS","Address 3","a0J28000000V96TEAS","","PAB3","Char","","","BIDC_1","a0J28000000V96TEAS-PAB3","SageX3CutomerHeader"
"a0K28000000W00EEAS","Address 4","a0J28000000V96TEAS","","PAB4","Char","","","BIDC_1","a0J28000000V96TEAS-PAB4","SageX3CutomerHeader"
"a0K28000000W00FEAS","BIC code","a0J28000000V96TEAS","","BICCOD","Char","","","BIDC_1","a0J28000000V96TEAS-BICCOD","SageX3CutomerHeader"
"a0K28000000W00GEAS","Intermediary bank","a0J28000000V96TEAS","","MIDPAB1","Char","","","BIDC_1","a0J28000000V96TEAS-MIDPAB1","SageX3CutomerHeader"
"a0K28000000W00HEAS","Paying bank 1","a0J28000000V96TEAS","","MIDPAB2","Char","","","BIDC_1","a0J28000000V96TEAS-MIDPAB2","SageX3CutomerHeader"
"a0K28000000W00IEAS","Paying bank 2","a0J28000000V96TEAS","","MIDPAB3","Char","","","BIDC_1","a0J28000000V96TEAS-MIDPAB3","SageX3CutomerHeader"
"a0K28000000W00JEAS","Address 3","a0J28000000V96TEAS","","MIDPAB4","Char","","","BIDC_1","a0J28000000V96TEAS-MIDPAB4","SageX3CutomerHeader"
"a0K28000000W00KEAS","BIC code","a0J28000000V96TEAS","","MIDBICCOD","Char","","","BIDC_1","a0J28000000V96TEAS-MIDBICCOD","SageX3CutomerHeader"
"a0K28000000W00LEAS","Country","a0J28000000V96TEAS","","MIDCRY","Char","","","BIDC_1","a0J28000000V96TEAS-MIDCRY","SageX3CutomerHeader"
"a0K28000000W00MEAS","Code","a0J28000000V96TEAS","","CCNCRM","Char","","","CNTC_1","a0J28000000V96TEAS-CCNCRM","SageX3CutomerHeader"
"a0K28000000W00NEAS","Surname","a0J28000000V96TEAS","","CNTLNA","Char","","","CNTC_1","a0J28000000V96TEAS-CNTLNA","SageX3CutomerHeader"
"a0K28000000W00OEAS","First name","a0J28000000V96TEAS","","CNTFNA","Char","","","CNTC_1","a0J28000000V96TEAS-CNTFNA","SageX3CutomerHeader"
"a0K28000000W00PEAS","Country","a0J28000000V96TEAS","","CNTCRY","Char","","","CNTC_1","a0J28000000V96TEAS-CNTCRY","SageX3CutomerHeader"
"a0K28000000W00QEAS","By default","a0J28000000V96TEAS","","CNTFLG","Integer","","1-No
2-Yes","CNTC_1","a0J28000000V96TEAS-CNTFLG","SageX3CutomerHeader"
"a0K28000000W00REAS","Title","a0J28000000V96TEAS","","CNTTTL","Integer","","1-Mr
2-Mrs
3-Ms","CNTC_1","a0J28000000V96TEAS-CNTTTL","SageX3CutomerHeader"
"a0K28000000W00SEAS","Function","a0J28000000V96TEAS","","CNTFNC","Integer","","1-CEO
2-Sales Director
3-Technical Director
4-Purchasing Director
5-Buyer
6-Inventory Director
7-Financial and Legal Director
8-Import/Export Director
9-Site Director
10-External Consultant
11-Other
12-REACH contact","CNTC_1","a0J28000000V96TEAS-CNTFNC","SageX3CutomerHeader"
"a0K28000000W00TEAS","Department","a0J28000000V96TEAS","","CNTSRV","Char","","","CNTC_1","a0J28000000V96TEAS-CNTSRV","SageX3CutomerHeader"
"a0K28000000W00UEAS","Address","a0J28000000V96TEAS","","CNTADD","Char","","","CNTC_1","a0J28000000V96TEAS-CNTADD","SageX3CutomerHeader"
"a0K28000000W00VEAS","Telephone","a0J28000000V96TEAS","","CNTTEL","Char","","","CNTC_1","a0J28000000V96TEAS-CNTTEL","SageX3CutomerHeader"
"a0K28000000W00WEAS","Fax","a0J28000000V96TEAS","","CNTFAX","Char","","","CNTC_1","a0J28000000V96TEAS-CNTFAX","SageX3CutomerHeader"
"a0K28000000W00XEAS","Mobile phone","a0J28000000V96TEAS","","CNTMOB","Char","","","CNTC_1","a0J28000000V96TEAS-CNTMOB","SageX3CutomerHeader"
"a0K28000000W00YEAS","Email","a0J28000000V96TEAS","","CNTWEB","Char","","","CNTC_1","a0J28000000V96TEAS-CNTWEB","SageX3CutomerHeader"
"a0K28000000W00ZEAS","Role","a0J28000000V96TEAS","","CNTMSS","Char","","","CNTC_1","a0J28000000V96TEAS-CNTMSS","SageX3CutomerHeader"
"a0K28000000W00aEAC","Birth date","a0J28000000V96TEAS","","CNTBIR","Date","","","CNTC_1","a0J28000000V96TEAS-CNTBIR","SageX3CutomerHeader"
"a0K28000000W00bEAC","Search key","a0J28000000V96TEAS","","CNTFULNAM","Char","","","CNTC_1","a0J28000000V96TEAS-CNTFULNAM","SageX3CutomerHeader"
"a0K28000000W00cEAC","Mailing prohibited","a0J28000000V96TEAS","","CNTFBDMAG","Integer","","1-No
2-Yes","CNTC_1","a0J28000000V96TEAS-CNTFBDMAG","SageX3CutomerHeader"
"a0K28000000W00dEAC","Language","a0J28000000V96TEAS","","CNTLAN","Char","","","CNTC_1","a0J28000000V96TEAS-CNTLAN","SageX3CutomerHeader"
"a0K28000000W00eEAC","Category","a0J28000000V96TEAS","","CNTCSP","Char","","","CNTC_1","a0J28000000V96TEAS-CNTCSP","SageX3CutomerHeader"
"a0K28000000W00fEAC","Flag","a0J28000000V96TEAS","","FLNEW","Integer","","","CNTC_1","a0J28000000V96TEAS-FLNEW","SageX3CutomerHeader"
"a0K28000000W00gEAC","Category","a0J28000000V96TEAS","","BCGCOD","Char","","","","a0J28000000V96TEAS-BCGCOD","SageX3CutomerHeader"
"a0K28000000W00hEAC","Active","a0J28000000V96TEAS","","BPCSTA","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-BPCSTA","SageX3CutomerHeader"
"a0K28000000W00iEAC","Customer","a0J28000000V96TEAS","","BPCNUM","Char","","","","a0J28000000V96TEAS-BPCNUM","SageX3CutomerHeader"
"a0K28000000W00jEAC","Name","a0J28000000V96TEAS","","BPCNAM","Char","","","","a0J28000000V96TEAS-BPCNAM","SageX3CutomerHeader"
"a0K28000000W00kEAC","Short description","a0J28000000V96TEAS","","BPRSHO","Char","","","","a0J28000000V96TEAS-BPRSHO","SageX3CutomerHeader"
"a0K28000000W00lEAC","Acronym","a0J28000000V96TEAS","","BPRLOG","Char","","","","a0J28000000V96TEAS-BPRLOG","SageX3CutomerHeader"
"a0K28000000W00mEAC","Physical person","a0J28000000V96TEAS","","LEGETT","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-LEGETT","SageX3CutomerHeader"
"a0K28000000W00nEAC","Country","a0J28000000V96TEAS","","CRY","Char","","","","a0J28000000V96TEAS-CRY","SageX3CutomerHeader"
"a0K28000000W00oEAC","Language","a0J28000000V96TEAS","","LAN","Char","","","","a0J28000000V96TEAS-LAN","SageX3CutomerHeader"
"a0K28000000W00pEAC","Site tax ID no.","a0J28000000V96TEAS","","CRN","Char","","","","a0J28000000V96TEAS-CRN","SageX3CutomerHeader"
"a0K28000000W00qEAC","SIC code","a0J28000000V96TEAS","","NAF","Char","","","","a0J28000000V96TEAS-NAF","SageX3CutomerHeader"
"a0K28000000W00rEAC","EU VAT no.","a0J28000000V96TEAS","","EECNUM","Char","","","","a0J28000000V96TEAS-EECNUM","SageX3CutomerHeader"
"a0K28000000W00sEAC","Currency","a0J28000000V96TEAS","","CUR","Char","","","","a0J28000000V96TEAS-CUR","SageX3CutomerHeader"
"a0K28000000W00tEAC","Mailing prohibited","a0J28000000V96TEAS","","BPRFBDMAG","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-BPRFBDMAG","SageX3CutomerHeader"
"a0K28000000W00uEAC","Intersites","a0J28000000V96TEAS","","BETFCY","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-BETFCY","SageX3CutomerHeader"
"a0K28000000W00vEAC","Site","a0J28000000V96TEAS","","FCY","Char","","","","a0J28000000V96TEAS-FCY","SageX3CutomerHeader"
"a0K28000000W00wEAC","Customer","a0J28000000V96TEAS","","BPCFLG","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-BPCFLG","SageX3CutomerHeader"
"a0K28000000W00xEAC","Sales rep","a0J28000000V96TEAS","","REPFLG","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-REPFLG","SageX3CutomerHeader"
"a0K28000000W00yEAC","Prospect","a0J28000000V96TEAS","","PPTFLG","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-PPTFLG","SageX3CutomerHeader"
"a0K28000000W00zEAC","Supplier","a0J28000000V96TEAS","","BPSFLG","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-BPSFLG","SageX3CutomerHeader"
"a0K28000000W010EAC","Miscellaneous BP","a0J28000000V96TEAS","","BPRACC","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-BPRACC","SageX3CutomerHeader"
"a0K28000000W011EAC","Service supplier","a0J28000000V96TEAS","","PRVFLG","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-PRVFLG","SageX3CutomerHeader"
"a0K28000000W012EAC","Carrier","a0J28000000V96TEAS","","BPTFLG","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-BPTFLG","SageX3CutomerHeader"
"a0K28000000W013EAC","Service caller","a0J28000000V96TEAS","","DOOFLG","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-DOOFLG","SageX3CutomerHeader"
"a0K28000000W014EAC","Identifier","a0J28000000V96TEAS","","IDENT","Char","","","","a0J28000000V96TEAS-IDENT","SageX3CutomerHeader"
"a0K28000000W015EAC","Address","a0J28000000V96TEAS","","CODADR","Char","","","BPAC_1","a0J28000000V96TEAS-CODADR","SageX3CutomerHeader"
"a0K28000000W016EAC","Description","a0J28000000V96TEAS","","BPADES","Char","","","BPAC_1","a0J28000000V96TEAS-BPADES","SageX3CutomerHeader"
"a0K28000000W017EAC","Country","a0J28000000V96TEAS","","BPACRY","Char","","","BPAC_1","a0J28000000V96TEAS-BPACRY","SageX3CutomerHeader"
"a0K28000000W018EAC","Country name","a0J28000000V96TEAS","","CRYNAM","Char","","","BPAC_1","a0J28000000V96TEAS-CRYNAM","SageX3CutomerHeader"
"a0K28000000W019EAC","Address","a0J28000000V96TEAS","","ADDLIG1","Char","","","BPAC_1","a0J28000000V96TEAS-ADDLIG1","SageX3CutomerHeader"
"a0K28000000W01AEAS","Address","a0J28000000V96TEAS","","ADDLIG2","Char","","","BPAC_1","a0J28000000V96TEAS-ADDLIG2","SageX3CutomerHeader"
"a0K28000000W01BEAS","Address","a0J28000000V96TEAS","","ADDLIG3","Char","","","BPAC_1","a0J28000000V96TEAS-ADDLIG3","SageX3CutomerHeader"
"a0K28000000W01CEAS","Postal code","a0J28000000V96TEAS","","POSCOD","Char","","","BPAC_1","a0J28000000V96TEAS-POSCOD","SageX3CutomerHeader"
"a0K28000000W01DEAS","City","a0J28000000V96TEAS","","CTY","Char","","","BPAC_1","a0J28000000V96TEAS-CTY","SageX3CutomerHeader"
"a0K28000000W01EEAS","Region (county, state, ..)","a0J28000000V96TEAS","","SAT","Char","","","BPAC_1","a0J28000000V96TEAS-SAT","SageX3CutomerHeader"
"a0K28000000W01FEAS","Telephone","a0J28000000V96TEAS","","TEL1","Char","","","BPAC_1","a0J28000000V96TEAS-TEL1","SageX3CutomerHeader"
"a0K28000000W01GEAS","Email","a0J28000000V96TEAS","","WEB1","Char","","","BPAC_1","a0J28000000V96TEAS-WEB1","SageX3CutomerHeader"
"a0K28000000W01HEAS","Website","a0J28000000V96TEAS","","FCYWEB","Char","","","BPAC_1","a0J28000000V96TEAS-FCYWEB","SageX3CutomerHeader"
"a0K28000000W01IEAS","External identifier","a0J28000000V96TEAS","","EXTNUM","Char","","","BPAC_1","a0J28000000V96TEAS-EXTNUM","SageX3CutomerHeader"
"a0K28000000W01JEAS","Default","a0J28000000V96TEAS","","BPAADDFLG","Integer","","1-No
2-Yes","BPAC_1","a0J28000000V96TEAS-BPAADDFLG","SageX3CutomerHeader"
"a0K28000000W01KEAS","Flag","a0J28000000V96TEAS","","FLMOD","Integer","","","BPAC_1","a0J28000000V96TEAS-FLMOD","SageX3CutomerHeader"
"a0K28000000W01LEAS","Validated","a0J28000000V96TEAS","","ADRVAL","Integer","","1-No
2-Yes","BPAC_1","a0J28000000V96TEAS-ADRVAL","SageX3CutomerHeader"
"a0K28000000W01MEAS","Flag","a0J28000000V96TEAS","","FLMODFONC","Integer","","","BPAC_1","a0J28000000V96TEAS-FLMODFONC","SageX3CutomerHeader"
"a0K28000000W01NEAS","ABC class","a0J28000000V96TEAS","","ABCCLS","Integer","","1-Class A
2-Class B
3-Class C
4-Class D","","a0J28000000V96TEAS-ABCCLS","SageX3CutomerHeader"
"a0K28000000W01OEAS","Minimum order","a0J28000000V96TEAS","","WORDMINAMT","Decimal","","","","a0J28000000V96TEAS-WORDMINAMT","SageX3CutomerHeader"
"a0K28000000W01PEAS","Allow order close","a0J28000000V96TEAS","","ORDCLE","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-ORDCLE","SageX3CutomerHeader"
"a0K28000000W01QEAS","Loan authorized","a0J28000000V96TEAS","","LNDAUZ","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-LNDAUZ","SageX3CutomerHeader"
"a0K28000000W01REAS","One order per deliv","a0J28000000V96TEAS","","ODL","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-ODL","SageX3CutomerHeader"
"a0K28000000W01SEAS","Partial delivery","a0J28000000V96TEAS","","DME","Integer","","1-Allowed
2-Ship line complete
3-Ship order complete","","a0J28000000V96TEAS-DME","SageX3CutomerHeader"
"a0K28000000W01TEAS","Price / Amount type","a0J28000000V96TEAS","","PRITYP","Integer","","1-Exclude tax
2-Include tax","","a0J28000000V96TEAS-PRITYP","SageX3CutomerHeader"
"a0K28000000W01UEAS","Freight invoicing","a0J28000000V96TEAS","","FREINV","Integer","","1-Invoiced
2-Not invoiced
3-Until threshold 1
4-Until threshold 2
5-Until threshold 3
6-Until threshold 4
7-Until threshold 5","","a0J28000000V96TEAS-FREINV","SageX3CutomerHeader"
"a0K28000000W01VEAS","Invoicing mode","a0J28000000V96TEAS","","IME","Integer","","1-One/Shipment
2-One/Closed order
3-One/Order
4-One/Ship to
5-One/Period
6-Manual","","a0J28000000V96TEAS-IME","SageX3CutomerHeader"
"a0K28000000W01WEAS","Invoice period","a0J28000000V96TEAS","","INVPER","Integer","","1-Per request
2-Daily
3-Weekly
4-10 day period
5-2 week period
6-Monthly","","a0J28000000V96TEAS-INVPER","SageX3CutomerHeader"
"a0K28000000W01XEAS","Invoice","a0J28000000V96TEAS","","WINVTEX","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-WINVTEX","SageX3CutomerHeader"
"a0K28000000W01YEAS","Due date origin","a0J28000000V96TEAS","","DUDCLC","Integer","","1-Invoice date
2-Shipment date","","a0J28000000V96TEAS-DUDCLC","SageX3CutomerHeader"
"a0K28000000W01ZEAS","Commission category","a0J28000000V96TEAS","","COMCAT","Integer","","1-Category 1
2-Category 2
3-Category 3","","a0J28000000V96TEAS-COMCAT","SageX3CutomerHeader"
"a0K28000000W01aEAC","Order","a0J28000000V96TEAS","","WORDTEX","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-WORDTEX","SageX3CutomerHeader"
"a0K28000000W01bEAC","Print ack.","a0J28000000V96TEAS","","OCNFLG","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-OCNFLG","SageX3CutomerHeader"
"a0K28000000W01cEAC","Template code","a0J28000000V96TEAS","","TPMCOD","Char","","","","a0J28000000V96TEAS-TPMCOD","SageX3CutomerHeader"
"a0K28000000W01dEAC","No.","a0J28000000V96TEAS","","INVDTA","Integer","","","BPC1_6","a0J28000000V96TEAS-INVDTA","SageX3CutomerHeader"
"a0K28000000W01eEAC","Description","a0J28000000V96TEAS","","SHO","Char","","","BPC1_6","a0J28000000V96TEAS-SHO","SageX3CutomerHeader"
"a0K28000000W01fEAC","% or amount","a0J28000000V96TEAS","","INVDTAAMT","Decimal","","","BPC1_6","a0J28000000V96TEAS-INVDTAAMT","SageX3CutomerHeader"
"a0K28000000W01gEAC","Curr.","a0J28000000V96TEAS","","WWCUR","Char","","","BPC1_6","a0J28000000V96TEAS-WWCUR","SageX3CutomerHeader"
"a0K28000000W01hEAC","Customer type","a0J28000000V96TEAS","","BPCTYP","Integer","","1-Normal
2-Miscellaneous
3-Intra-company
4-Prospect","","a0J28000000V96TEAS-BPCTYP","SageX3CutomerHeader"
"a0K28000000W01iEAC","Our supplier no.","a0J28000000V96TEAS","","BPCBPSNUM","Char","","","","a0J28000000V96TEAS-BPCBPSNUM","SageX3CutomerHeader"
"a0K28000000W01jEAC","Rate type","a0J28000000V96TEAS","","CHGTYP","Integer","","1-Daily Rate
2-Monthly Rate
3-Average Rate
4-Customs Doc File exchange","","a0J28000000V96TEAS-CHGTYP","SageX3CutomerHeader"
"a0K28000000W01kEAC","Credit control","a0J28000000V96TEAS","","OSTCTL","Integer","","1-Check
2-No Check
3-Hold","","a0J28000000V96TEAS-OSTCTL","SageX3CutomerHeader"
"a0K28000000W01lEAC","Authorized credit","a0J28000000V96TEAS","","WOSTAUZ","Decimal","","","","a0J28000000V96TEAS-WOSTAUZ","SageX3CutomerHeader"
"a0K28000000W01mEAC","Credit level total","a0J28000000V96TEAS","","XOST","Decimal","","","","a0J28000000V96TEAS-XOST","SageX3CutomerHeader"
"a0K28000000W01nEAC","Credit insurance","a0J28000000V96TEAS","","WCDTISR","Decimal","","","","a0J28000000V96TEAS-WCDTISR","SageX3CutomerHeader"
"a0K28000000W01oEAC","Insurance date","a0J28000000V96TEAS","","CDTISRDAT","Date","","","","a0J28000000V96TEAS-CDTISRDAT","SageX3CutomerHeader"
"a0K28000000W01pEAC","Ins. company","a0J28000000V96TEAS","","BPCCDTISR","Char","","","","a0J28000000V96TEAS-BPCCDTISR","SageX3CutomerHeader"
"a0K28000000W01qEAC","Customer notes","a0J28000000V96TEAS","","BPCNOTE","Char","","","","a0J28000000V96TEAS-BPCNOTE","SageX3CutomerHeader"
"a0K28000000W01rEAC","Business","a0J28000000V96TEAS","","BUS","Char","","","","a0J28000000V96TEAS-BUS","SageX3CutomerHeader"
"a0K28000000W01sEAC","Source","a0J28000000V96TEAS","","ORIPPT","Char","","","","a0J28000000V96TEAS-ORIPPT","SageX3CutomerHeader"
"a0K28000000W01tEAC","Customer since","a0J28000000V96TEAS","","BPCSNCDAT","Date","","","","a0J28000000V96TEAS-BPCSNCDAT","SageX3CutomerHeader"
"a0K28000000W01uEAC","Token credits","a0J28000000V96TEAS","","PITCDT","Integer","","","","a0J28000000V96TEAS-PITCDT","SageX3CutomerHeader"
"a0K28000000W01vEAC","Manual supplement","a0J28000000V96TEAS","","PITCPT","Integer","","","","a0J28000000V96TEAS-PITCPT","SageX3CutomerHeader"
"a0K28000000W01wEAC","Total token credit","a0J28000000V96TEAS","","TOTPIT","Integer","","","","a0J28000000V96TEAS-TOTPIT","SageX3CutomerHeader"
"a0K28000000W01xEAC","Points debit","a0J28000000V96TEAS","","BPCPITDEB","Integer","","","","a0J28000000V96TEAS-BPCPITDEB","SageX3CutomerHeader"
"a0K28000000W01yEAC","Value  0","a0J28000000V96TEAS","","NULPIO","Integer","","1-No
2-Yes","","a0J28000000V96TEAS-NULPIO","SageX3CutomerHeader"
"a0K28000000W01zEAC","Chosen service","a0J28000000V96TEAS","","COTCHX","Char","","","","a0J28000000V96TEAS-COTCHX","SageX3CutomerHeader"
"a0K28000000W020EAC","Tokens necessary","a0J28000000V96TEAS","","COTPITRQD","Integer","","","","a0J28000000V96TEAS-COTPITRQD","SageX3CutomerHeader"
"a0K28000000W021EAC","Bill-to customer","a0J28000000V96TEAS","","BPCINV","Char","","","","a0J28000000V96TEAS-BPCINV","SageX3CutomerHeader"
"a0K28000000W022EAC","Pay by","a0J28000000V96TEAS","","BPCPYR","Char","","","","a0J28000000V96TEAS-BPCPYR","SageX3CutomerHeader"
"a0K28000000W023EAC","Factor","a0J28000000V96TEAS","","FCTNUM","Char","","","","a0J28000000V96TEAS-FCTNUM","SageX3CutomerHeader"
"a0K28000000W024EAC","Group customer","a0J28000000V96TEAS","","BPCGRU","Char","","","","a0J28000000V96TEAS-BPCGRU","SageX3CutomerHeader"
"a0K28000000W025EAC","Risk BP","a0J28000000V96TEAS","","BPCRSK","Char","","","","a0J28000000V96TEAS-BPCRSK","SageX3CutomerHeader"
"a0K28000000W026EAC","Exemption no.","a0J28000000V96TEAS","","VATEXN","Char","","","","a0J28000000V96TEAS-VATEXN","SageX3CutomerHeader"
"a0K28000000W027EAC","Accounting code","a0J28000000V96TEAS","","ACCCOD","Char","","","","a0J28000000V96TEAS-ACCCOD","SageX3CutomerHeader"
"a0K28000000W028EAC","Account structure","a0J28000000V96TEAS","","DIA","Char","","","","a0J28000000V96TEAS-DIA","SageX3CutomerHeader"
"a0K28000000W029EAC","Tax rule","a0J28000000V96TEAS","","VACBPR","Char","","","","a0J28000000V96TEAS-VACBPR","SageX3CutomerHeader"
"a0K28000000W02AEAS","Payment terms","a0J28000000V96TEAS","","PTE","Char","","","","a0J28000000V96TEAS-PTE","SageX3CutomerHeader"
"a0K28000000W02BEAS","Payment days","a0J28000000V96TEAS","","J1","Integer","","","","a0J28000000V96TEAS-J1","SageX3CutomerHeader"
"a0K28000000W02CEAS","Unavailable","a0J28000000V96TEAS","","UVYCOD2","Char","","","","a0J28000000V96TEAS-UVYCOD2","SageX3CutomerHeader"
"a0K28000000W02DEAS","Settlement discount","a0J28000000V96TEAS","","DEP","Char","","","","a0J28000000V96TEAS-DEP","SageX3CutomerHeader"
